### ISSUE TITLE
Only Import Single Pool

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#101]
Is it possible to choose to import only a single pool? From what I understand setting ```zpool cachefile=/etc/zfs/zpool.cache <pool>``` should only import the specified pool. I've been unable to do this. 

I already have an existing root on zfs install and I was attempting to create another pool to use for another install. After I set up the install as normal and booted, I found that both of my pools were importing on top of each other when I had only set the cachefiles to boot one. How should it properly be specified that only one pool should be imported as opposed to all of the pools? Do I need to edit the systemd units? Or am I doing it wrong?

**Comment by johnramsden** [comment]
I just thought of something, should I be setting  ```canmount=noauto``` to all my datasets to avoid this? I guess that would have avoided the problem of my data sets being mounted on top of each other, but what I would really like would be for only my specified pool to be imported at all.

**Comment by Kiwwiaq** [comment]
Hi,

File `/etc/zfs/zpool.cache` is a list of all known imported pools, that will be re-imported after reboot. Setting the file in pool config will tell ZFS where to store this information.

Try this, it **should** work:
- deport pool you don`t like
- delete the cache file
- recreate the cache file for pool you like to import -> `zpool set cachefile=/etc/zfs/zpool.cache <pool>`

**Comment by johnramsden** [comment]
Yea, that Is how I understood it should work, the reason I commented year was that it wasn't. I'll give it another shot.
