### ISSUE TITLE
Installing Arch via ISO on ZFS - can't really do it anymore.

### ISSUE THREAD

**Issue by alaricljs** [archzfs/archzfs#108]
zfs-git isn't in aur anymore, and http://archzfs.com/archzfs/x86_64/ isn't tracking archiso releases any more.

@demizer is there a reason archiso packages aren't being built any more?

**Comment by demizer** [comment]
Archiso packages got left behind a bit when I refactored the build scripts. I will pick them back up once I get the latest refactoring working.

**Comment by alaricljs** [comment]
Great thanks.  If this is a process that's not yet automated I'd be willing to lend a hand.
