### ISSUE TITLE
Specify the order that datasets are mounted at boot

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#109]
Is it possible to specify the order that datasets are mounted at boot? Right now the problem I'm having with multiple datasets is the order that they are mounted at boot seems almost random. Datasets end up getting into a race condition with the operating system, which ends up creating the missing directories and then the datasets won't mount.

I'm trying to use the folllowing setup, but depending on the order I mount them, sometimes `/var/log` and `/var/log/journal` dont mount.

```
# zfs list
NAME                                          USED  AVAIL  REFER  MOUNTPOINT
vault                                        1020M   859G    96K  none
vault/ROOT                                    727M   859G    96K  none
vault/ROOT/default                            727M   859G  4.42M  /
vault/ROOT/default/opt                         96K   859G    96K  /opt
vault/ROOT/default/usr                        708M   859G  75.3M  /usr
vault/ROOT/default/usr/lib                    456M   859G   455M  /usr/lib
vault/ROOT/default/usr/local                  168K   859G   104K  /usr/local
vault/ROOT/default/usr/share                  176M   859G   172M  /usr/share
vault/ROOT/default/var                       14.2M   859G  1.32M  /var
vault/ROOT/default/var/lib                   11.6M   859G   148K  /var/lib
vault/ROOT/default/var/lib/pacman            10.9M   859G  10.9M  /var/lib/pacman
vault/ROOT/default/var/lib/systemd            448K   859G   160K  /var/lib/systemd
vault/ROOT/default/var/lib/systemd/coredump   160K   859G    96K  /var/lib/systemd/coredump
vault/usr                                      96K   859G    96K  none
vault/var                                     289M   859G    96K  none
vault/var/cache                               287M   859G   287M  /var/cache
vault/var/lib                                 384K   859G    96K  none
vault/var/lib/lxc                              96K   859G    96K  /var/lib/lxc
vault/var/lib/lxd                              96K   859G    96K  /var/lib/lxd
vault/var/lib/machines                         96K   859G    96K  /var/lib/machines
vault/var/log                                 700K   859G   132K  /var/log
vault/var/log/journal                          96K   859G    96K  /var/log/journal
```

It seems like part of the issue is related to `vault/var/log` and `vault/var/log/journal` not being children of `vault/ROOT/default/var`. 

I end up with errors:

```
Feb 24 23:08:49 skel zfs[2991]: cannot mount '/var/log': directory is not empty
Feb 24 23:08:49 skel zfs[2991]: cannot mount '/var/log/journal': directory is not empty
```

Does anyone have any advice? Do I need a custom hook?

I'm able to make the current setup work, but only if /var/log and /var/log/journal are legacy.

**Comment by haraldkoch** [comment]
I'm curious - why do you want to split your root filesystem into so many datasets?

**Comment by johnramsden** [comment]
For one thing, if boot environments are used and your logs are out of the boot environment dataset, they can be persistent between the separate boot environments. The more everything is split up, the more specific you can be about what is, and what isn't part of the boot environment.

Also, it's nice to be able to snapshot, and backup small datasets, and only the parts you need rather than everything.
