### ISSUE TITLE
Support for shadowing ?

### ISSUE THREAD

**Issue by aletessier** [archzfs/archzfs#111]
Shadow migration is a process that pulls the data to be migrated:

Create an empty ZFS file system.

Set the shadow property on an empty ZFS file system, which is the target (or shadow) file system, to point to the file system to be migrated. For example:

    # zfs create -o shadow=nfs://system/export/home/ufsdata users/home/shadow2
Data from the file system to be migrated is copied over to the shadow file system. For step-by-step instructions, see Migrating ZFS File Systems in Oracle Solaris Administration: ZFS File Systems.

https://docs.oracle.com/cd/E23824_01/html/E24456/filesystem-3.html

% sudo zfs get all z | grep shadow
1 alex@node-747b ~

I installed zfs on archlinux recently and it seems shadowing is not present ?

**Comment by aletessier** [comment]
% sudo zfs get all z | grep shadow
1 alex@node-747b ~

I installed zfs on archlinux recently and it seems shadowing is not present ?

**Comment by demizer** [comment]
Doesn't look like this feature is available in ZFSonLinux (OpenZFS). Closing at Wontfix.
