### ISSUE TITLE
zfs-archiso-linux not up to date with latest archiso kernel

### ISSUE THREAD

**Issue by Toasterson** [archzfs/archzfs#115]
Latest archiso has kernel 4.10.6 and the zfs-archiso-linux still requires 4.7.2 could you update the package? Or do I need to use another repo to get zfs working on a default archiso.

**Comment by pztrn** [comment]
Bump. 4.10.11 is here.

**Comment by demizer** [comment]
I will fix this later tonight, the scripts were refactored a while back and support for deploying archiso updates were never finished due to lack of time.
