### ISSUE TITLE
SPL & GCC 7

### ISSUE THREAD

**Issue by f3dup** [archzfs/archzfs#121]
Hello,

SPL build fails on various incompatible-pointer-types errors with GCC 7. Downgrading to GCC 6 helps bypassing the related errors.

Here's an example of what can be seen in the build output:
```
In file included from ./include/linux/seqlock.h:35:0,
                 from ./include/linux/time.h:5,
                 from ./include/linux/stat.h:18,
                 from ./include/linux/module.h:10,
                 from /home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/include/sys/sysmacros.h:28,
                 from /home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/include/sys/types.h:29,
                 from /home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/include/sys/rwlock.h:28,
                 from /home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/module/spl/spl-rwlock.c:27:
/home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/include/sys/rwlock.h: In function 'spl_rw_set_owner':
/home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/include/sys/rwlock.h:55:32: error: passing argument 1 of 'spinlock_check' from incompatible pointer type [-Werror=incompatible-pointer-types]
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
                                ^
./include/linux/spinlock.h:208:34: note: in definition of macro 'raw_spin_lock_irqsave'
   flags = _raw_spin_lock_irqsave(lock); \
                                  ^~~~
/home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/include/linux/rwsem_compat.h:55:46: note: in expansion of macro 'spin_lock_irqsave'
 #define spl_rwsem_lock_irqsave(lk, fl)       spin_lock_irqsave(lk, fl)
                                              ^~~~~~~~~~~~~~~~~
/home/f3dup/tmp/spl-linux-lts/src/spl-0.6.5.9/include/sys/rwlock.h:55:9: note: in expansion of macro 'spl_rwsem_lock_irqsave'
         spl_rwsem_lock_irqsave(&SEM(rwp)->wait_lock, flags);
         ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sq3** [comment]
I installed an older gcc version and kernel from `/var/cache/packman/pkg`. Than rebuild the kernel modules with dkms. Works fine for me as an quick fix.

```
$ pacman -U gcc-6.3.1-2-x86_64.pkg.tar.xz ./gcc-libs-6.3.1-2-x86_64.pkg.tar.xz
$ pacman -U linux-lts-4.4.50-1-x86_64.pkg.tar.xz linux-lts-headers-4.4.50-1-x86_64.pkg.tar.xz
$ dkms autoinstall
```

**Comment by omgold** [comment]
Why not simply disable the error? This helps for me:
```
--- PKGBUILD.orig	2017-06-21 10:00:49.054941221 +0200
+++ PKGBUILD	2017-06-21 10:00:10.220622337 +0200
@@ -38,7 +38,7 @@
                 --with-linux=/usr/lib/modules/4.9.30-1-lts/build \
                 --with-linux-obj=/usr/lib/modules/4.9.30-1-lts/build \
                 --with-config=kernel
-    make
+    make KCFLAGS="-Wno-error=incompatible-pointer-types"
 }
 
 package() {
```

**Comment by demizer** [comment]
I don't want to disable anything using parameters because the build works on gcc 7.1 with spl master branch. I'm waiting for them to make another stable release and we should be golden.

**Comment by omgold** [comment]
Are you sure? It might still take months until zfsonlinux 7.0 is declared stable.

**Comment by demizer** [comment]
@omgold the next version is 0.6.5.11, which is planned at https://github.com/zfsonlinux/spl/projects/1#card-3418392

I don't think it will be months before the next release, but if it is not made in the next week or two, I will use your patch and push packages out.

Thanks!

**Comment by bobwya** [comment]
@demizer  any chance of rev-bump to support **linux-lts** **4.9.34** ?

I stupidly did a partial upgrade... Now, with my pinned LTS kernel version, Samba won't start (doesn't affect me - but does affect other users of my NAS)...

Appreciate all your hard work as always!

**Comment by demizer** [comment]
@bobwya done. Thanks. I was having problems pushing to AUR. It seems the AUR devs fixed it sometime last night.

**Comment by bobwya** [comment]
@demizer I was just tacking on to this issue thread - but actually thinking about your [unofficial ZFS repository](http://demizerone.com/archzfs/x86_64/)... 
Am I stuck switching to **zfs-git** branch - if I want up-to-date **linux-lts** support??
Thanks

**Comment by KrzaQ** [comment]
I still cannot update via the normal pacman route:

```
pacman -Syuu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 archzfs is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: spl-linux-lts: installing linux-lts (4.9.37-1) breaks dependency 'linux-lts=4.9.30'
:: zfs-linux-lts: installing linux-lts (4.9.37-1) breaks dependency 'linux-lts=4.9.30'
:: zfs-utils-linux-lts: installing linux-lts (4.9.37-1) breaks dependency 'linux-lts=4.9.30'
```
Is there something I should do, or just wait?

**Comment by minextu** [comment]
Packages have not yet been updated, you will have to wait for that
