### ISSUE TITLE
Update for linux-lts 4.9.31

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#122]

**Comment by jacksonatl** [comment]
Any update on this? LTS kernel was released almost a week ago now.

**Comment by smorks** [comment]
probably waiting for #121 to be fixed.

**Comment by demizer** [comment]
@smorks is correct, archzfs stable is dead in the water until the gcc 7.1.1 build errors are fixed upstream in OpenZFS. Until then I plan on trying to get archzfs-lts-git packages out so users have an upgrade path if they so choose.

**Comment by KrzaQ** [comment]
It took me embarrassingly long to find a way to update the rest of the system, so I'll leave it here in case someone finds it helpful:
`pacman -Syuu --ignore=linux-lts`

**Comment by demizer** [comment]
For those that can't wait, I have created the archzfs-linux-lts-git package group. You can get the PKGBUILDS from AUR or from the archzfs repository.

**Comment by illum1n4ti** [comment]
Hello

I am getting the following error 

error: failed to prepare transaction (could not satisfy dependencies)
:: spl-linux-lts: installing linux-lts (4.9.34-1) breaks dependency 'linux-lts=4.9.30'
:: zfs-linux-lts: installing linux-lts (4.9.34-1) breaks dependency 'linux-lts=4.9.30'
:: zfs-utils-linux-lts: installing linux-lts (4.9.34-1) breaks dependency 'linux-lts=4.9.30'

I hope u could update the repo

**Comment by risto3** [comment]
I tried to upgrade to the archzfs-linux-lts-git  flavor, but there seems to be weird dependency issue... 
```
$ LANG=C sudo pacman -Syu  archzfs-linux-lts-git 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 archzfs is up to date
:: There are 4 members in group archzfs-linux-lts-git:
:: Repository archzfs
   1) spl-linux-lts-git  2) spl-utils-linux-lts-git  3) zfs-linux-lts-git  4) zfs-utils-linux-lts-git

Enter a selection (default=all): 
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
:: spl-linux-lts-git and spl-utils-linux-lts are in conflict. Remove spl-utils-linux-lts? [y/N] y
:: zfs-linux-lts-git and zfs-linux-lts are in conflict. Remove zfs-linux-lts? [y/N] y
:: zfs-utils-linux-lts-git and zfs-utils-linux-lts are in conflict. Remove zfs-utils-linux-lts? [y/N] y
error: failed to prepare transaction (could not satisfy dependencies)
:: spl-linux-lts: removing spl-utils-linux-lts breaks dependency 'spl-utils-linux-lts'
:: spl-linux-lts: installing linux-lts (4.9.36-1) breaks dependency 'linux-lts=4.9.30'
```
shouldn't the first conflict be: 'spl-linux-lts-git and spl-linux-lts'  such that spl-linux-lts get replaced?
spl-utils-linux-git should then conflict and replace spl-utils-linux ...
