### ISSUE TITLE
can't destroy dataset while samba share using.

### ISSUE THREAD

**Issue by morphinz** [archzfs/archzfs#133]
Hello. 
I cant destroy if someone using samba share. 
I was able to destory in Unix ZFS with -F parameter.

**Comment by demizer** [comment]
Hello, thank you for the report, but I do not think this is a packaging problem. In my experience, major filesystem operations can only be performed if the filesystem is not in use.

Do you have output of the error that resulted?

**Comment by morphinz** [comment]
```
[root@test test]# zfs destroy testPool/test
umount: /testPool/test: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
cannot unmount '/testPool/test': umount failed
```

```
[root@test test]# zfs destroy -f testPool/test
umount: /testPool/test: target is busy
        (In some cases useful info about processes that
         use the device is found by lsof(8) or fuser(1).)
cannot unmount '/testPool/test': umount failed
```

**Comment by storrgie** [comment]
Restart smbd and attempt to destroy again. Also make sure your present working directory is not the same as what you're trying to destroy. This is not an archzfs issue, please close this.

**Comment by morphinz** [comment]
When you restart smbd, all shares are affected. I can't restart smbd for a dataset (one share).  
Ok i will figure out something else But still zfs should be able to destroy even if someone uses it.
