### ISSUE TITLE
Status in README?

### ISSUE THREAD

**Issue by andrewgdunn** [archzfs/archzfs#135]
A bit of a meta comment, but it would likely cut down on some of the reported issues in this repo if the readme were to have some table showing the status of the current builds, as well as a suggesting to run the `-git` builds if you're wanting to move quickly.

**Comment by demizer** [comment]
I think this is a great idea. I will start working on this this week. We'll need to mention the status on the Arch Wiki ZFS page as well.

**Comment by demizer** [comment]
Another option is to use the wiki https://github.com/archzfs/archzfs/wiki
