### ISSUE TITLE
Strange behavior on Kernel 4.12 - Upgrade git-Tree to zfs/spl 0.7.0 RC 5?

### ISSUE THREAD

**Issue by grizzlyfred** [archzfs/archzfs#136]
Kernel 4.12 refuses to work with the "normal" zfs-linux412 packages, bacause it fails to mount zvols - which mount absolutely fine on 4.11 with a strange "error 17".
I tried to build from aur-git, but that is pinned to kernel 4.11 and rc4.
Could you upgrade?

**Comment by demizer** [comment]
Hello, thanks for the report. I am currently building for OpenZFS 0.7.0. Let's see if the new version fixes your problem. Hopefully I will push out the new packages tonight. Thanks!

**Comment by demizer** [comment]
The 0.7.0 packages have been updated. Thanks!
