### ISSUE TITLE
Update pre-built packages for linux-lts 4.9.43-1

### ISSUE THREAD

**Issue by bobwya** [archzfs/archzfs#170]
Please can we get an update for the pre-built packages in your unofficial [archzfs repository](http://demizerone.com/archzfs/x86_64/) to support the **core/linux-lts 4.9.43-1** ...
Thanks

**Comment by demizer** [comment]
Yup, sorry for the late updates everyone. I am slammed at work and don't have much time as of late.

**Comment by demizer** [comment]
Update has been pushed out.
