### ISSUE TITLE
add pkgver() to PKGBUILD

### ISSUE THREAD

**Issue by Finic8** [archzfs/archzfs#171]
When building the packages from the aur, the package version does not get updated even if there are new commits. This creates all kinds of errors and checksum mismatches since the pkg name stays the same even though the package already includes newer commits and has therefore a different hash.

So could we possibly add the pkgver() function to the PKGBUILDs like the Arch Wiki suggests for git packages?

Something like:
> pkgver() {
    cd "${srcdir}/zfs"
    git describe --match "zfs-*" --long --tags | sed -e 's|zfs-||' -e 's|-\([0-9]*-g\)|-r\1|' -e 's|[-: ]|_|g'
   }

**Comment by demizer** [comment]
We should use this.
