### ISSUE TITLE
Zen kernel v4.12.8 is now available

### ISSUE THREAD

**Issue by charlesmilette** [archzfs/archzfs#173]
Please rebuild the packages against this new version

**Comment by demizer** [comment]
Sorry about that. I did not have checks in the scraper.sh script for the zen kernel. These have been added and the packages have been updated. Thanks!

**Comment by storrgie** [comment]
@demizer might have an issue with loction/naming:

```
error: failed retrieving file 'zfs-linux-0.7.1.4.12.8.1-1-x86_64.pkg.tar.xz' from archzfs.com : The requested URL returned error: 404
```

**Comment by charlesmilette** [comment]
It worked on my machine.

**Comment by demizer** [comment]
@storrgie that's a different problem, I will push a fix.

**Comment by demizer** [comment]
@storrgie fixed

**Comment by storrgie** [comment]
@demizer can comfirm working, you're awesome.
