### ISSUE TITLE
Unable to update packages

### ISSUE THREAD

**Issue by demizer** [archzfs/archzfs#190]
I am traveling and can't access my home server to update packages due to a configuration error on my router.

The packages will remain out-of-date until I return from vacation on Saturday December 02.

**Comment by storrgie** [comment]
Enjoy it!

Is there a way I can buy you a beer or something? We're using this project a ton of servers and very much appreciate the work!

**Comment by stevleibelt** [comment]
@demizer 
thanks for letting us knw. Enjoy your trip and don't get stressed. Things are working so far.

Cheers and thanks for all your work!
