### ISSUE TITLE
Update SPL (Git?) to 0.7.4-pre to include support for 4.14 kernels

### ISSUE THREAD

**Issue by kode54** [archzfs/archzfs#191]
The latest commit, as of this writing:

zfsonlinux/spl@ed19bccfb651843fa208232b3a2d3d22a4152bc8

... is required to support 4.14 kernels, as they de-exported vfs_read/vfs_write, and added new functionality to existing functions, so now SPL either uses the new functionality, or falls back to wrappers that use the older functions.

My AUR kernel has already jumped onto 4.14, so I'm running a release behind for the time being, but it probably won't be long before the Arch kernel package updates to some 4.14 release.

I assume this will have to make it into the Git package? The version on spl-dkms-git and zfs-dkms-git looks suspiciously behind, unless I am to understand that 0.7.3 was never tagged, or the version string doesn't use `git describe --tags` to versionize the packages, so it displays as 0.7.0+somehugeoffset, instead of 0.7.3+slightlysmalleroffset.

E: Oh yeah, saw your other notice. See you tomorrow at the earliest, and enjoy your break!

**Comment by minextu** [comment]
The git packages are always pulled from master, so they don't need to get updated, just rebuild. 
As for the tags: new releases are tagged from the `zfs-0.7-release` branch.  `git describe --tags` only fetches the latest tag for the master branch, that's why you only get `0.7.0` as the newest tag.

**Comment by kode54** [comment]
Ah, I wasn't aware they didn't tag the point releases. Thanks for clearing that up.

**Comment by demizer** [comment]
After updating, I am seeing the following from spl:

```
[  718.352258] spl: Unknown symbol vfs_write (err 0)
[  718.352354] spl: Unknown symbol vfs_read (err 0)
[  774.150200] spl: Unknown symbol vfs_write (err 0)
[  774.150294] spl: Unknown symbol vfs_read (err 0)
[  820.401338] spl: Unknown symbol vfs_write (err 0)
[  820.401431] spl: Unknown symbol vfs_read (err 0)
[  984.157833] spl: Unknown symbol vfs_write (err 0)
[  984.157925] spl: Unknown symbol vfs_read (err 0)
[ 1505.395425] spl: Unknown symbol vfs_write (err 0)
[ 1505.395513] spl: Unknown symbol vfs_read (err 0)
[ 1530.882717] spl: Unknown symbol vfs_write (err 0)
[ 1530.882804] spl: Unknown symbol vfs_read (err 0)
[ 1561.647350] spl: Unknown symbol vfs_write (err 0)
[ 1561.647443] spl: Unknown symbol vfs_read (err 0)
```

**Comment by demizer** [comment]
Fixed in https://github.com/zfsonlinux/spl/issues/656
