### ISSUE TITLE
ZFS Module Fails to Load

### ISSUE THREAD

**Issue by demizer** [archzfs/archzfs#192]
After rebooting my machine, the zfs file system is not loaded. When I try to load the module manually, I am greeted with:

```
lithium% sudo modprobe zfs
modprobe: ERROR: could not insert 'zfs': Unknown symbol in module, or unknown parameter (see dmesg)
```

I am working to resolve the issue.

**Comment by demizer** [comment]
Appologies everyone. I should have ran tests, but I did not. @minextu has been working on a CI system, I will work on implementing this in AWS to prevent this happening in the future.

**Comment by minextu** [comment]
I thnik thats because of https://github.com/archzfs/archzfs/issues/191. You will probably need to patch spl using https://github.com/zfsonlinux/spl/commit/ed19bccfb651843fa208232b3a2d3d22a4152bc8

**Comment by minextu** [comment]
archzfs-ci does only build the packages for now. I'm working on it..

**Comment by gigamo** [comment]
Rebooting after updating to 4.14 to find my root filesystem (on ZFS) unusable was a bit of a surprise at least :) looks like I was a bit too quick. Unbroke it by downgrading the packages and kernel through live USB for now. 

Just wanted to say good luck and thanks for your work on this project!

**Comment by minextu** [comment]
https://github.com/archzfs/archzfs/pull/193 has a fix
