### ISSUE TITLE
Update version informaton for *-git packages

### ISSUE THREAD

**Issue by UweSauter** [archzfs/archzfs#198]
As of today (2017-12-08) all *-git packages in archzfs have wrong versioning information 0.7.0 while other packages reflect correct version as can be seen in the output below.

I'm not sure how to handle this case where version is a moving target (HEAD respectively the commit hash) but I believe that it should be updated to include the latest official release of ZFSonlinux, e.g. instead of `archzfs/spl-linux-git 0.7.0.r21.ged19bcc.4.14.3.1-4` it should be `archzfs/spl-linux-git 0.7.3.ged19bcc.4.14.3.1-4`.

```
# pacman -Ss zfs | grep ^arch
archzfs/spl-archiso-linux 0.7.2_4.13.3.1-1 (archzfs-archiso-linux)
archzfs/spl-linux 0.7.3.4.14.3.1-4 (archzfs-linux)
archzfs/spl-linux-git 0.7.0.r21.ged19bcc.4.14.3.1-4 (archzfs-linux-git)
archzfs/spl-linux-hardened 0.7.3_4.14.3.a.1-1 (archzfs-linux-hardened)
archzfs/spl-linux-hardened-git 0.7.0.r21.ged19bcc.4.14.3.a.1-1 (archzfs-linux-hardened-git)
archzfs/spl-linux-lts 0.7.3.4.9.66.1-2 (archzfs-linux-lts)
archzfs/spl-linux-lts-git 0.7.0.r21.ged19bcc.4.9.66.1-2 (archzfs-linux-lts-git)
archzfs/spl-linux-zen 0.7.3.4.14.3.1-3 (archzfs-linux-zen)
archzfs/spl-linux-zen-git 0.7.0.r21.ged19bcc.4.14.3.1-3 (archzfs-linux-zen-git)
archzfs/spl-utils-common 0.7.3-1 (archzfs-linux)
archzfs/spl-utils-common-git 0.7.0.r21.ged19bcc-2 (archzfs-linux-git)
archzfs/zfs-archiso-linux 0.7.2_4.13.3.1-1 (archzfs-archiso-linux)
archzfs/zfs-archiso-linux-headers 0.7.2_4.13.3.1-1
archzfs/zfs-linux 0.7.3.4.14.3.1-4 (archzfs-linux)
archzfs/zfs-linux-git 0.7.0.r200.gd4677269f.4.14.3.1-4 (archzfs-linux-git)
archzfs/zfs-linux-git-headers 0.7.0.r200.gd4677269f.4.14.3.1-4
archzfs/zfs-linux-hardened 0.7.3_4.14.3.a.1-1 (archzfs-linux-hardened)
archzfs/zfs-linux-hardened-git 0.7.0.r200.gd4677269f.4.14.3.a.1-1 (archzfs-linux-hardened-git)
archzfs/zfs-linux-hardened-git-headers 0.7.0.r200.gd4677269f.4.14.3.a.1-1
archzfs/zfs-linux-hardened-headers 0.7.3_4.14.3.a.1-1
archzfs/zfs-linux-headers 0.7.3.4.14.3.1-4
archzfs/zfs-linux-lts 0.7.3.4.9.66.1-2 (archzfs-linux-lts)
archzfs/zfs-linux-lts-git 0.7.0.r200.gd4677269f.4.9.66.1-2 (archzfs-linux-lts-git)
archzfs/zfs-linux-lts-git-headers 0.7.0.r200.gd4677269f.4.9.66.1-2
archzfs/zfs-linux-lts-headers 0.7.3.4.9.66.1-2
archzfs/zfs-linux-zen 0.7.3.4.14.3.1-3 (archzfs-linux-zen)
archzfs/zfs-linux-zen-git 0.7.0.r200.gd4677269f.4.14.3.1-3 (archzfs-linux-zen-git)
archzfs/zfs-linux-zen-git-headers 0.7.0.r200.gd4677269f.4.14.3.1-3
archzfs/zfs-linux-zen-headers 0.7.3.4.14.3.1-3
archzfs/zfs-utils-common 0.7.3-1 (archzfs-linux)
archzfs/zfs-utils-common-git 0.7.0.r200.gd4677269f-2 (archzfs-linux-git)
```

**Comment by minextu** [comment]
As I explained in https://github.com/archzfs/archzfs/issues/191, new releases in zfs get tagged using the `zfs-0.7-release` branch.

An easy workaround would be replacing `git describe --long` with `` git describe --long `git rev-list --tags --max-count=1` `` like in https://github.com/minextu/archzfs/commit/14f6d4666132787365ac4d34dfdf6ed12c0a7ef8 to use tags across all branches.

But this can cause problems in future releases, for example: if there's ever a `0.8rc1` and then after that a `0.7.5` gets tagged, the version would get decreased and you would need to force a downgrade in order to update.

Another solution would be to ignore tags and just use the revision string.

**Comment by UweSauter** [comment]
Thanks for the explanation. I then would suggest to include date in ISO format [1] and commit hash as version for *-git packages. Something like `archzfs/spl-linux-git 2017-12-08.ged19bcc.4.14.3.1-4` of, if dashes might cause problems `archzfs/spl-linux-git 2017.12.08.ged19bcc.4.14.3.1-4`.



[1] https://en.wikipedia.org/wiki/ISO_8601

**Comment by minextu** [comment]
Great idea, I opened a pull request (https://github.com/archzfs/archzfs/pull/200)
