### ISSUE TITLE
Update for Linux-4.14.4, Linux-LTS-4.9.67, Linux-Zen-4.14.4

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#199]

**Comment by jacksonatl** [comment]
What's the status on this, all supported kernels have been updated over a week ago now?

**Comment by demizer** [comment]
Appologies, I have been super busy with my private life to notify the community. I will get package updates sometime today. 

Also, @minextu has been working on deployment automation that will automatically deploy built packages when kernel versions are updated. We are working on documentation for this. I will test it and hopefully in the near future package deployments will no longer be a manual process! I am very excited and thankful to @minextu for making this happen!

**Comment by jacksonatl** [comment]
Awesome, thanks! Saw activity on other bugs & was worried there was a show stopper
