### ISSUE TITLE
Remove dkms PKGBUILDs

### ISSUE THREAD

**Issue by minextu** [archzfs/archzfs#205]
push.sh has added all dkms PKGBUILDs to the main archzfs repository. Possibly because dkms is not a submodule (and not in the aur).

We should either remove these commits from master, or push a new commit deleting those files.

**Comment by demizer** [comment]
Ah missed that. We should try to get maintenance of the linux-dkms packages in AUR so we can add as submodules.

**Comment by demizer** [comment]
I'll send AUR mods some requests

**Comment by minextu** [comment]
Hm, it seems like the current maintainer of zfs-dkms doesn't want to transfer ownership, so wouldn't it be a bit mean to just let a mod do that? The package isn't broken or anything.

**Comment by demizer** [comment]
Right. I meant try to get maintainership from the maintainer. In any case, we can just keep the sources in the archzfs repo until the maintainer wants to transfer ownership or add us on as contributors.

**Comment by minextu** [comment]
Yeah but the entire spl/zfs source tree was added along with it, since there's no .gitignore in there.

**Comment by demizer** [comment]
Awwww weak. I will fix that now.

**Comment by demizer** [comment]
Thanks @minextu for the issue!
