### ISSUE TITLE
zfs-mount at boot with 4.14.5-1-ARCH x86_64 seems to no longer work

### ISSUE THREAD

**Issue by risto3** [archzfs/archzfs#207]
just updated this morning getting the latest build of zfs and 4.14.5-1-ARCH
had a real scare because my logins no longer worked from lightdm.  In a tty
I logged into root and noticed that my home directory was empty... in fact,
all were...
so I zfs mounted my home filesystem and was able to login...
checked systemctl:
```
richard@sarchx64:/etc/zfs/zed.d$ systemctl status zfs-mount
● zfs-mount.service - Mount ZFS filesystems
   Loaded: loaded (/usr/lib/systemd/system/zfs-mount.service; enabled; vendor pr
   Active: active (exited) since Thu 2017-12-14 07:00:25 CET; 18min ago
  Process: 518 ExecStart=/usr/bin/zfs mount -a (code=exited, status=0/SUCCESS)
 Main PID: 518 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   CGroup: /system.slice/zfs-mount.service
```
it is still enabled and ran successfully.
so I simply issued: `sudo zfs mount -a` and the rest of the filesystems seemed to load fine.

tried rebooting to see if this was simply a oneshot, but the same situation repeated.

Is there something new or changed that I missed and need to configure?
Anybody else see issues of this sort?

**Comment by minextu** [comment]
Seems like https://github.com/archzfs/archzfs/issues/186 made it into the stable release

**Comment by minextu** [comment]
This issue is also described upstream (https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.4)

**Comment by risto3** [comment]
indeed, issuing `sudo systemctl enable zfs-import.target` restored reboot environment expectations.
Thanks for the quick reply (perhaps a heads-up on the wiki/forum is in order)

**Comment by hrast01** [comment]
I came across this last night, I should have opened up an issue with a solution in it.
