### ISSUE TITLE
Can't find pool/datasets and systemd services are missing after 4.14.6 update

### ISSUE THREAD

**Issue by gigamo** [archzfs/archzfs#214]
After updating to the 4.14.6 kernel along with the new archzfs packages, ZFS is unable to find my pool and its datasets. All ZFS-related systemd services also appear to be missing. `dmesg | grep ZFS` showed no errors of any kind, so the module does seem to be loaded.

Not sure what caused this, as I had to downgrade back to 4.14.5 to go back to a working system for now.

**Comment by demizer** [comment]
Yup. A new flag was added that we missed. New packages are being built now. Sorry about that. Next year we will have automated testing in place that will catch things like this.

**Comment by demizer** [comment]
Related to #213

**Comment by demizer** [comment]
I still don't see the systemd unit files in zfs-utils-common-git after a rebuild.

**Comment by minextu** [comment]
That's strange, it's working on my fork (https://arch.et.tc/archzfs-ci/x86_64/zfs-utils-common-0.7.4-2-x86_64.pkg.tar.xz)

**Comment by minextu** [comment]
by the way: you didn't need to rebuild every kernel package, just the common packages

**Comment by minextu** [comment]
I just compiled the aur version and even there  systemd files are being built, so seems like you maybe uploaded an older version to the repo? You could try bumping the common pkgrel once more and rebuild the common-git packages

**Comment by dmp1ce** [comment]
I just install `pkgrel=2` and I don't see `zfs.target` anywhere.

**Comment by dmp1ce** [comment]
I am using archzfs repo, not the AUR.

**Comment by minextu** [comment]
Yeah the repo does not have systemd files right now. You can install https://arch.et.tc/archzfs-ci/x86_64/zfs-utils-common-0.7.4-2-x86_64.pkg.tar.xz or build from the aur in the meantime

**Comment by dmp1ce** [comment]
Thanks @minextu . I installed that package manually for now. Do you know when the archzfs repo will be updated?

**Comment by minextu** [comment]
No sorry, only @demizer can do that

**Comment by demizer** [comment]
When I try to build, I am getting:

```configure: WARNING: unrecognized options: --with-systemd 
```
In the output. 

The common-git packages are using latest commit hash:

```
-source=("git+https://github.com/zfsonlinux/zfs.git#commit=bbffb59efc49baba1d131d497202e8cda0068c3d"
+source=("git+https://github.com/zfsonlinux/zfs.git#commit=a8b2e30685c9214ccfd0181977540e080340df4e"
```

I suspect something is happening with my local git repo. I am working to resolve this.

**Comment by demizer** [comment]
Related https://github.com/zfsonlinux/zfs/commit/ee410eefc2a9c0f0e77bd765894ee7767af647ea

**Comment by demizer** [comment]
Success!
```
demizer@lithium  ❯❯❯ pacman -Qlp packages/common-git/zfs-utils-common-git/zfs-utils-common-git-2017.12.21.r3220.a8b2e3068-1-x86_64.pkg.tar.xz| grep service
zfs-utils-common-git /usr/lib/systemd/system/zfs-import-cache.service
zfs-utils-common-git /usr/lib/systemd/system/zfs-import-scan.service
zfs-utils-common-git /usr/lib/systemd/system/zfs-mount.service
zfs-utils-common-git /usr/lib/systemd/system/zfs-share.service
zfs-utils-common-git /usr/lib/systemd/system/zfs-zed.service
```
Pushing out updates now!
