### ISSUE TITLE
Is a single zpool with datasets for root supported?

### ISSUE THREAD

**Issue by osmano807** [archzfs/archzfs#22]
Hello, I'm currently running Arch on a system with only a single zpool for `/`, but wanted to know if it is intended to use it with datasets for the various dirs on root. 
I know that Arch is not supported to run with different partitions for `/`, `/usr` and specially `/etc`, but I don't know if a different dataset fits in this rule.

After installing (with some grub-install problems), booting with a single zpool didn't work. I have the following zpool/dataset configuration:

```
 ~ ? sudo zfs list -o name,mountpoint
NAME               MOUNTPOINT
zroot              /
zroot/etc          /etc
zroot/home         /home
zroot/swap         -
zroot/usr          /usr
zroot/usr/include  /usr/include
zroot/var          /var
zroot/var/empty    /var/empty
zroot/var/log      /var/log
```

The problem is that on boot only the `zroot` would be mounted, not his datasets, like `zroot/usr`, and the kernel would complain that it couldn't find `/sbin/init`. To fix this, I made this modification to `/lib/initcpio/hooks/zfs`

```diff
--- zfs-utils.initcpio.hook	2014-04-10 11:03:06.060838876 -0300
+++ initcpio/zfs.hooks	2014-04-07 19:53:40.823981457 -0300
@@ -49,12 +49,20 @@ zfs_mount_handler () {
         fi
     fi
 
-    local mountpoint=$("/usr/bin/zfs" get -H -o value mountpoint $ZFS_DATASET)
-    if [ "$mountpoint" = "legacy" ] ; then
-        mount -t zfs -o ${rwopt_exp} "$ZFS_DATASET" "$node"
-    else
-        mount -o zfsutil,${rwopt_exp} -t zfs "$ZFS_DATASET" "$node"
-    fi
+    # My hack
+    # loop over all children datasets on $ZFS_DATASET
+
+    /usr/bin/zfs list -H -o name -t filesystem -r $ZFS_DATASET | while read -r ZFS_CHILDREN_DATASET ; do
+        local mountpoint=$("/usr/bin/zfs" get -H -o value mountpoint $ZFS_CHILDREN_DATASET)
+        if [ "$mountpoint" = "legacy" ] ; then
+            echo "ZFS: mounting legacy don't work with this hack: $ZFS_CHILDREN_DATASET"
+            #mount -t zfs -o ${rwopt_exp} "$ZFS_CHILDREN_DATASET" "$node"
+            return 1
+        else
+            mount -o zfsutil,${rwopt_exp} -t zfs "$ZFS_CHILDREN_DATASET" "$node/$mountpoint"
+        fi
+
+    done
 }
 
 run_hook() {
```

It's working for my setup, because my zfs dataset mountpoints reflect exactly the desired mountpoints on the running system, and I don't have any dataset with legacy mountpoint set.

**Comment by demizer** [comment]
https://github.com/archzfs/archzfs/tree/master/testing/tests/archzfs-qemu-lts-test-01-root-bootfs is a test I put together to test archzfs used as a root fs (with datasets) using syslinux as the bootloader. The test passes.
