### ISSUE TITLE
zed.rc replaced with default on upgrade of zfs-utils-common

### ISSUE THREAD

**Issue by nightah** [archzfs/archzfs#225]
It appears that anytime there is a update for the zfs-utils-common* packages the file `/etc/zfs/zed.d/zed.rc` is replaced with the default provided.

Could you please update the according zfs-utils-common* PKGBUILD's to include:
```
backup=('etc/zfs/zed.d/zed.rc')
```
As per the detail [here](https://wiki.archlinux.org/index.php/PKGBUILD#backup).

> **backup**
> An array of files that can contain user-made changes and should be preserved during upgrade or removal of a package, primarily intended for configuration files in /etc.
> 
> Files in this array should use relative paths without the leading slash (/) (e.g. etc/pacman.conf, instead of /etc/pacman.conf).
> 
> When updating, new versions may be saved as file.pacnew to avoid overwriting a file which already exists and was previously modified by the user. Similarly, when the package is removed, user-modified files will be preserved as file.pacsave unless the package was removed with the pacman -Rn command.

I would have submitted a PR for this, however, due to my lack of experience with submodules I can't seem to follow the existing submodules to see the said PKGBUILD's which require updating.

**Comment by minextu** [comment]
Thanks for the info. I submitted a pull request

**Comment by demizer** [comment]
Packages haven't been pushed out yet, working on that now. Thanks!

**Comment by demizer** [comment]
Rebuilt packages have been pushed! Thanks for reporting!
