### ISSUE TITLE
Update for linux 4.15.2-2, linux-lts 4.14.18-1 and linux-zen 4.15.2-2

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#227]

**Comment by storrgie** [comment]
@demizer did the packages get pushed? I just tried to install on a new instance and got: 

```
[root@tank ~]# pacman -S zfs-linux
resolving dependencies...
warning: cannot resolve "linux=4.15.2-2", a dependency of "spl-linux"
warning: cannot resolve "spl-linux", a dependency of "zfs-linux"
warning: cannot resolve "linux=4.15.2-2", a dependency of "zfs-linux"
:: The following package cannot be upgraded due to unresolvable dependencies:
      zfs-linux
```

**Comment by someone1** [comment]
@storrgie the linux package is now at 4.15.3-1 but zfs-linux is expecting 4.15.2-2, downgrade to the old kernel or wait for this package to be updated for the latest kernel

**Comment by storrgie** [comment]
@demizer would like like for users to make new issues when the kernel moves? (like this ticket)?
