### ISSUE TITLE
depmod cant finde modules during install

### ISSUE THREAD

**Issue by sircrimer** [archzfs/archzfs#248]
While updating to 
linux-lts-4.14.39-2
spl-linux-lts-0.7.8.4.14.39.1-1
zfs-linux-lts-0.7.8.4.14.39.1-1

>>> Updating SPL module dependencies
depmod: WARNING: could not open /lib/modules/4.14.39-1-lts/modules.order: No suc                                                                                                             h file or directory
depmod: WARNING: could not open /lib/modules/4.14.39-1-lts/modules.builtin: No s                                                                                                             uch file or directory
(4/4) upgrading zfs-linux-lts                      [######################] 100%
>>> Updating ZFS module dependencies
depmod: WARNING: could not open /lib/modules/4.14.39-1-lts/modules.order: No suc                                                                                                             h file or directory
depmod: WARNING: could not open /lib/modules/4.14.39-1-lts/modules.builtin: No s                                                                                                             uch file or directory

**Comment by demizer** [comment]
Fix should be pushed out now. Sorry about that.
