### ISSUE TITLE
Update Linux-LTS pkg to 4.14.51

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#257]

**Comment by hrast01** [comment]
Is there a better way to do this?  I don't want to create issues every time there's an LTS update because I don't know if someone is already working on them.

**Comment by demizer** [comment]
@hrast01 eventually updates will be automated, but I have been real busy with work and personal stuff as of late to get the infra set up for the automation.

**Comment by hrast01** [comment]
Appreciate the work you do, I just didn't want to be a pain in the ass.
