### ISSUE TITLE
Maintainer change

### ISSUE THREAD

**Issue by demizer** [archzfs/archzfs#262]
After six years of being primary maintainer, it's time for me to pass it onto the next. I no longer have time to dedicate to this project because of work and family obligations. @minextu has agreed to take over the handling and direction of the project. He is already a core contributor and has some great new additions in store for the future.

In the coming days, I will hand over the archzfs.com domain to @minextu and we will sign the packages with his signing key:

```
DDF7DB817396A49B2A2723F7403BD972F75D9D76 ArchZFS Bot <bot@archzfs.com>
```

Thanks!

**Comment by sonix07** [comment]
thank you for all the effort. I've been using this for years and my experience was flawless. thank you very much

**Comment by foafron** [comment]
Thank you for all of your hard work.  ZFS has performed wonderfully for me for multiple years on Arch.  Thanks so much!

**Comment by kmelva** [comment]
Thanks for the hard work!

**Comment by CRWdog193** [comment]
Have used/appreciated your work for a long time - can't thank you enough for your efforts. ZFS on Arch has always "Just Worked" - thank you!

**Comment by aaronlauterer** [comment]
Thanks a lot for your work!

**Comment by Thorsten2k3** [comment]
Thanks so much for your work! ZFS on Arch always just worked for me as well.

**Comment by minextu** [comment]
Thanks for your patience, the transition is now complete and all packages are up to date again (except for linux-vfio and archiso for now).

To update, you will need to add the new gpg key to pacman's trusted key list:
```
pacman-key -r F75D9D76
pacman-key --lsign-key F75D9D76
```
Don't forget to remove the temporary repository, if you've used it.

There's also a new testing repository, which gets automated daily updates using https://ci.archzfs.com
```
[archzfs-testing]
Server = http://archzfs.com/$repo/$arch
```
I'm manually testing those packages and push them to the main archzfs repository after that.

**Comment by kmelva** [comment]
Hi @minextu and thanks for doing this!

Is there any difference in functionality between [AUR/zfs-linux](https://aur.archlinux.org/packages/zfs-linux/) package and `zfs-linux` package in the archzfs repository? I've been using the AUR version so far, but I'd like to switch to prebuilt packages, if there are no (significant) differences.

**Comment by minextu** [comment]
All packages except for dkms are built using the same PKGBUILD's as in the aur. So there's no real difference when building it yourself.

**Comment by piotaixr** [comment]
@itoffshore @minextu 
Same problem here, fresh install:
```
[root@arch-install-vbox ~]# pacman-key -r F75D9D76
gpg: key 403BD972F75D9D76: public key "ArchZFS Bot <buildbot@archzfs.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
==> Updating trust database...
gpg: next trustdb check due at 2018-12-13
[root@arch-install-vbox ~]# pacman-key --lsign-key F75D9D76
  -> Locally signing key F75D9D76...
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: bad data signature from key 20E8A9C77716EB4F: Wrong key usage (0x19, 0x2)
gpg: depth: 0  valid:   1  signed:   6  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: bad data signature from key 20E8A9C77716EB4F: Wrong key usage (0x19, 0x2)
gpg: depth: 1  valid:   6  signed:  70  trust: 1-, 0q, 0n, 5m, 0f, 0u
gpg: depth: 2  valid:  70  signed:   8  trust: 70-, 0q, 0n, 0m, 0f, 0u
gpg: next trustdb check due at 2018-12-13
[root@arch-install-vbox ~]# pacman -syyu
error: invalid option '-s'
[root@arch-install-vbox ~]# pacman -Syyu
:: Synchronising package databases...
 core                                                       130.8 KiB   644K/s 00:00 [#################################################] 100%
 extra                                                     1652.3 KiB  4.52M/s 00:00 [#################################################] 100%
 community                                                    4.5 MiB  5.99M/s 00:01 [#################################################] 100%
 archzfs                                                     17.0 KiB   740K/s 00:00 [#################################################] 100%
 archzfs.sig                                                310.0   B  0.00B/s 00:00 [#################################################] 100%
:: Starting full system upgrade...
 there is nothing to do
[root@arch-install-vbox ~]# pacman -S zfs-linux
resolving dependencies...
looking for conflicting packages...

Packages (4) spl-linux-0.7.9.4.17.8.1-1  spl-utils-common-0.7.9-1  zfs-utils-common-0.7.9-1  zfs-linux-0.7.9.4.17.8.1-1

Total Download Size:    4.53 MiB
Total Installed Size:  12.34 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 spl-utils-common-0.7.9-1-x86_64                             16.0 KiB   696K/s 00:00 [#################################################] 100%
 spl-linux-0.7.9.4.17.8.1-1-x86_64                           96.7 KiB  1696K/s 00:00 [#################################################] 100%
 zfs-utils-common-0.7.9-1-x86_64                              3.7 MiB  8.77M/s 00:00 [#################################################] 100%
 zfs-linux-0.7.9.4.17.8.1-1-x86_64                          785.1 KiB  11.0M/s 00:00 [#################################################] 100%
(4/4) checking keys in keyring                                                       [#################################################] 100%
downloading required keys...
:: Import PGP key 2048R/B18A9C9F1E4EEAFF072DAB9E5E1ABF240EE7A126, "Jesus Alvarez <jeezusjr@gmail.com>", created: 2012-10-24? [Y/n] n
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```

**Comment by minextu** [comment]
spl/zfs-utils-common was last built by demizer, so it's still signed using his gpg key. I will bump the pkgrel later today to replace it with the new gpg key.

**Comment by minextu** [comment]
It should now work without demizer's key

**Comment by itoffshore** [comment]
@minextu - yes all ok

```
[stuart@manjaro ~]$ sudo pacman-key -d B18A9C9F1E4EEAFF072DAB9E5E1ABF240EE7A126
==> Updating trust database...
gpg: next trustdb check due at 2018-10-19
[stuart@manjaro ~]$ sudo pacman -Syu
:: Synchronising package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archzfs is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (2) zfs-dkms-git-2018.07.24.r4643.g473c976a0-1  zfs-utils-common-git-2018.07.24.r4643.g473c976a0-1

Total Download Size:    9.14 MiB
Total Installed Size:  42.75 MiB
Net Upgrade Size:       0.00 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 zfs-utils-common-git-2018.07.24.r4643.g473c976a0-...     4.1 MiB  2.29M/s 00:02 [##############################################] 100%
 zfs-dkms-git-2018.07.24.r4643.g473c976a0-1-x86_64        5.0 MiB  6.84M/s 00:01 [##############################################] 100%
```

**Comment by kuon** [comment]
I want to thank you for all the work. I have been using zfs under arch for a long time and it was a flawless experience. I wish you the best. I'm also happy @minextu is taking over and that the project will not be unmaintained.

Thanks you all.

**Comment by endreszabo** [comment]
Thank you all guys.

**Comment by dln11** [comment]
@demizer  Thanks for all the work and effort over the years. :-) I'm running a encrypted full zfs setup for several years now and as others already have pointed out it was a very good experience. I wish you all the best.
