### ISSUE TITLE
versions in repo too old?

### ISSUE THREAD

**Issue by btwe** [archzfs/archzfs#265]
Dear all,

Today my plan was to migrate from `aur/zfs-linux-git` to the archzfs repo. But I made the mistake to remove the `aur/zfs-linux-git` packages and upgrade the kernel to `4.17.13` _before_ verifying your repos provide with zfs packages matching the up to date kernel.

I see you guys have a buildbot (`ci.archzfs.com`), but there I can only find latest builds for `4.17.12`.
Is that correct or am I doing something wrong? Are you currently working on it? If yes, please also go for `4.17.14`, because `linux-4.17.13` was flagged outdated today.

Now I am in a situation where I cannot use my system. I chose to use the -git version because my $HOME is on a native encrypted zpool.

I think my options are:
- wait until archzfs is up to date with current kernel
- downgrade kernel to `4.17.12`
- revert back to /aur (which are also still on `4.17.12`)

Could you give me some feedback on how I may proceed?

I assume as soon archzfs is installed on my system, upgrading will only be done when both linux kernel and zfs packages can be upgraded. Is that right? I was always fighting to upgrad the aur packages, which is the biggest part of the reason why I like to change to your repos. Please let me know if I decided to do this too early.

Thanks a lot!

**Comment by minextu** [comment]
Packages are up to date again. 
You are right, the safest solution is to wait for archzfs to be updated, but some prefer to do partial upgrades (upgrade everything except for the kernel). Someone even created a repo for making this easier: https://end.re/archzfs-kernels

Another solution is to use the automated testing repository, where packages are updated daily at 3:00 UTC. These aren't tested though.
```
[archzfs-testing]
Server = http://archzfs.com/$repo/$arch
````

**Comment by btwe** [comment]
Thank you very much for the quick update and valuable information. Everything just works as expected again.
