### ISSUE TITLE
New version of zfs/spl *before* kernel is released?

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#266]
Did the new automated build system get the new builds ready *before* the new kernel actually made it to repos? :)

```
warning: cannot resolve "linux=4.17.13.arch1-1", a dependency of "spl-linux"
warning: cannot resolve "linux=4.17.13.arch1-1", a dependency of "zfs-linux"
```

**Comment by minextu** [comment]
Your mirror was probably out of sync / not fast enough :D

**Comment by fryfrog** [comment]
Really out of sync / slow, it was still missing this morning. Should have fixed mirrors before creating issue, sorry! :)

¯\_(ツ)_/¯
