### ISSUE TITLE
zfs-dkms conflicts with all other packaged modules packages, should it not be the other way around?

### ISSUE THREAD

**Issue by AdamSLevy** [archzfs/archzfs#269]
I recently used the scripts in this repo to build a modules package for an ec2-lts kernel. Previously I had been using zfs-dkms from your repos. To my surprise when I went to install my module package, I discovered it did not cause a conflict with zfs-dkms like I expected it to. I dug into the `conflicts` array in the generated PKGBUILDs and was surprised to find that the modules packages only declare the corresponding `-git` versions of the packages as conflicts. (i.e. zfs-linux declares zfs-linux-git as a conflict). I then discovered that the `zfs-dkms` package declares all of the other modules packages as conflicts. 

This seems like the wrong direction to declare the conflict. Shouldn't all of the modules packages just declare the zfs-dkms package in its conflicts array instead of having to list all possible modules packages in the zfs-dkms package's conflicts array?

**Comment by minextu** [comment]
Yeah you're right, it should be the other way around. I changed the way conflicts work in bf51917a62e3d3c5b515f5926c464de973615855 (only on my fork of archzfs for now). This also utilizes the `provides` variable, so we don't need to generate a huge list of all header packages anymore. I will push it to archzfs.com after I did some testing.

Thanks for the suggestion!
