### ISSUE TITLE
Support for 4.18.9.arch1-1

### ISSUE THREAD

**Issue by koraa** [archzfs/archzfs#270]
HI,
zfs-0.7.11 (https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.11) has been released which should have support for 4.18 :)

**Comment by minextu** [comment]
I updated to zfs 0.7.11 nine days ago. Which packages are you talking about? :smile:

**Comment by koraa** [comment]
Hi minextu,
thanks for updating the packages!

Weirdly, I am still getting this trying to upgrade:

```
warning: cannot resolve "linux=4.17.2-1", a dependency of "spl-linux"                                       
warning: cannot resolve "linux=4.17.2-1", a dependency of "zfs-linux"                                       
```

**Comment by koraa** [comment]
oO seems I had the demizerone.com mirror in my config for some reason
