### ISSUE TITLE
Confusing and useless zfs-utils-common, spl-utils-common packages

### ISSUE THREAD

**Issue by eli-schwartz** [archzfs/archzfs#273]
As far as I can tell, these were created solely because the existing zfs-utils and spl-utils packages were split packages that caused people to build the dkms packages (although installation was not forced).

There's no reason they should exist, to be honest, and since taking over the dkms packages I have split out zfs-utils into a separate PKGBUILD. So all the existing zfs packages should start using a unified package name that everyone can agree upon...

Side note: spl-utils is useless and only contains testsuite binaries, there's zero reason to force people to install it IMO. But if you really want it, please rename spl-utils-common to spl-utils, because there is nothing "-common" about just-a-dependency.

Also: https://lists.archlinux.org/pipermail/aur-requests/2018-November/027729.html

**Comment by minextu** [comment]
The reason behind the common packages was exactly like you said: zfs-utils did already exist and wasn't a split package. Another reason is that we don't have control over the utils package and because of that, our version in the repo is never the same package as the one in the aur. if we change the init hook or update /  patch zfs, zfs-utils might still be outdated for aur users and they wouldn't be able to update easily or have a different experience than repo users.

I think the best solution to this would be, to hook up the zfs-dkms and zfs-utils package to our buildsystem to update everything at once and have one codebase for all zfs packages.

Another option would be to have archzfs your zfs-dkms aur package completely separated. To avoid confusion, we could rename the zfs-utils-common package to something like zfs-utils-archzfs.

What do you think?

**Comment by eli-schwartz** [comment]
> The reason behind the common packages was exactly like you said: zfs-utils did already exist and wasn't a split package.

Technically speaking, this isn't really a good reason for creating a duplicate. The package can still be built and installed either way.

> Another reason is that we don't have control over the utils package and because of that, our version in the repo is never the same package as the one in the aur. if we change the init hook or update / patch zfs, zfs-utils might still be outdated for aur users and they wouldn't be able to update easily or have a different experience than repo users.

This is also not a reason. There are many packages in all of Arch Linux, which depend on each other despite being maintained by different people. If one package doesn't get "patched", then the appropriate response is usually not to fork the package, but rather, to discuss with the maintainer of the package why it should be patched.

Anyways I do not understand how this would prevent users from updating. If the package is simply not getting updated, sure... but you can use versioned depends for this, and cause the update to be held until the dependency is updated. This would maybe encourage unresponsive maintainers to be responsive, encourage users to be responsive about flagging packages out of date or submitting orphan requests, and in general encourage everyone to work together, which is purportedly a goal of the AUR.

That being said, I'm pretty well active and don't anticipate lagging in this package, sooooo... shouldn't be a problem in future.

> I think the best solution to this would be, to hook up the zfs-dkms and zfs-utils package to our buildsystem to update everything at once and have one codebase for all zfs packages.

I'm intimidated by meta-build systems which, to me, obscure the actual resources being used, introduce heavily layered assumptions, and make it difficult to figure out where to update what is, in the end, actually a very simple build recipe.

> Another option would be to have archzfs your zfs-dkms aur package completely separated. To avoid confusion, we could rename the zfs-utils-common package to something like zfs-utils-archzfs.

That would reduce confusion, but it would not reduce duplication, which I think to be a valid additional concern.

...

Let's consider the case where zfs-utils is not being updated because the maintainer is slow. Assuming the zfs-linux package is updated and requires in turn an updated zfs-utils, the pinned dependency would result in the package simply being uninstallable from the AUR, period.

The result would be that users of the AUR get told "please ask the zfs-utils maintainer to provide an update, alternatively you can use the PKGBUILD from the github repo at XXXXX, or use our prebuilt repository". This doesn't seem very ideal, but it would put the responsibility where it belonged. I'd actually opt, instead, for providing updates in the custom repo but not deploying that to the AUR -- then telling users via a pinned comment that the update is waiting for a dependency to be updated, "please consider using our custom repo in the meantime". :D

**Comment by eli-schwartz** [comment]
Regarding things which you want to change in the zfs-utils package and the maintainer does not want to change, what happens when the reverse situation occurs?

For example, if you look at the current zfs-utils package, it installs the upstream bash-completion instead of a forked and bundled one. I looked at the upstream sources and noticed they provide one, and eagerly seized the opportunity to simplify and stop doing something which IMO is not the job of downstream packagers (to provide their own bash completions).

I've also removed several useless binaries from the initcpio: https://aur.archlinux.org/cgit/aur.git/commit/?h=zfs-utils&id=76f9e08e617727d3fdd44070575d938f6b76b7ce
Some of which your initcpio install hook did not add, some of which it still does add.

**Comment by minextu** [comment]
Wouldn't the easiest solution for this be to rename / merge zfs-utils-common into zfs-utils and let archzfs generate + push new PKGBUILD's to the aur. Then we would only have one utils package and zfs-dkms can depend on this one.

I really don't like the idea of removing the utils package out of the archzfs buildscripts (or having a different version in the repo). For me the entire point of this project is to have all zfs package sources at one place and be able to test them together. If someone would change the zfs hook and open a pull request, only the repo users will actually get this change. You would need to make the same changes for the aur utils packages, when the entire process could be completely automated. The same applies for the reverse of course.

So if you want to continue to maintain zfs-utils by yourself, I still think, while not optimal, having a zfs-utils-archzfs would be the best option.

**Comment by minextu** [comment]
I had some time to think about this and I will go ahead and point all archzfs packages to zfs-utils instead of pushing a custom utils package to the aur again. Thanks for bringing this up.

**Comment by JonyEpsilon** [comment]
I'm not sure I understand all the details here, so please forgive any imprecision ...

I think that currently the AUR zfs-utils and zfs-linux packages have been out of sync since 2021-08-29, preventing people using this combination from upgrading. Having looked over the issues on this repo, and tried to understand the background, it feels like this conversation is relevant to this. I wonder if any of the discussion in this thread is worthy of revisiting?

**Comment by JonyEpsilon** [comment]
P.s. happy to make a new issue for this if it would be more productive.
