### ISSUE TITLE
spl-utils has extraneous comma

### ISSUE THREAD

**Issue by enckse** [archzfs/archzfs#274]
The spl-utils PKGBUILD in the AUR has a comma in the `replaces` array:
```
replaces=("spl-utils-linux", "spl-utils-linux-lts" "spl-utils-common")
```

Which causes the [AUR page](https://aur.archlinux.org/packages/spl-utils/) to show this:
```
 spl-utils-common, spl-utils-linux,, spl-utils-linux-lts 
```

**Comment by minextu** [comment]
Good catch, will be fixed soon
