### ISSUE TITLE
root on ZFS: who/what is responsible for unmounting/exporting on system shutdown?

### ISSUE THREAD

**Issue by rsyring** [archzfs/archzfs#281]
I recently built a system that has a ZFS data set as root mounted on a LUKs encrypted device for whole-disk encryption:

ssd partition 5 --> LUKs --> ZFS

I am using the `zfs=bootfs` kernel option so utils initcpio hook loads my pool and mounts my datasets.  mkinitcpio is setup to run the encrypt hook before ZFS:

```
HOOKS=(base udev autodetect modconf block keyboard encrypt zfs filesystems fsck shutdown)
```
I deliberately do not use legacy mount points for the root FS since the initcpio hook is able to get all my zfs datasets mounted correctly.

This is all working fine and my system boots as expected.  However, on shutdown, I see some errors right before the system powers off:

![image](https://user-images.githubusercontent.com/109467/50469830-39b0e600-097c-11e9-9cbd-1e5206dd5e8d.png)

After some trial and error, I have found that the error message is being generated by the [initcpio shutdown script](https://github.com/falconindy/mkinitcpio/blob/a3cb799a8f63186b843db6a57da12d74a9320686/shutdown#L94) when it tries close my dmcrypt device.

The problem is that the shutdown script assumes all file systems will be unmounted when it calls umount.  But the ZFS datasets won't be unmounted that way.  And, even if they were, the zpool would still be active and would prevent the dmcrypt device from being able to be closed.

I was able to hack the shutdown script and manually unmount/export before the final attempt to close the dmcrypt device, which stopped the error messages:

```diff
printf '%s\n' "Disassembling stacked devices."

+zfs umount -a
+zpool export -a

# iterate over devices with holders
for part in */holders/*; do
    printf '%s\n' "part: $part"
    [ -e "$part" ] && disassemble "${part%%/*}"
done
```
So, I guess the problem could be with the shutdown script, in which case I need to file a bug with mkinitcpio.  But, it got me wondering, who/what is responsible for correctly unmounting zfs datasets and ultimately exporting all zpools on shutdown?

FWIW, ZoL has [an example](https://github.com/zfsonlinux/zfs/blob/master/contrib/dracut/README.dracut.markdown#export-zfssh) of doing this for Dracut.  They also had some discussion about this topic at: https://github.com/zfsonlinux/zfs/issues/5228

Thanks in advance for any help you can provide.

**Comment by zeph** [comment]
@rsyring got any follow up on this? I got a pretty noisy JBOD that I want to be able to switch off safely when not needed... I did the unmount but all drives are still shown ONLINE in the zpool

root@roger:~# zpool status
  pool: morituri
 state: ONLINE
  scan: scrub repaired 0B in 6h53m with 0 errors on Wed Mar  6 19:56:34 2019
config:

	NAME                                 STATE     READ WRITE CKSUM
	morituri                             ONLINE       0     0     0
	  raidz1-0                           ONLINE       0     0     0
	    ata-MAXTOR_STM3320820A_9QF6JNGH  ONLINE       0     0     0
	    ata-MAXTOR_STM3320820A_9QF6JMRK  ONLINE       0     0     0
	    sdi1                             ONLINE       0     0     0
	    sdj1                             ONLINE       0     0     0

errors: No known data errors

**Comment by stevleibelt** [comment]
Shouldn't this be closed, because it is old/possible outdated?

**Comment by ElvishJerricco** [comment]
@stevleibelt Is it? I don't see reference to any sort of fix here in the issue.

**Comment by rsyring** [comment]
@stevleibelt I appreciate you asking.  I've since moved to Ubuntu and using native ZFS encryption so I couldn't tell you.

**Comment by stevleibelt** [comment]
@rsyring you are welcome and thank you for your feedback.

Indeed, neither I can tell if this error exist because of the same reason you've mentioned. Moving to native zfs encryption is simple to easy.

Enjoy your zfs pools and have an awesome week.
