### ISSUE TITLE
Python missing from makedepends=(...)

### ISSUE THREAD

**Issue by drbawb** [archzfs/archzfs#283]
I'm experimenting with a setup to build the `zfs-utils-rc` and `zfs-linux-rc` packages for my systems w/ modified kernels inside a chroot [as described on the Arch wiki.](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot)

In doing so, if I create a clean `chroot` with nothing but the `base-devel` package group and the target Linux kernels, I've found that the configure step, for both the utils & module, fails with the following rather non-descript error:

```
...
checking whether host toolchain supports AES... yes
checking whether host toolchain supports PCLMULQDQ... yes
checking for target asm dir... asm-x86_64
configure: error: Cannot find  in your system path
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/drbawb/tmp/chroot/drbawb/build
```

To debug I compared this snippet to corresponding output from a successful compilation on another host:

```
...
checking whether host toolchain supports AES... yes
checking whether host toolchain supports PCLMULQDQ... yes
checking for target asm dir... asm-x86_64
checking whether python3 version is >= 2.6... yes
checking for python3 version... 3.7
checking for python3 platform... linux
checking for python3 script directory... ${prefix}/lib/python3.7/site-packages
checking for python3 extension module directory... ${exec_prefix}/lib/python3.7/site-packages
checking for python3.7... /usr/bin/python3.7
checking for a version of Python >= '2.1.0'... yes
checking for a version of Python >= '3.4.0'... yes
checking for the distutils Python package... yes
checking for Python include path... -I/usr/include/python3.7m
checking for Python library path... -L/usr/lib -lpython3.7m
checking for Python site-packages path... /usr/lib/python3.7/site-packages
checking python extra libraries... -lpthread -ldl  -lutil -lm
checking python extra linking flags... -Xlinker -export-dynamic
checking consistency of all components of python development environment... yes
checking for python3.7 module: setuptools... yes
checking for python3.7 module: cffi... no
checking whether to enable pyzfs: ... no
...
```

So the configure step appears to fail around the part where it checks the `python` environment. (Apparently it does this even if this `pyzfs` is not being built.) So if I go ahead and add `python` to `makedepends=(...)` in the PKGBUILDs then everything builds as expected, so it would appear that this build-time dependency is missing, at the very least, from the `zfs-linux-rc` and `zfs-utils-rc` packages. (Also I feel it'd be nice if the error was a little more descriptive than `can't find <blank> in system path`, but admittedly I know very little about autotools, or how it reports errors.)

Is this something that could be fixed here so that the ZFS packages build cleanly on a minimal installation/chroot of Arch?

**Comment by minextu** [comment]
Yep, had the same issue yesterday and fixed it in https://github.com/archzfs/archzfs/commit/43da9951ee38a4fef506d06036676734ee302cfd. I just forgot to push it.

**Comment by mdPlusPlus** [comment]
Can anyone confirm this is actually fixed? I'm running into the same problem when trying to build `0.8.0-rc5` under Debian 9.9.

Commands to reproduce:
1. `wget https://github.com/zfsonlinux/zfs/releases/download/zfs-0.8.0-rc5/zfs-0.8.0-rc5.tar.gz`
2. `tar xvf zfs-0.8.0-rc5.tar.gz`
3. `cd zfs-0.8.0`
4. `sh autogen.sh`
5. `./configure`
