### ISSUE TITLE
Compatibility of 0.7.12 with kernels > 4.19

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#286]
I've been actually noticed any problems, and I've been running on 4.20.x with zfs-linux for a while, but I did notice apparently the [0.7.12 release](https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.7.12) is only compatible with kernels up to 4.19. It was mentioned [on the mailing list](http://list.zfsonlinux.org/pipermail/zfs-discuss/2019-January/033431.html) that users were having trouble building with dkms, how did you end up building the latest kernels? Is there an issue with running the latest kernel that you are aware of?

**Comment by minextu** [comment]
I've applied this patch: https://github.com/zfsonlinux/zfs/pull/8227/files. It's already part of spl (https://github.com/zfsonlinux/spl/commit/cd1b28e0cfa923db988611df28958f7b84b53530) and only changes the `zpios` module, which is used for testing. So there shouldn't be any side effects.

**Comment by johnramsden** [comment]
Awesome, thanks!
