### ISSUE TITLE
No builds since February 9th?

### ISSUE THREAD

**Issue by haraldkoch** [archzfs/archzfs#287]
It appears that no archzfs builds have happened since February 9th, and there have been several kernel releases since then. I thought there was an automated build in place these days - is it not working?

**Comment by minextu** [comment]
New builds have been pushed. Sorry about that, didn't have too much time this week. 
Unfortunately testing is still done manually and haven't gotten around to automated that yet.
You can use the fully automated testing repository instead if you want.
```
[archzfs-testing]
Server = http://archzfs.com/$repo/x86_64
```

**Comment by haraldkoch** [comment]
Ah. My misunderstanding then - my apologies. And thanks for doing the update!!
