### ISSUE TITLE
Lagging behind the distro kernel lately?

### ISSUE THREAD

**Issue by spheenik** [archzfs/archzfs#288]
This is not really a bug, but rather a question. Not sure where to ask otherwise, so I'll just go ahead here...

It seems to me the zfs packages are lagging behind the distro kernel. IIRC, you guys created some automated build infrastructure to remedy this. Was it reverted to a manual process? 

I do not see any issues about this, so I am probably the only one to ask...

**Comment by bglod** [comment]
There was a recent issue on a similar topic. Does #287 answer your question?

**Comment by spheenik** [comment]
Pretty much, thank you. Quick follow up: What are the implications of adding the archfs-testing repository? Is it safe to go with the route "if it builds, it should work", or should I wait for the manual testing step?

**Comment by minextu** [comment]
To be honest I haven't catched any issues so far when testing. What could happen is something like changed systemd files, which might break auto mounting. But that mostly applies to the git packages since stable version mostly don't change that much between versions.

**Comment by spheenik** [comment]
Thanks for the elaboration. I think I feel adventurous, and will switch to the testing repo :+1:
