### ISSUE TITLE
ZFS-linux out of sync with 5.1.15-arch1-1-ARCH

### ISSUE THREAD

**Issue by jbhanks** [archzfs/archzfs#294]
I was trying to build an archiso with zfs-linux last night and I got the following error:
`error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'linux=5.1.14.arch1-1' required by zfs-linux
`
I assume this is because there was a minor kernel update and the zfs-linux package has not been updated yet.

**Comment by minextu** [comment]
Updated, sorry for the delay.

**Comment by jbhanks** [comment]
Thank you! Under 24 hours isn't bad at all :)
