### ISSUE TITLE
internal error: Invalid exchange

### ISSUE THREAD

**Issue by bazzawill** [archzfs/archzfs#297]
My system was hanging on importing ZFS pools after a reboot
I have got it up without my pools mounted but I am getting the following error

sudo zpool import -d /dev/disk/by-id mythfs
internal error: Invalid exchange

I have tried 
sudo zpool import -Fn -d /dev/disk/by-id mythfs 
sudo zpool import -FXn -d /dev/disk/by-id mythfs 

both complete without any output but my pool will still not mount

**Comment by stevleibelt** [comment]
Shouldn't this be closed, because it is old/possible outdated?

**Comment by minextu** [comment]
Please reopen, if this is still an issue
