### ISSUE TITLE
High hdd activity on idle?

### ISSUE THREAD

**Issue by JonAnder83** [archzfs/archzfs#298]
One thing I noticed is that even on idle activity, my three HDD drives forming a raid5 are always active: Every second they move and stop (can hear the needles moving)
I use this pool for storage pourposes on a local machine and no one is accessing from anywhere else.
Is this behavious normal for zfs? Is there anything I can tweak?

**Comment by fryfrog** [comment]
I'm just some guy, but this doesn't seem like a great place to ask this question. This repository is for the *packages* for ZFS on Arch Linux. While I'm sure many are familiar w/ ZFS, it still probably isn't the right place.

Maybe start w/ #zfsonlinux on irc.freenode.net?
