### ISSUE TITLE
on 0.8.1_5.2.8.arch1.1-1 arc_prune eats all cpu cycles if `zfs.zfs_arc_max` kernel parameter is set

### ISSUE THREAD

**Issue by emacsomancer** [archzfs/archzfs#299]
After updating to `zfs-0.8.1_5.2.8.arch1.1-1` and rebooting, [arc_prune] processes kept respawning and eating up all available cpu. The same behaviour obtained on both the regular arch kernel and the lts kernel. I had `zfs.zfs_arc_max=2147483648` included as a kernel parameter. Removing this kernel parameter and rebooting resolved the [arc_prune] cpu-eating issue, but of course means I have to run with ZFS's default arc size.

**Comment by stevleibelt** [comment]
Shouldn't this be closed, because it is old/possible outdated?

**Comment by minextu** [comment]
Please reopen, if this is still an issue
