### ISSUE TITLE
zfs-dkms fails on 5.3

### ISSUE THREAD

**Issue by Whoops** [archzfs/archzfs#301]
Looks like Arch just got the 5.3 kernel. My DKMS build failed, which looks to be due to [this upstream issue](https://github.com/zfsonlinux/zfs/issues/9332). There isn't an official release with a fix yet, but the issue said they had working 5.3 patches.

**Comment by minextu** [comment]
I just added the relevant patches for linux 5.3 to archzfs, thanks for reporting!
