### ISSUE TITLE
Use your initcpio stuff to improve aur/zfs-dkms?

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#304]
Hey @oowi and @minextu,

Just tonight I tried to switch to the aur/zfs-dkms, but discovered that it doesn't seem to wait for the module / pools to load before bailing at boot on a zfs root pool. After switching back to archzfs/zfs-dkms, everything is fine and I started poking around a bit w/ @eli-schwartz and it looks like your hook is a bit more robust.

Do you have any objection to me using yours to improve the aur version? And by using, I mean mostly copying it!

Looks like this is the commit that probably would "fix" it: https://github.com/archzfs/archzfs/commit/d61d37d3b65b70b28f384e3dae1dcbf5ab963c23

**Comment by oowi** [comment]
>>>>> "dw" == Donald Webster <notifications@github.com> writes:

    dw> Do you have any objection to me using yours to improve the aur
    dw> version? And by using, I mean mostly copying it!

no objection

    dw> Looks like this is the commit that probably would "fix" it:
    dw> https://github.com/archzfs/archzfs/commit/d61d37d3b65b70b28f384e3dae1dcbf5ab963c23

I don't remember anything in particular about it that I would not
expect to generalize.

**Comment by minextu** [comment]
Sure go ahead, would be great if all archlinux zfs packages would use the same hook.

**Comment by fryfrog** [comment]
Thanks a bunch, I'm closing this but may ask follow up questions later. :)
