### ISSUE TITLE
Re-apply SIMD patches?

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#305]
The SIMD fixes were removed at the last minute, it looks like due to issues on *older* kernels. Would it be crazy to bring back the patch set you guys had for 0.8.1?

https://github.com/zfsonlinux/zfs/issues/9346

**Comment by fryfrog** [comment]
From my `/proc/spl/kstat/zfs/vdev_raidz_bench`, speeds are very low. I wish I'd saved a version from when I was running a patched 5.2.x kernel. :/

https://paste.ubuntu.com/p/xC23XFDTsq/

**Comment by minextu** [comment]
I'm watching the issue and sounds like they are working on a fix, so I won't apply it for now (linux-lts would probably cause issues too)

**Comment by fryfrog** [comment]
Ah, true. I forgot there are other kernels.

**Comment by rajil** [comment]
Do we need to remove the manually applied simd patch with zfs 0.8.3?

**Comment by fryfrog** [comment]
They never got applied.
