### ISSUE TITLE
Testing repository out of date

### ISSUE THREAD

**Issue by lrustand** [archzfs/archzfs#307]
Currently the testing repository is out of date. The current linux version on arch is 5.3.4, but the archzfs-testing repository is only at 5.3.1, this is the same as the main archzfs repo. Seems like the "automatically builds against the latest kernel" is kind of not working.

**Comment by SchrodingerZhu** [comment]
Not solved till now.

Seems that the last sync in CI did not update anything.

**Comment by minextu** [comment]
Testing get's updated every 24 hours. I should probably increase the interval though.

**Comment by SchrodingerZhu** [comment]
@minextu stuck at 5.3.5 (to 5.3.6) for almost 72 hrs.

**Comment by lrustand** [comment]
I don't use the testing repository. The archzfs-testing repository is up to
date for me now. It was however stuck on 5.3.1 for several days while arch
kernel from core repository was ahead of that.

Seems as it is working now for me at least.

**Comment by lrustand** [comment]
Oops. Testing was actually enabled on that machine. That must be it then.
Sorry, my mistake
