### ISSUE TITLE
spl.spl_hostid does not set the hostid

### ISSUE THREAD

**Issue by Perseid** [archzfs/archzfs#31]
Hi,

(at least) since the 3.18.4-1 kernel update (zfs-git 0.6.3_r170_gd958324f_3.18.4_1-1) the spl.spl_hostid kernel option does not work to set the hostid. A constant hostid is valuable for root partitions, as they cannot be properly exported during shutdown (and booting will fail if the hostid has changed since last import if the import is not forced via the zfs_force=1 kernel option).

I was under the impression that it did work on the previous kernel, as I had no problems on all boots since my Arch installation two weeks ago, but maybe the hostid is less volatile than I thought. Also the [Installing Arch Linux on ZFS](https://wiki.archlinux.org/index.php/Installing_Arch_Linux_on_ZFS#After_the_first_boot) wiki page describes setting the kernel parameter as a valid alternative to creating a /etc/hostid file.

Best regards.

**Comment by demizer** [comment]
archzfs no longer does anything with hostid.
