### ISSUE TITLE
Add some warning to archlinux testing branch

### ISSUE THREAD

**Issue by SchrodingerZhu** [archzfs/archzfs#313]
There is no archzfs repo following the testing branch. I think we should add some specific warning to this.

Recently I ran into a trouble since arch testing repo did something like (5.3.7-1 -> 5.3.7-2 immediately -> 5.3.8). The version of the kernel jumped too fast in testing repo so that I missed the 5.3.7-2. Without any manual operation, I stuck at  `5.3.7-1` which is buggy on my laptop. After waiting for a while, I do some manual upgrade of kernel using the archive which resulted in an absence of nvidia driver. Then I noticed that nvidia driver's modules are hardcoded when packaging. So I had to again downgrade the nvidia package.

This is only an example of mine. I understand that it is quite common to have such issues. Therefore, I think we had better add some notice on it.

BTW, is it possible for me to migrate to DKMS from static modules? Any guide on this?

**Comment by fryfrog** [comment]
You should be able to just remove `archzfs/zfs-linux` and then install `archzfs/zfs-dkms`. Your issue could happen to anyone, I'm not sure what you think archzfs could do to mitigate it. You either run the kernel the package is built for or you don't.
