### ISSUE TITLE
archzfs.com is down

### ISSUE THREAD

**Issue by mnd999** [archzfs/archzfs#321]
Archzfs.com seems to be down. It should either be restored or the mirror documentation updated.

**Comment by fryfrog** [comment]
The mirrors from #308 work, thankfully.

**Comment by minextu** [comment]
It's back online, sorry about that. There is a memory leak on that webserver if the uptime get's too high. I need to investigate that, so it doesn't happen again.

**Comment by fryfrog** [comment]
Time for a reload/restart timer every day! ;)
