### ISSUE TITLE
Problem with zfs-linux-git?

### ISSUE THREAD

**Issue by hafniumdk** [archzfs/archzfs#329]
Doing `pacman -S zfs-linux-git` get me this (trying to move from release to master). Wonder what the problem is...

```
resolving dependencies...
warning: cannot resolve "zfs-utils-git=2020.01.31.r5690.g591505dc2", a dependency of "zfs-linux-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      zfs-linux-git

:: Do you want to skip the above package for this upgrade? [y/N] n
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'zfs-utils-git=2020.01.31.r5690.g591505dc2' required by zfs-linux-git
```

**Comment by lnicola** [comment]
See #328. It's a bad time to upgrade anything.

**Comment by hafniumdk** [comment]
> See #328. It's a bad time to upgrade anything or even reboot.

Seems in general to be a hard time for ZoL vs the Linux kernel (SIMD issues and now this). And the ZoL releases are not very frequent, so the issues are left lingering for months (if not more).
