### ISSUE TITLE
archzfs-kernels repo SSL cert is expired

### ISSUE THREAD

**Issue by zhimsel** [archzfs/archzfs#330]
Hey guys,

Looks like the SSL cert for `end.re` is expired as of today: 

```
archzfs is up to date
error: failed retrieving file 'archzfs-kernels.db' from end.re : SSL certificate problem: certificate has expired
error: failed to update archzfs-kernels (download library error)
```

**Comment by minextu** [comment]
Just tagging @endreszabo for this

**Comment by endreszabo** [comment]
Thx guys for looping me in. I was aware of the cert has expired but wanted to finally go the Ansible way with renewing it.

Renewing is successful, deploying is not yet. So I deployed it manually.

Sorry for the inconvenience this may have caused.

**Comment by zhimsel** [comment]
No worries, thanks for the quick turnaround!

**Comment by endreszabo** [comment]
Aaand now the VPS provider went down.
