### ISSUE TITLE
archzfs.com webserver is down.

### ISSUE THREAD

**Issue by jstenback** [archzfs/archzfs#335]
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
error: failed retrieving file 'archzfs.db' from archzfs.com : Failed to connect to archzfs.com port 80: Connection refused
error: failed to update archzfs (download library error)
error: failed to synchronize all databases

**Comment by minextu** [comment]
And it's backup now, thx for reporting!

**Comment by mcilloni** [comment]
It looks like it's down again:

`error: failed retrieving file 'archzfs.db' from archzfs.com : Failed to connect to archzfs.com port 80: Connection refused`

**Comment by danielclough** [comment]
Seems to be down again.

```sh
archzfs.db failed to download
error: failed retrieving file 'archzfs.db' from archzfs.com : The requested URL returned error: 404
error: failed retrieving file 'archzfs.db' from mirror.sum7.eu : The requested URL returned error: 404
error: failed retrieving file 'archzfs.db' from mirror.biocrafting.net : The requested URL returned error: 404
error: failed retrieving file 'archzfs.db' from mirror.in.themindsmaze.com : The requested URL returned error: 404
error: failed retrieving file 'archzfs.db' from zxcvfdsa.com : The requested URL returned error: 404
error: failed to synchronize all databases (failed to retrieve some files)
```

**Comment by stevleibelt** [comment]
Working fine on my machines (Germany)
