### ISSUE TITLE
ZEDLET script for zfs-mount-generator is located in directory with hardcoded zfs version number

### ISSUE THREAD

**Issue by mogwa1** [archzfs/archzfs#338]
While converting an existing archlinux ZFS system to use the "new" zfs-mount-generator, I noticed that the ZEDLET script that is supposed to be linked into the `/etc/zfs/zed.d` directory is located in a directory which includes the ZFS version number, namely `/usr/lib/zfs-0.8.3/zfs/zed.d/history_event-zfs-list-cacher.sh`.
This link has to be created manually, in contrast to the default ZEDLET links in `/etc/zfs/zed.d` which are maintained by the zfs package.  This means that when ZFS is updated to a newer version, this link will become dangling, and the system will not boot up properly if the link is not updated manually before rebooting.
I would say that this is a very dangerous situation.

Any suggestion for another way to link the script without having a hard dependency on the version number?

PS: The ZFS archwiki page refers to `/usr/lib/zfs/zfs/zed.d/` (so without version number) which seems to suggest that this used to be different in the past.

**Comment by minextu** [comment]
Yes, it should probably be located somewhere else. I think having it at `/usr/lib/zfs/zed.d` makes more sense. I pushed a new zfs-utils package to `archzfs-testing` with that change and will update regular repo later.

Thanks for letting me know!
