### ISSUE TITLE
missing repo key

### ISSUE THREAD

**Issue by eoli3n** [archzfs/archzfs#339]
As said here https://github.com/eoli3n/arch-config/issues/1, there is an error when trying to import repo key.
```bash
$ LANG=C pacman-key --recv-keys F75D9D76
gpg: key 403BD972F75D9D76: 2 signatures not checked due to missing keys
gpg: key 403BD972F75D9D76: "ArchZFS Bot <buildbot@archzfs.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

$ cat /etc/pacman.d/gnupg/gpg.conf
no-greeting
no-permission-warning
lock-never
keyserver hkp://pool.sks-keyservers.net
keyserver-options timeout=10
```

**Comment by minextu** [comment]
I don't think that's an error, it looks like it imported the key successfully.
Did you run `pacman-key --lsign-key F75D9D76` after that?

**Comment by eoli3n** [comment]
> 2 signatures not checked due to missing keys

Running ``pacman-key --lsign-key F75D9D76`` doesn't clean that warning.
```
$ LANG=C pacman-key --recv-keys F75D9D76
gpg: key 403BD972F75D9D76: 2 signatures not checked due to missing keys
gpg: key 403BD972F75D9D76: "ArchZFS Bot <buildbot@archzfs.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1

$ LANG=C pacman-key --lsign-key F75D9D76
  -> Locally signing key F75D9D76...
==> Updating trust database...
gpg: next trustdb check due at 2020-05-31

$ LANG=C pacman-key --recv-keys F75D9D76
gpg: key 403BD972F75D9D76: 2 signatures not checked due to missing keys
gpg: key 403BD972F75D9D76: "ArchZFS Bot <buildbot@archzfs.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```
That test was from my host.

-----

From latest archiso, problem is different, it simply fails to add.
Following this -> https://wiki.archlinux.org/index.php/Pacman/Package_signing#Cannot_import_keys
```
$ pacman -Sc
$ pacman -Sy archlinux-keyring
$ pacman-key --populate archlinux
$ pacman-key --recv-keys F75D9D76
```
This fails, as default keyring in archiso use ``hkps``. If i force it without TLS, it works.

```
$ pacman-key --recv-keys F75D9D76 --keyserver hkp://pool.sks-keyservers.net:80
```

**Comment by eoli3n** [comment]
When i add the key after adding archzfs repo, there is also an error about importing a ``unknown`` key.
As a workaround, i had to https://github.com/eoli3n/archiso-zfs/commit/787896e7518f6a0d62a22a1781def913da6cebb8

**Comment by minextu** [comment]
> 2 signatures not checked due to missing keys

That shouldn't be a problem. I signed the archzfs key with my personal gpg key and it's unable to check that one. But that doesn't affect the archzfs key, which looks to be already imported.

So when you run (with the archzfs repo already added):
- `pacman-key --recv-keys F75D9D76`
- `pacman-key --lsign-key F75D9D76`
- `pacman -Sy`

Is there another error coming up?

**Comment by eoli3n** [comment]
Did you change something ? Now it seems to work

**Comment by minextu** [comment]
Nope, but key servers are weird sometimes...
