### ISSUE TITLE
Build out archzfs.com using Hugo

### ISSUE THREAD

**Issue by yanfali** [archzfs/archzfs#34]
Hi @demizer not sure you are aware of this, but the repo appears to be down. This makes getting updates hard unless you want to compile from source. I really appreciate the public service you provide and don't want to make this sound like a complaint.

**Comment by demizer** [comment]
Hello! Thanks for the report. The actual repo url for use in pacman.conf is "http://demizerone.com/demz-repo-core/x86_64/" which appears to be up.

http://demizerone.com/archzfs was the original page describing the packages and that is missing. I will leave this open so it gets fixed.

Thanks!

**Comment by yanfali** [comment]
Thanks @demizer a lot of the wiki and docs are wrong too :) Might want to let the maintainers know.

**Comment by yanfali** [comment]
Man the gpg devs have broken lsign for importing your PGP key. Workaround can be found here https://bbs.archlinux.org/viewtopic.php?id=190301

**Comment by demizer** [comment]
A second person has identified this. It must be fixed.

**Comment by mattronix** [comment]
well guys for now feel free to use https://mattronix.nl/arch/zfs/ as your repo  

and for up to date arch zfs isos: https://mattronix.nl/arch/arch-zfs-isos/

[zfs]  # For zfs packages
Server = https://mattronix.nl/arch/$repo/$arch

**Comment by demizer** [comment]
Website has moved to archzfs.com, but a website is still needed.

**Comment by demizer** [comment]
I want to use https://gohugo.io/ for the static site, and provide a list of links for downloading achive packages.

**Comment by yanfali** [comment]
:+1: Hugo is pretty awesome.

**Comment by demizer** [comment]
Instead of creating a site, we should just have archzfs redirect to the github wiki. This makes it easy for people to contribute update.

**Comment by yanfali** [comment]
:+1:

**Comment by demizer** [comment]
Redirects have been implemented. Thanks!
