### ISSUE TITLE
error: failed retrieving file from archzfs.com - The requested URL returned error: 404

### ISSUE THREAD

**Issue by trytuna** [archzfs/archzfs#348]
Hey,

I am about to update (`pacman -Syu`) zfs-dkms but I am getting the following error:

    error: failed retrieving file 'zfs-dkms-0.8.4-1-x86_64.pkg.tar.zst' from archzfs.com : The requested URL returned error: 404
    error: failed retrieving file 'zfs-dkms-0.8.4-1-x86_64.pkg.tar.zst' from mirror.sum7.eu : The requested URL returned error: 404
    error: failed retrieving file 'zfs-dkms-0.8.4-1-x86_64.pkg.tar.zst' from mirror.biocrafting.net : The requested URL returned error: 404

I unwisely already upgraded the kernel by just ignoring the zfs packages in hope that my current version is still compatible. I guess I am stuck here. Does anyone know what I can do from now on?

**Comment by minextu** [comment]
I removed this package by accident when I switched to zst compression. Sorry about that, it's back now
