### ISSUE TITLE
missing .sig file for zfs-utils-0.8.4-1-x86_64.pkg.tar.zst

### ISSUE THREAD

**Issue by eoli3n** [archzfs/archzfs#354]
In http://archzfs.com/archzfs/x86_64/

My script detect for the latest archiso that it needs to install zfs-utils-0.8.4-1-x86_64.pkg.tar.zst but it fails because of a missing sig file.
![2020-08-20T09:36:53,057814742+02:00](https://user-images.githubusercontent.com/14223657/90730621-b8346700-e2c8-11ea-9b4d-b4febf0c60e1.png)

Could you add the file ?

**Comment by minextu** [comment]
It probably got lost during the transition to zst compression. It's back now, sorry about that.
