### ISSUE TITLE
zfs-dkms-git fails to download files

### ISSUE THREAD

**Issue by epsilon-phase** [archzfs/archzfs#355]
Hi, while attempting to install the git release, I ran into some issues after enabling the repo as instructed.

pacman can't find these files in particular:
```
error: failed retrieving file 'zfs-utils-git-2020.08.23.r6168.g07ce8961e-1-x86_64.pkg.tar.zst' from archzfs.com : The requested URL returned error: 404
error: failed retrieving file 'zfs-dkms-git-2020.08.23.r6168.g07ce8961e-1-x86_64.pkg.tar.zst' from archzfs.com : The requested URL returned error: 404
```

Thank you

**Comment by minextu** [comment]
It might have updated while you were executing pacman. Try running pacman with `-Sy`.

**Comment by epsilon-phase** [comment]
That appears to be it, thank you :)
