### ISSUE TITLE
OpenZFS released 0.8.5

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#360]
Looks like the ol' 0.8.5 came out.

https://github.com/openzfs/zfs/releases/tag/zfs-0.8.5

There *may* be some issue w/ it not listing kernel compatibility?

https://old.reddit.com/r/zfs/comments/j6gtma/release_zfs085_openzfszfs_github/

I have not tried to do it yet. :|

**Comment by minextu** [comment]
Updated, didn't have to modify anything :slightly_smiling_face:
