### ISSUE TITLE
Panic on boot after upgrading to ZFS 2.0 on Arch

### ISSUE THREAD

**Issue by andyleadbetter** [archzfs/archzfs#364]
I have a 5 disk pool, 4 spining 2TB disks, with a 100GB SSD for SLOG/L2ARC
NAME                                       SIZE  ALLOC   FREE  CKPOINT  EXPANDSZ   FRAG    CAP  DEDUP    HEALTH  ALTROOT
data                                      7.27T  4.17T  3.10T        -         -     6%    57%  1.32x    ONLINE  -
  raidz1                                  7.27T  4.17T  3.10T        -         -     6%  57.3%      -  ONLINE  
    eba2d4bd-f2e2-a547-bd26-2b7f8cc3bd82      -      -      -        -         -      -      -      -  ONLINE  
    b2637b48-c2c7-9345-82d4-e7723d16fe8a      -      -      -        -         -      -      -      -  ONLINE  
    cbf26adb-8688-ec4f-b450-8be01c28a773      -      -      -        -         -      -      -      -  ONLINE  
    14f9bec2-feb7-994b-bad6-26e75426f670      -      -      -        -         -      -      -      -  ONLINE  
logs                                          -      -      -        -         -      -      -      -  -
  3579d1eb-8b27-43a4-9917-02eab3ff2882    19.5G   652K  19.5G        -         -     0%  0.00%      -  ONLINE  
cache                                         -      -      -        -         -      -      -      -  -
  sdf2                                    91.8G  91.4G   385M        -         -     0%  99.6%      -  ONLINE  

Since updating the kernel and zpool to the new 2.0 release, I am getting this log in the kernel trace, and see txg_sync spinning at a high disk load.  How can I debug where the error is, I've scrubbed all pools and there is no error found.

VERIFY(avl_find(tree, new_node, &where) == NULL) failed
[   25.055108] PANIC at avl.c:641:avl_add()
[   25.055165] Showing stack for process 2402
[   25.055171] CPU: 0 PID: 2402 Comm: z_livelist_dest Tainted: P           OE     5.9.1-zen2-1-zen #1
[   25.055173] Hardware name: System manufacturer System Product Name/H110M-R, BIOS 4210 07/03/2019
[   25.055174] Call Trace:
[   25.055187]  dump_stack+0x6e/0x90
[   25.055209]  spl_panic+0xef/0x117 [spl]
[   25.055221]  ? __kmalloc_node+0x1ee/0x430
[   25.055230]  avl_add+0x9b/0xb0 [zavl]
[   25.055401]  dsl_livelist_iterate+0x142/0x1f0 [zfs]
[   25.055529]  bpobj_iterate_blkptrs+0x101/0x360 [zfs]
[   25.055680]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[   25.055803]  bpobj_iterate_impl+0x2e0/0x5c0 [zfs]
[   25.055951]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[   25.056099]  dsl_process_sub_livelist+0xb5/0xf0 [zfs]
[   25.056246]  ? dsl_deadlist_cache_compare+0x20/0x20 [zfs]
[   25.056415]  spa_livelist_delete_cb+0x252/0x390 [zfs]
[   25.056609]  zthr_procedure+0x135/0x150 [zfs]
[   25.056794]  ? zrl_is_locked+0x20/0x20 [zfs]
[   25.056812]  thread_generic_wrapper+0x6f/0x80 [spl]
[   25.056828]  ? __thread_exit+0x20/0x20 [spl]
[   25.056834]  kthread+0x19f/0x1d0
[   25.056840]  ? __kthread_init_worker+0x50/0x50
[   25.056847]  ret_from_fork+0x22/0x30

**Comment by andyleadbetter** [comment]
have some other errors showing later

[  246.807485] INFO: task z_livelist_dest:2402 blocked for more than 122 seconds.
[  246.807492]       Tainted: P           OE     5.9.1-zen2-1-zen #1
[  246.807494] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  246.807498] task:z_livelist_dest state:D stack:    0 pid: 2402 ppid:     2 flags:0x00004080
[  246.807506] Call Trace:
[  246.807521]  __schedule+0x42b/0xc10
[  246.807533]  schedule+0x45/0x170
[  246.807553]  spl_panic+0x115/0x117 [spl]
[  246.807566]  ? __kmalloc_node+0x1ee/0x430
[  246.807574]  avl_add+0x9b/0xb0 [zavl]
[  246.807738]  dsl_livelist_iterate+0x142/0x1f0 [zfs]
[  246.807864]  bpobj_iterate_blkptrs+0x101/0x360 [zfs]
[  246.808015]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  246.808139]  bpobj_iterate_impl+0x2e0/0x5c0 [zfs]
[  246.808287]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  246.808451]  dsl_process_sub_livelist+0xb5/0xf0 [zfs]
[  246.808654]  ? dsl_deadlist_cache_compare+0x20/0x20 [zfs]
[  246.808827]  spa_livelist_delete_cb+0x252/0x390 [zfs]
[  246.809018]  zthr_procedure+0x135/0x150 [zfs]
[  246.809199]  ? zrl_is_locked+0x20/0x20 [zfs]
[  246.809217]  thread_generic_wrapper+0x6f/0x80 [spl]
[  246.809237]  ? __thread_exit+0x20/0x20 [spl]
[  246.809244]  kthread+0x19f/0x1d0
[  246.809251]  ? __kthread_init_worker+0x50/0x50
[  246.809258]  ret_from_fork+0x22/0x30
[  246.809267] INFO: task z_livelist_cond:2403 blocked for more than 122 seconds.
[  246.809270]       Tainted: P           OE     5.9.1-zen2-1-zen #1
[  246.809271] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  246.809274] task:z_livelist_cond state:D stack:    0 pid: 2403 ppid:     2 flags:0x00004080
[  246.809278] Call Trace:
[  246.809285]  __schedule+0x42b/0xc10
[  246.809292]  schedule+0x45/0x170
[  246.809307]  spl_panic+0x115/0x117 [spl]
[  246.809319]  ? __kmalloc_node+0x1ee/0x430
[  246.809326]  avl_add+0x9b/0xb0 [zavl]
[  246.809497]  dsl_livelist_iterate+0x142/0x1f0 [zfs]
[  246.809656]  bpobj_iterate_blkptrs+0x101/0x360 [zfs]
[  246.809804]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  246.809928]  bpobj_iterate_impl+0x2e0/0x5c0 [zfs]
[  246.810076]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  246.810224]  dsl_process_sub_livelist+0xb5/0xf0 [zfs]
[  246.810371]  ? dsl_deadlist_cache_compare+0x20/0x20 [zfs]
[  246.810550]  spa_livelist_condense_cb+0xb9/0x210 [zfs]
[  246.810743]  zthr_procedure+0x135/0x150 [zfs]
[  246.810925]  ? zrl_is_locked+0x20/0x20 [zfs]
[  246.810945]  thread_generic_wrapper+0x6f/0x80 [spl]
[  246.810961]  ? __thread_exit+0x20/0x20 [spl]
[  246.810967]  kthread+0x19f/0x1d0
[  246.810973]  ? __kthread_init_worker+0x50/0x50
[  246.810979]  ret_from_fork+0x22/0x30
[  272.103279] kauditd_printk_skb: 5 callbacks suppressed
[  272.103283] audit: type=1109 audit(1603036969.267:338): pid=64331 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:bad_ident grantors=? acct="?" exe="/usr/bin/sshd" hostname=117.71.59.108 addr=117.71.59.108 terminal=ssh res=failed'
[  369.687492] INFO: task z_livelist_dest:2402 blocked for more than 245 seconds.
[  369.687497]       Tainted: P           OE     5.9.1-zen2-1-zen #1
[  369.687499] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  369.687502] task:z_livelist_dest state:D stack:    0 pid: 2402 ppid:     2 flags:0x00004080
[  369.687508] Call Trace:
[  369.687520]  __schedule+0x42b/0xc10
[  369.687530]  schedule+0x45/0x170
[  369.687549]  spl_panic+0x115/0x117 [spl]
[  369.687562]  ? __kmalloc_node+0x1ee/0x430
[  369.687570]  avl_add+0x9b/0xb0 [zavl]
[  369.687733]  dsl_livelist_iterate+0x142/0x1f0 [zfs]
[  369.687860]  bpobj_iterate_blkptrs+0x101/0x360 [zfs]
[  369.688091]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  369.688221]  bpobj_iterate_impl+0x2e0/0x5c0 [zfs]
[  369.688507]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  369.688813]  dsl_process_sub_livelist+0xb5/0xf0 [zfs]
[  369.689100]  ? dsl_deadlist_cache_compare+0x20/0x20 [zfs]
[  369.689733]  spa_livelist_delete_cb+0x252/0x390 [zfs]
[  369.690252]  zthr_procedure+0x135/0x150 [zfs]
[  369.690821]  ? zrl_is_locked+0x20/0x20 [zfs]
[  369.690888]  thread_generic_wrapper+0x6f/0x80 [spl]
[  369.690916]  ? __thread_exit+0x20/0x20 [spl]
[  369.690925]  kthread+0x19f/0x1d0
[  369.690933]  ? __kthread_init_worker+0x50/0x50
[  369.690943]  ret_from_fork+0x22/0x30
[  369.690956] INFO: task z_livelist_cond:2403 blocked for more than 245 seconds.
[  369.690981]       Tainted: P           OE     5.9.1-zen2-1-zen #1
[  369.690983] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[  369.690987] task:z_livelist_cond state:D stack:    0 pid: 2403 ppid:     2 flags:0x00004080
[  369.690994] Call Trace:
[  369.691004]  __schedule+0x42b/0xc10
[  369.691015]  schedule+0x45/0x170
[  369.691040]  spl_panic+0x115/0x117 [spl]
[  369.691084]  ? __kmalloc_node+0x1ee/0x430
[  369.691096]  avl_add+0x9b/0xb0 [zavl]
[  369.691367]  dsl_livelist_iterate+0x142/0x1f0 [zfs]
[  369.691738]  bpobj_iterate_blkptrs+0x101/0x360 [zfs]
[  369.692085]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  369.692513]  bpobj_iterate_impl+0x2e0/0x5c0 [zfs]
[  369.692819]  ? dsl_deadlist_load_tree+0x200/0x200 [zfs]
[  369.693048]  dsl_process_sub_livelist+0xb5/0xf0 [zfs]
[  369.693197]  ? dsl_deadlist_cache_compare+0x20/0x20 [zfs]
[  369.693367]  spa_livelist_condense_cb+0xb9/0x210 [zfs]
[  369.693619]  zthr_procedure+0x135/0x150 [zfs]
[  369.693817]  ? zrl_is_locked+0x20/0x20 [zfs]
[  369.693836]  thread_generic_wrapper+0x6f/0x80 [spl]
[  369.693852]  ? __thread_exit+0x20/0x20 [spl]
[  369.693859]  kthread+0x19f/0x1d0
[  369.693866]  ? __kthread_init_worker+0x50/0x50
[  369.693873]  ret_from_fork+0x22/0x30

**Comment by minextu** [comment]
Sounds like an upstream issue. Try opening a ticket here https://github.com/openzfs/zfs/issues/. You can reopen this issue, if you think it's specific to archzfs.
