### ISSUE TITLE
Rename demz-repo-core back to archzfs

### ISSUE THREAD

**Issue by demizer** [archzfs/archzfs#37]
Originally the repo was named archzfs, but at the time I worked on more packages in AUR and thought it would be cool to have a repository structure similar to the official structure. It turns out, maintaining a linux filesystem is a bunch of work! So I stopped maintaining the other packages in AUR and dedicated myself to archzfs. Now the old naming scheme doesn't really fit.

Since I am in a push to setup automated testing, it would be a great time to rename the repo back to archzfs.

It is possible to redirect requests to demz-repo-core to the new repo name, but I think a jarring breakage is in the spirit of Arch Linux anyways! ;)

This task is to be done after the new archzfs.com is deployed.

**Comment by haraldkoch** [comment]
I could be wrong, but it appears that this change was done recently, and also all the packages have been renamed? Is it safe to switch to the "archzfs" repo and follow pacman's "replace this package with" instructions, or should we wait?

**Comment by demizer** [comment]
Yes this has been done, and it is safe to use. When upgrading you will be asked to choose either "zfs-linux" or "zfs-linux-git". I recommend "zfs-linux", the git packages track the latest changes in the ZFSonLinux projects git repo and are meant for people that need the absolute bleeding edge.
