### ISSUE TITLE
Add dependency on core/which for zfs-utils.

### ISSUE THREAD

**Issue by dmtrbm** [archzfs/archzfs#373]
`/usr/lib/dracut/modules.d/90zfs/module-setup.sh` contains a check `which grep >/dev/null 2>&1 || return 1`, so it will bail if `which` isn't installed.

`grep` is part of `base` group, `which` is only part `base-devel`.
Adding (opt)depends seems like a good idea to save people time troubleshooting why dracut fails to include zfs module.

**Comment by minextu** [comment]
It's part of `base-devel` which is expected to be installed when using makepkg.

> Before continuing, install the base-devel group. Packages belonging to this group are not required to be listed as build-time dependencies (makedepends) in PKGBUILD files.

(https://wiki.archlinux.org/index.php/makepkg#Usage)

**Comment by dmtrbm** [comment]
Yes, but base-devel is a build-time dependency, not a run-time dependency. Plus, archzfs repo provides binary packages. Even building dkms packages doesn't require full base-devel group.

**Comment by minextu** [comment]
Dependency on `which` was removed in zfs 2.1.0
