### ISSUE TITLE
Linux-zen updated again

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#375]
Appears the package was updated a few minutes after the archzfs package was updated.

**Comment by minextu** [comment]
Hmm no, both archzfs and upstream are at `5.10.4.zen2-1` right now as far as I can tell (https://archlinux.org/packages/extra/x86_64/linux-zen)

**Comment by jacksonatl** [comment]
Sorry yay was ignoring the inline # in my ignore list.
