### ISSUE TITLE
The ol' OpenZFS 2.0.1 is out, yay.

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#376]
And it fixes autoconf 2.70, even more yay.

https://github.com/openzfs/zfs/releases/tag/zfs-2.0.1

**Comment by adasauce** [comment]
hoping this fixes the sendfile issues since upgrading to 2.0 in 5.10

**Comment by nightah** [comment]
@adasauce it does:
* https://github.com/openzfs/zfs/pull/11351
* https://github.com/openzfs/zfs/pull/11378

**Comment by fryfrog** [comment]
It's been a few hours since the commit, is there something else needed? Build pipeline stuck?

**Comment by adasauce** [comment]
I think your message unstucked it. 2.0.1 dkms is installing rn for me

**Comment by fryfrog** [comment]
As is the way. :)

**Comment by adasauce** [comment]
and can now confirm I can run nginx with sendfile on again too!

best zfs hotfix in a while for me. thanks everyone down the line!
