### ISSUE TITLE
Linux-LTS 5.4.95-1 released.

### ISSUE THREAD

**Issue by hrast01** [archzfs/archzfs#382]
The 2.0.2 and the new kernel drop happened about the same time it looks like 😄

**Comment by edacval** [comment]
linux-lts-5.4.95-1 is broken: [Issue](https://bugs.archlinux.org/task/69549)

**Comment by hrast01** [comment]
Oh, that is a whole lot of not good.

**Comment by minextu** [comment]
Bug fixed and packages have been updated
