### ISSUE TITLE
package size: zfs-linux is 10x larger than zfs-linux-lts

### ISSUE THREAD

**Issue by scott323** [archzfs/archzfs#383]
I've noticed this when building personal live archiso (where sizes do matter)

```
[root@baraddur ~]# ls -hl /var/cache/pacman/pkg/zfs-linux*.zst
-rw-r--r-- 1 root root  13M Feb  8 01:57 /var/cache/pacman/pkg/zfs-linux-2.0.2_5.10.13.arch1.2-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.3M Feb  6 17:50 /var/cache/pacman/pkg/zfs-linux-lts-2.0.2_5.4.95.1-1-x86_64.pkg.tar.zst
```

Is this expected?

**Comment by minextu** [comment]
Hmm interesting, it looks like the module itself is larger. Might be something to ask upstream.

**Comment by saint-erk** [comment]
It's not an explanation for _why_ zfs.ko is bigger, but I observe that with linux-lts on 5.10.* versions, the zfs-linux-lts packages is also large relative to the 5.4.* linux-lts packages. 

[root@machine]# ls -lh /var/cache/pacman/pkg/zfs-linux-*.zst
-rw-r--r-- 1 root root  14M Jun 12 16:07 /var/cache/pacman/pkg/zfs-linux-2.0.4_5.12.10.arch1.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  14M Jun 27 16:44 /var/cache/pacman/pkg/zfs-linux-2.0.5_5.12.13.arch1.2-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  14M Jul  2 02:35 /var/cache/pacman/pkg/zfs-linux-2.0.5_5.12.14.arch1.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  14M Jul  9 09:03 /var/cache/pacman/pkg/zfs-linux-2.1.0_5.12.15.arch1.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.3M Jan 22 05:40 /var/cache/pacman/pkg/zfs-linux-lts-2.0.1_5.4.91.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.3M Jan 26 16:31 /var/cache/pacman/pkg/zfs-linux-lts-2.0.1_5.4.92.1-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root 1.3M Jan 30 06:21 /var/cache/pacman/pkg/zfs-linux-lts-2.0.1_5.4.93.2-1-x86_64.pkg.tar.zst
-rw-r--r-- 1 root root  14M Jul  9 09:02 /var/cache/pacman/pkg/zfs-linux-lts-2.1.0_5.10.48.1-1-x86_64.pkg.tar.zst

**Comment by endreszabo** [comment]
Maybe the modules are not `strip`ped anymore?

**Comment by minextu** [comment]
Yes, strip didn't work, because it is compressed in the install step. It will now manually do that during build, so packages will be smaller again on the next kernel update. Thanks!
