### ISSUE TITLE
Shucks, 2.0.3 is out now!

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#385]
Doesn't seem to be a lot in this one, but +0.0.1 is +0.0.1!

Set file mode during zfs_write #11474 #11576
zfs-import-{cache,scan}: change condition to FileNotEmpty #11568
dracut: Fix race condition between load-key and import #11500
zfs-list.8: clarify listing snapshots #11562 #11565
zts-report.py: ignore some skipped tests in Github CI #11554
CI: add ubuntu-* functional tests runner #11554
CI: rename zfs-tests workflow #11554

https://github.com/openzfs/zfs/releases/tag/zfs-2.0.3

**Comment by minextu** [comment]
Updated
