### ISSUE TITLE
Cannot import root zpool at boot after updating from zfs-util/zfs-dkms 0.8.5 to 2.0.0+

### ISSUE THREAD

**Issue by derzahla** [archzfs/archzfs#386]
I've been stuck for quite awhile now on this. I have now again tried the latest zfs-utils and zfsdkms (2.0.3). I have most recently tried compiling the latest zfs-utils and zfs-dkms PKGBUILDS directly from this git repo and the problem is still present.

bootloader boots, asks for my luks decryption key, then tries to import the root zpool and the kernel panics, saving no valid zpool is found.

Interestingly enough, I've been using a manjaro usb disk which has zfs 2.0.0 to chroot back into my filesystem and reinstall the old 0.8.5 packages when I break the systems.  I am able to manually unlock the luks device and import the zpool without problem. So something must have changed with the initrd boot hooks or something. Im just not that familiar with the whole process and havent been able to find a solution yet despite many hours of trying.  Any idea what the problem might be? Thanks

**Comment by stevleibelt** [comment]
Hey @derzahla, are you using grub? If so, can you post part of your grub.cfg plus the output of the "ls -la /dev/disc/by-uuid"?

For example, following one line of my grub.cfg.

```
linux   /vmlinuz-linux zfs=br01 rw cryptdevice=/dev/disk/by-uuid/54a90420-c694-4524-8587-5d25df82af7e:crypto-br01 quiet ipv6.disable=1 i915.semaphores=1 i915.execlist=0 nosmap
```

Last part is not important, but the the first parts until `quiet` is the one.
`br01` is my pool and the uuid points to my pool partition (sda3).

For the log, this is my current setup.

```
zfs --version
zfs-2.0.3-1
zfs-kmod-2.0.3-1

uname -a
Linux <host> 5.10.15-arch1-1 #1 SMP PREEMPT Wed, 10 Feb 2021 18:32:40 +0000 x86_64 GNU/Linux

```

Cheers,
Stev

**Comment by derzahla** [comment]
Hi Stev, thanks for the fast reply.  Im actually using refind since.  This is my boot line:

"Boot with standard options"  "ro root= cryptdevice=UUID=7042cc7a-9964-4684-817f-944b755a4306:cryptroot cryptdevice=UUID=7042cc7a-9964-4684-817f-944b755a4306:luks-7042cc7a-9964-4684-817f-944b755a4306 root=zfs zfs=z/ROOT/manjaro/root udev.log_priority=3 ro zfs=z/ROOT/manjaro/root rw"

which, now that you mention it looks very odd.  Going to see if I can figure out why theres all this redundancy and get back to you.

**Comment by stevleibelt** [comment]
Good luck, I've carried my poll since 2015 and ran into multiple issues back and than. And yes, your config is looking really odd :-D.

**Comment by derzahla** [comment]
Ok, i had to do some massive cleanup. still not sure of why there are duplicates showing up in my grub.cfg when theyre not in /etc/default/grub.  Resinatlled zfs v2.0.3 and going to try again

linux   /vmlinuz-5.9-x86_64 root=ZFS=z/ROOT/manjaro/root rw  cryptdevice
=UUID=7042cc7a-9964-4684-817f-944b755a4306:cryptroot zfs=z/ROOT/manjaro/root rw

**Comment by derzahla** [comment]
That seemed to work with the 5.9 kernel.  Now I will try 5.10, since zfs-dkms 0.8.5 wouldnt compile at all against 5.10 headers.

**Comment by derzahla** [comment]
Ok, all good pretty much!  thanks for pointing me in the right direction. I didnt even think to check my kernel boot line for craziness seeing as worked fine until i switched to zfs v2.

grub-mkconfig is still ended up with:
linux	/vmlinuz-5.10-x86_64 root=ZFS=z/ROOT/manjaro/root rw  cryptdevice=UUID=7042cc7a-9964-4684-817f-944b755a4306:cryptroot zfs=z/ROOT/manjaro/root rw

even though my /etc/default/grub config is:

GRUB_CMDLINE_LINUX_DEFAULT="cryptdevice=UUID=7042cc7a-9964-4684-817f-944b755a4306:cryptroot zfs=z/ROOT/manjaro/root rw"
GRUB_CMDLINE_LINUX=""

so something seems odd.  thanks alot though!

**Comment by stevleibelt** [comment]
Now that you've pointed me into the direction too, I can remember that I had to fix the initial created grub.cfg always.
After a while, my grub.cfg was never updated so all was fine. Anywas, I've created a git repository to have version control for my grub.cfg at the right place.
Glad that your system is up and running again :-).

**Comment by minextu** [comment]
I might be wrong, but If I remember correctly grub detects the `zfs` pool automatically and attaches the appropriate `zfs` parameter when running `grub-mkconfig`. So having it in `/etc/default/grub` will cause a duplication. Maybe something to try.
