### ISSUE TITLE
OpenZFS behind on stable support for the latest Linux Kernel release

### ISSUE THREAD

**Issue by elXaptation** [archzfs/archzfs#388]
Ran in to this problem today, setting up a new dev system. 

Based on the "When to create an issue" guidelines, "packages are out of date", I took that to mean this situation should be reported.

My new installation of Arch Linux installs 5.11.1.arch1-1, the stable OpenZFS version expects 5.10.16.arch1-1. 

I used the Arch Linux Wiki guide to install Arch on ZFS using the ISO and the archiso-system zfs module installer ( https://github.com/eoli3n/archiso-zfs ). The ISO was based on linux 5.10.11. The module installer was able to find the package in the archives and enabled me to create my partitions, zpool and datasets. I pointed pacstrap at the datasets and installed the base system successfully. That base includes linux 5.11.1.arch1-1.

I'm not surprised. I was aware of this possibility from reading the documentation before I started. Any guidance on when stable OpenZFS can be expected to catch up to Arch? I understand this may be a while, but at least I'll know I should go find a different strategy in the meantime. Thank you.

**Comment by kido5217** [comment]
There's two options I can think of:

1. Use linux-lts instead of linux package.
2. Use zfs-dkms instead of kernel-specifix one.

**Comment by elXaptation** [comment]
Thanks. I'll give it a try.

> There's two options I can think of:
> 
>     1. Use linux-lts instead of linux package.
> 
>     2. Use zfs-dkms instead of kernel-specifix one.

**Comment by minextu** [comment]
Packages have been updated again.

Another way is to do is in the future, is to use the archzfs testing repository which generally gets updated faster:
```
[archzfs-testing]
Server = https://archzfs.com/$repo/$arch
```

**Comment by elXaptation** [comment]
Thank you very much.


> Packages have been updated again.
> 
> Another way is to do is in the future, is to use the archzfs testing repository which generally gets updated faster:
> 
> ```
> [archzfs-testing]
> Server = https://archzfs.com/$repo/$arch
> ```
