### ISSUE TITLE
Add a fully ZFS-enabled GRUB package

### ISSUE THREAD

**Issue by kerberizer** [archzfs/archzfs#39]
The current Arch [GRUB packages](https://www.archlinux.org/packages/?name=grub) don't recognize ZFS pools upgraded to support the most recent feature flags. This is because [upstream GRUB](http://git.savannah.gnu.org/cgit/grub.git) lacked proper support for the `hole_birth` and `embedded_data features` up until very recently.[1,2]

The problem doesn't affect booting, i.e. even systems with unpatched GRUB and fully upgraded pools boot normally, but grub-install would fail to recognize the ZFS filesystem on the required devices. This essentially makes new installations with ZFS next to impossible.

Seeing that it took nine months for the required patches to get incorporated upstream, and not to mention that we'll have to wait even more for a new GRUB release and then updated Arch packages, it makes sense for us to maintain a separate GRUB package with always current support for ZFS.  

**NB:** Pull request #41 follows progress.

---
1. http://git.savannah.gnu.org/cgit/grub.git/commit/?id=a1007c6af296172c788f3346ff3ad30b9020f723
2. http://git.savannah.gnu.org/cgit/grub.git/commit/?id=4a7ea4003bd9f39e9bf2ebadbe4ab38f8874be66

**Comment by techmunk** [comment]
It'd be awesome to have a grub package built and available with the other ZFS packages.

I've been able to get grub working 100% with arch by taking the following steps: (This is for a whole disk ZFS on root install)

#### Can be done on any machine to build the ZFS enabled grub package
1. Download Grub git package from the AUR. https://aur.archlinux.org/packages/grub-git/
2. Install zfs-git package on build machine. (Adds ZFS include files for building Grub)
3. Add `--enable-libzfs` to configure lines in grub-git PKGBUILD
4. makepkg

#### Install steps from ZFS enabled archiso image.
1. See https://wiki.archlinux.org/index.php/Installing_Arch_Linux_on_ZFS for main info, but essentially follow on from "Setup the ZFS filesystem". **For whole disk setup DO NOT DO THE "Partition the destination drive" STEP**.
2. After your `pacstrap /mnt base zfs-git`, but before chrooting into /mnt, be sure to copy the grub package compiled above, into this new root.
3. Just before chrooting, we need to setup somewhere for grub-install to put it's core.img. Run `gdisk /dev/sda` (Adjust for the disk you'd like to boot from), add a new partition. This will be partition number 2, and it will start at sector 34, and end at sector 2047, and will be of type EF02. This is outside of the partitions ZFS creates. The table should look like:
```
Number  Start (sector)    End (sector)  Size       Code  Name
   1            2048        16758783   8.0 GiB     BF01  zfs
   2              34            2047   1007.0 KiB  EF02  BIOS boot partition
   9        16758784        16775167   8.0 MiB     BF07
```
After writing the new partition table, you might need to run `partprobe` to have the new table loaded.
3. Once chrooted, do the mkinicpio steps as per the guide linked above.
4. Install the grub package we previously built (`pacman -U grub-git`)
5. Edit /etc/default/grub, and add the following to the `GRUB_CMDLINE_LINUX_DEFAULT` property
`zfs=bootfs zfs_import_dir=/dev/disk/by-id` (Only add zfs_import_dir if you used /dev/disk/by-id to create your pool).
6. Run grub install `grub-install --recheck /dev/sda` (Use the same device you partitioned above).
7. Run grub-mkconfig `grub-mkconfig -o /boot/grub/grub.cfg`
8. exit chroot, unmount and export pool and reboot.
9. Profit - You now have a whole disk ZFS on root install that will boot up just fine, with all zpool features enabled.

**Comment by kerberizer** [comment]
@techmunk, thanks a lot for the detailed explanation. I'm afraid I'll have to admit being lazy here, because the grub-zfs PKGBUILD [has in fact been in my repo](https://github.com/kerberizer/archzfs-git/tree/master/grub-zfs) for quite some time, and I only need to integrate it into demizer's build infrastructure (I still use my own, unpublished script for the job).

**Comment by mattronix** [comment]
If you would like i have a fix for this my friend @nathan7 created a patched grub bootloader for this. 

also he created a  neet tool for installing the boot partition on zfs: https://github.com/nathan7/bootr

**Comment by kerberizer** [comment]
Both [grub](https://www.archlinux.org/packages/core/x86_64/grub/) and [grub-git](https://aur.archlinux.org/packages/grub-git/) nowadays offer good ZFS support. (forgot to close the issue together with #41)
