### ISSUE TITLE
zfs 2.0.4 is out

### ISSUE THREAD

**Issue by kido5217** [archzfs/archzfs#390]
With support for 5.11 kernel
[https://github.com/openzfs/zfs/releases/tag/zfs-2.0.4](https://github.com/openzfs/zfs/releases/tag/zfs-2.0.4)

**Comment by fryfrog** [comment]
Probably should have given it a humorous title to attract the attention of @minextu :)

**Comment by minextu** [comment]
That could be the case, or I was just busy and forgot about updating :smile:
Anyways it's updated now :slightly_smiling_face:
