### ISSUE TITLE
zfs-import.service masked

### ISSUE THREAD

**Issue by david-morris** [archzfs/archzfs#395]
I had a working system with zfs-linux but I needed to update and didn't want my kernel version lagging because I didn't notice.

So I switched to zfs-dkms 2.0.4 and now zfs-import.service is masked (it's a link to /dev/null).

Does this repo cover the zfs-dkms package?  Has anyone got mounting on boot working with zfs-dkms? I also tried the zfs-mount-generator method on the wiki, and that has not worked for me.

**Comment by david-morris** [comment]
I should add --- I use zfs for a media partition, so there is no issue with kernel parameters as I've never added any for zfs, so this doesn't overlap with #386 .

**Comment by minextu** [comment]
Checkout https://wiki.archlinux.org/title/ZFS#Automatic_Start

You'll need to enable zfs-import.**target**, zfs-import-cache.service, zfs-mount.service, zfs.target
