### ISSUE TITLE
Linux 5.12 compatibility

### ISSUE THREAD

**Issue by frebib** [archzfs/archzfs#398]
Arch got 5.12 today (recently?) https://archlinux.org/packages/core/x86_64/linux/
The various Linux 5.12 compatibility patches from upstream should be applied until there is a new release that includes them.
These are probably most/all of the required patches: https://github.com/openzfs/zfs/search?q=linux+5.12&type=commits

Some prior art of mine: https://github.com/archzfs/archzfs/commit/0329db31910451de423b38afdd1a9f0ccbe48c7e

**Comment by fryfrog** [comment]
https://github.com/eli-schwartz/pkgbuilds/pull/24

^ If it helps, this is the PR for aur/zfs-dkms.

**Comment by jonathonf** [comment]
Wait on using that PR, I'm looking to get the necessary compat changes backported into zfs-2.0.5-staging.

**Comment by ne9z** [comment]
For anyone in a hurry, `zfs-dkms-git` package is [tested](https://github.com/openzfs/openzfs-docs/issues/162#issuecomment-834092513) to be compatible with 5.12 kernel, **might contain bugs**.

**Comment by minextu** [comment]
Packages have been updated with the backported patches
