### ISSUE TITLE
zpool_influxdb missing from the 2.1.0 build

### ISSUE THREAD

**Issue by steven-omaha** [archzfs/archzfs#406]
I have the latest build installed.
Name                     : zfs-linux
Version                  : 2.1.0_5.12.14.arch1.1-1

zfs-2.1.0 introduces a new command, `zpool_influxdb`. https://github.com/openzfs/zfs/pull/10786 Since this is not a subcommand of `zpool`, it needs to be added to the PKGBUILD.

**Comment by minextu** [comment]
I just added it, you can now find it under `/usr/lib/zfs/zpool_influxdb`.
Thank you for reporting this :slightly_smiling_face:

**Comment by steven-omaha** [comment]
Thank you for the quick fix!
