### ISSUE TITLE
Updating to 2.1.0_5.12.15 causes SEGV

### ISSUE THREAD

**Issue by valkum** [archzfs/archzfs#407]
When trying to update to the newest kernel with newest zfs release I get a SEGV. The SEGV is raised before a new boot env is written.

My output is along the lines of (not much really)
```
systemd(1): SEGV
```

Command to run:
`pacman -Sy --needed linux linux-headers zfs-linux zfs-utils`

My system follows the guide on https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Arch%20Linux%20Root%20on%20ZFS.html

If you need more information, please guide me. As my system crashes right at the upgrade I am not able to fetch any generated coredumps. I currently boot into a bootenv right before the segfaulting update.

**Comment by minextu** [comment]
Please reopen, if this is still an issue
