### ISSUE TITLE
zfs does not work with iso image

### ISSUE THREAD

**Issue by DCastellacci** [archzfs/archzfs#418]
Hello

I am on Arch Linux version 5.14.14-arch1-1 archlinux-2021.10.01-x86_64.iso I built a vm with FreeBSD Bhyve I converted Bhyve image to squashfs and built an iso file is boot with bhyve everything works except zfs when I am under bhyve vm not the iso but the image of the vm bhyve the zfs works perfectly but when I am under bhyve with the iso boot that is to say that bhyve starts with an iso image as everything also works except zfs here is the error message that I receive "arch linux modprobe fatal module zfs not found in directory 5.14.8-arch1-1" it's curious that asks me for a path with a directory 5.14.8-arch1-1 then that the version is 5.14.14-arch1-1 I specify that this message only appears with the iso image and not with the bhyve image of the vm have any idea to solve the problem?

Thank you Didier

**Comment by stevleibelt** [comment]
Hey @DCastellacci, would it be possible that you put some "sentence stop marks" like "." and some more format in your issue ticket?
Currently, it is hard to read which complicates the part of understanding.

Thanks in advance.

**Comment by DCastellacci** [comment]
Hello

I am on Arch Linux version 5.14.14-arch1-1 archlinux-2021.10.01-x86_64.iso.

I built a vm with FreeBSD Virtual Machin PLayer Bhyve, and converted the Bhyve image to squashfs; and i built an iso file and i booted with bhyve under the iso image; everything is working; except zfs.

When I am under bhyve Virtual Machin PLayer not under the iso image, but with the image of the Virtual Machin PLayer bhyve; the zfs works perfectly.

But when I am under VM Player bhyve and that I boot with the iso image, that is to say that bhyve starts with an iso image as an image, everything also works; except zfs here is the error message that I recognize "arch linux modprobe fatal module zfs not found in directory 5.14.8-arch1-1".

It's odd that "modprobe" asks me for a path with a 5.14.8-arch1-1 directory while the version of Arch linux is 5.14.14-arch1-1
I specify that this message only appears with the iso image and not with the image of the virtual machine.

Do you have any idea to solve the problem ?

Thank you Didier

**Comment by DCastellacci** [comment]
Hello,

The problem came from the kernel version difference between the iso image and the virtual machine image.

Problem solved

I did not encounter any problem with zfs neither with the installation nor with its function.

Thank you
Didier
