### ISSUE TITLE
Failed to create arch iso zfs image.

### ISSUE THREAD

**Issue by odror** [archzfs/archzfs#419]
When trying to create arch iso with zfs I get the following error.
sudo mkarchiso -v -w /tmp .
```
warning: cannot resolve "linux=5.15.2.arch1-1", a dependency of "zfs-linux"
:: The following package cannot be upgraded due to unresolvable dependencies:
      zfs-linux

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'linux=5.15.2.arch1-1' required by zfs-linux
==> ERROR: Failed to install packages to new root
```

**Comment by DCastellacci** [comment]
sorry I got the wrong post

**Comment by odror** [comment]
That was the issue. I had to date back by 2 days pacman.conf

**Comment by stevleibelt** [comment]
@odror same "issue" for me, I am always building my [archiso](https://github.com/stevleibelt/arch-linux-live-cd-iso-with-zfs) when I was able to update a running arch linux machine with zfs. This way, I "ensure" that the zfs and the linux kernel are compatible currently.
Indeed, this is only a suitable solution for home users.

What do you mean with "date back by 2 days pacman.conf"? Is there an option to date back a pacman.conf file?

**Comment by odror** [comment]
something like that

```
[core]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2017/08/18/$repo/os/$arch

[extra]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2017/08/18/$repo/os/$arch

[community]
SigLevel = PackageRequired
Server=https://archive.archlinux.org/repos/2017/08/18/$repo/os/$arch

```

**Comment by stevleibelt** [comment]
@odror thank you very much. Didn't know this is possible.
