### ISSUE TITLE
Issue with loop devices in ZFS v2.1.2 and Linux 5.16.x

### ISSUE THREAD

**Issue by Thrilleratplay** [archzfs/archzfs#432]
I wanted to document this here as it took me some time to track down the cause.  It seems that ZFS was relying on ~deprecated kernel functions that were removed~ renamed/moved functions in 5.16.

https://github.com/openzfs/zfs/issues/12926

ZFS has been patched to correct this in master but not in a release.

**Comment by rincebrain** [comment]
They weren't really "deprecated" for any stretch, 5.16 just renamed one, put another in a different header, and changed the call signature on a third, with no period of adjustment where the old and new co-existed.

**Comment by rigred** [comment]
Code is merged in with the 2.1.3 release staging patchset
https://github.com/openzfs/zfs/pull/12975
https://github.com/openzfs/zfs/pull/13063

But really this should be pushed out earlier since things can break quite badly when loop devices don't work.

**Comment by minextu** [comment]
zfs 2.1.3 has been released and packages have been pushed. This should be fixed now
