### ISSUE TITLE
DKMS package fails to build in vanilla live environment

### ISSUE THREAD

**Issue by ne9z** [archzfs/archzfs#436]
I'm using 2022.03.01 iso.

```
checking kernel source version... 5.16.11-arch1-1
checking kernel file name for module symbols... Module.symvers
checking whether modules can be built... no
configure: error: 
	*** Unable to build an empty module.
			

Building module:
cleaning build area...(bad exit status: 2)
make -j1 KERNELRELEASE=5.16.11-arch1-1...(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.16.11-arch1-1 (x86_64)
```

See also this issue: https://github.com/openzfs/openzfs-docs/issues/277

**Comment by minextu** [comment]
Just to make sure, did you install the correct `linux-headers` packages for the kernel on the iso?

**Comment by ne9z** [comment]
Yes I have.  I'm installing according to [this page](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/2-zfs-dkms.html#installation).

**Comment by minextu** [comment]
There is probably not enough space on the iso filesystem for the dkms build. 

Instead you can install the appropriate zfs-linux version from the archive to match the iso's kernel version, along with the utils package. This script from eoli3n does it automatically: https://github.com/eoli3n/archiso-zfs 

Or follow this guide to integrate zfs into the iso directly: https://wiki.archlinux.org/title/ZFS#Create_an_Archiso_image_with_ZFS_support

**Comment by ne9z** [comment]
> probably not enough space

I forgot to mention that I have expanded the CoW space with `mount -o remount,size=2G /run/archiso/cowspace/`.

> base-devel are missing / out of sync, 3rd script, custom ISO

Thanks for the tip.

**Comment by Reuenthal767** [comment]
I'm having the exact same problem with 2022.04.05 and 2022.05.01.

The CoW space was expanded to 50% of ram (so ~8GB) so I don't thik that's the culprit.

I've managed to make it work with eoli3n script, but only on 2022.04.05.

**Comment by cbc02009** [comment]
Same situation as @Reuenthal767 (thanks for the heads up about image version!). Not sure what the cause is, but the openzfs instructions no longer work (I think because there's no kernel image in /boot on the live image for zfs-dkms to update?)

The script worked for me with 2022.04.05.
