### ISSUE TITLE
zfs-2.1.4 is out!

### ISSUE THREAD

**Issue by hrast01** [archzfs/archzfs#443]
Thanks!

**Comment by DerVerruckteFuchs** [comment]
An FYI for the repository maintainer(s): zfs-2.1.3 only supports Linux kernels up to 5.16, and the kernel version currently available in the official Arch repositories is 5.17.1. zfs-2.1.4 is necessary for kernel version 5.17.1. Right now a regular update could potentially be hazardous for users that want to interact with any zfs pools/datasets, or use zfs for their root volume(s).

**Comment by i3Craig** [comment]
Confirmed to not be compatible with the latest kernel available (5.17.1).
Hopefully zfs-2.1.4 will be put out soon.
![scrot](https://user-images.githubusercontent.com/70919757/160728661-77b4e981-b245-4981-830e-4369ecbbe7e5.png)
