### ISSUE TITLE
ZFS update fails to build module, segfaults core dumped during build.

### ISSUE THREAD

**Issue by Sweeper5** [archzfs/archzfs#452]
As I try to update, the ZFS module breaks, I attempted both the git and normal DKMS module.
<details>
  <summary>Pacman output</summary>
  
A copy and paste output of my Pacman output
  
  ```bash
==> dkms install --no-depmod zfs/git -k 5.18.7-arch1-1
/usr/bin/dkms: line 757: 1885781 Segmentation fault      (core dumped) ( cd "$dkms_tree/$module/$module_version/$script_type/"; exec $run )
Error! Bad return status for module build on kernel: 5.18.7-arch1-1 (x86_64)
Consult /var/lib/dkms/zfs/git/build/make.log for more information.
==> WARNING: `dkms install --no-depmod zfs/git -k 5.18.7-arch1-1' exited 10
==> dkms install --no-depmod zfs/git -k 5.15.52-1-lts
/usr/bin/dkms: line 757: 1888279 Segmentation fault      (core dumped) ( cd "$dkms_tree/$module/$module_version/$script_type/"; exec $run )
Error! Bad return status for module build on kernel: 5.15.52-1-lts (x86_64)
Consult /var/lib/dkms/zfs/git/build/make.log for more information.
==> WARNING: `dkms install --no-depmod zfs/git -k 5.15.52-1-lts' exited 10
==> ERROR: Missing 5.18.5-arch1-1 kernel headers for module zfs/git.
==> ERROR: Missing 5.17.9-arch1-1 kernel headers for module zfs/git.
==> ERROR: Missing 5.18.3-arch1-1 kernel headers for module zfs/git.
==> ERROR: Missing 5.18.6-arch1-1 kernel headers for module zfs/git.
  ```
  
</details>

And from the makefile it references:
<details>
  <summary>ZFS makefile output</summary>
  
A copy and paste output of the makefile.log contents
  
  ```bash
DKMS make.log for zfs-git for kernel 5.15.52-1-lts (x86_64)
Sun Jul  3 06:25:34 PM CEST 2022
make: *** No targets specified and no makefile found.  Stop.
  ```
  
</details>

**Comment by minextu** [comment]
Is this still an issue for you? It sounds like there are missing headers for some of the kernels you have

**Comment by Sweeper5** [comment]
I think not, as there are no other comments about similar issues, I think I found where the problem occurred and it was a bit strange.
https://bbs.archlinux.org/viewtopic.php?id=277744
Basically glibc seemed to be corrupted / misbehaving and forcing a reinstall of that seemed to cure the issue.
I am still perplexed if glibc had a corruption as to how it could have been corrupted as the pool it was installed on was a mirror with copies = 2 to fight that eventuality.
