### ISSUE TITLE
Update for Linux and Linux-zen to 5.19 kernel

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#458]

**Comment by fpf3** [comment]
Is there an update to the kernel module available? Is it just getting it packaged for this repo?

**Comment by jacksonatl** [comment]
Just updating the repo, looks good now I'll close the ticket

**Comment by fpf3** [comment]
Just tried upgrading again - there still appears to be an issue:

```
:: Do you want to skip the above package for this upgrade? [y/N]
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'linux=5.19.3.arch1-1' required by zfs-linux

```

Did the kernel update again since earlier today?
