### ISSUE TITLE
requires linux=4.2.1-1

### ISSUE THREAD

**Issue by tristan-k** [archzfs/archzfs#46]
I cant update my system anymore.

    $ uname -a
    Linux pb4540s 4.2.1-1-ARCH #1 SMP PREEMPT Tue Sep 22 06:57:07 CEST 2015 x86_64 GNU/Linux
    $ pacman -Syu
    :: Starting full system upgrade...
    resolving dependencies...
    looking for conflicting packages...
    error: failed to prepare transaction (could not satisfy dependencies)
    :: spl-git: requires linux=4.2.1-1
    :: zfs-git: requires linux=4.2.1-1

**Comment by Finkregh** [comment]
sorta-dup of https://github.com/archzfs/archzfs/issues/28

**Comment by demizer** [comment]
Dupe of #28
