### ISSUE TITLE
zfs-linux parallel to zfs-dkms

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [archzfs/archzfs#462]
In the PKGBUILD for the `zfs-linux` package (and its variants), the `zfs-dkms` package (and its variants) are listed under `conflicts`. This makes sense from the standpoint that both packages provide ZFS functionality as kernel modules. However, I see use cases where having both installed in parallel would be desirable: For example, most of the times I use one of the common kernels e.g. like the linux, linux-lts, and linux-zen kernels, having them installed in parallel. These, of course, are conveniently provided pre-compiled by this project. Hovewer, if I now want to use/try out a customized kernel, a kernel with a new feature, or the like, I need install `zfs-dkms` for this kernel. Due to the mentioned conflict, installing `zfs-dkms` uninstalls all the zfs-linux, zfs-linux-lts, zfs-linux-zen, etc. packages and for each installed kernel dkms starts to compile the respective kernel module, which were before pre-compiled. So in order to have one custom kernel installed, I have to now locally compile all otherwise pre-compiled kernels for each kernel update. Therefore, it would be desirable to be able to keep the zfs-linux* packages while being able to compile ZFS modules for custom kernels via `zfs-dkms`. Is this possible from a technical perspective?

**Comment by minextu** [comment]
Closing this for now. Feel free to reopen, if anyone has an idea how this can be done
