### ISSUE TITLE
Error: Not Found While Loading vmlinuz-linux

### ISSUE THREAD

**Issue by stooone** [archzfs/archzfs#463]
Hi,

I had this problem a few times in the past and I have it now. I wasn't able to find the root cause for it.

I use rEFInd to boot Arch. Nothing fancy:
```
timeout 20
scanfor manual
scan_all_linux_kernels false
default_selection "Arch Linux"

menuentry "Arch Linux" {
    icon /EFI/refind/icons/os_arch.png
    volume arch-linux
    loader /vmlinuz-linux
    initrd /initramfs-linux.img
    options "zfs=waco/ROOT/default rw ipv6.disable_ipv6=1 ip=192.168.100.7::192.168.100.1:255.255.255.0::eth0:none"
}
```
My /boot is on ext4 on a software RAID.

After the last upgrade to 5.19.13-arch1-1 it doesn't boot:

`Error: Not Found While Loading vmllinuz-linux.`

If I downgrade the kernel and ZFS it is OK.

`pacman -U linux-5.18.10.arch1-1-x86_64.pkg.tar.zst zfs-linux-2.1.5_5.18.10.arch1.1-1-x86_64.pkg.tar.zst zfs-linux-headers-2.1.5_5.18.10.arch1.1-1-x86_64.pkg.tar.zst nvidia-515.57-4-x86_64.pkg.tar.zst zfs-utils-2.1.5-4-x86_64.pkg.tar.zst nvidia-utils-515.57-1-x86_64.pkg.tar.zst`

I can't spot any difference just the kernel and initrd file. If I don't downgrade just overwrite the files on my /boot partition then it boots (with many errors, since other files missing, but boots). So the only problem can be the kernel file, but I suppose that if it has any errors then others would also rise the voice. So I don't get it.

Please suggest how to go forward to track down the issue.

**Comment by stevleibelt** [comment]
Since it is a kernel module, is there an issue when calling `mkinitcpio`?

**Comment by stooone** [comment]
No problems have been reported during mkinitcpio.

**Comment by stooone** [comment]
It turned out that the problem is with the 5.19 kernel. Sorry for opening the ticket here.
