### ISSUE TITLE
Unable to import PGP key

### ISSUE THREAD

**Issue by superbonaci** [archzfs/archzfs#473]
Trying on Arch:
````
archzfs      14.1 KiB  86.5 KiB/s 00:00 [################################] 100%
error: archzfs: key "DDF7DB817396A49B2A2723F7403BD972F75D9D76" is unknown
:: Import PGP key DDF7DB817396A49B2A2723F7403BD972F75D9D76? [Y/n] Y
error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```

**Comment by 1da1a172** [comment]
See the [wiki](https://wiki.archlinux.org/title/Pacman/Package_signing#Adding_unofficial_keys) on how to add keys for unofficial repositories.

You can grab the key from [`archzfs.gpg`](https://zxcvfdsa.com/archzfs/archzfs.gpg) on one of the mirrors. Admittedly, this isn't a great way to distribute the keys, but you can at least TOFU (trust on first use) it.

**Comment by 1da1a172** [comment]
Ah, I knew there was a better source for the key. As noted in the repo [wiki](https://github.com/archzfs/archzfs/wiki#using-the-archzfs-repository), you can get the key from https://archzfs.com/archzfs.gpg .

**Comment by stevleibelt** [comment]
Duplicated issue, see [issue/481](https://github.com/archzfs/archzfs/issues/481) :-) (no fronting)
