### ISSUE TITLE
Signature is unknown trust

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#481]
Did the signing change for the package? Or is something messed up?

```
fryfrog@redwing ~  ❯ paru
error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 archzfs                                                   14.9 KiB  27.5 KiB/s 00:01 [#################################################] 100%
error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust
error: failed to synchronize all databases (invalid or corrupted database (PGP signature))
```

**Comment by fryfrog** [comment]
The downloading it directly step in the wiki "fixes" it, but it doesn't seem crazy to check this was an intentional change?

**Comment by minextu** [comment]
The gpg key used have an expiry date on feb 2nd 2023, but it has been updated quite a while ago. This would happen if you imported the key a long time ago. Try refeshing it:

```
sudo pacman-key --refresh-keys DDF7DB817396A49B2A2723F7403BD972F75D9D76
```

Or if this doesn't work, delete and import again:
```
pacman-key -d DDF7DB817396A49B2A2723F7403BD972F75D9D76
pacman-key -r DDF7DB817396A49B2A2723F7403BD972F75D9D76
pacman-key --lsign-key DDF7DB817396A49B2A2723F7403BD972F75D9D76
```

Or as a third solution, download and import archfs.gpg manually: https://github.com/archzfs/archzfs/wiki#using-the-archzfs-repository

**Comment by fryfrog** [comment]
Yeah, it'd be from ages ago. Thanks, I should have wiki'd first :P
