### ISSUE TITLE
Unknown trust for buildbot keys

### ISSUE THREAD

**Issue by FluxusMagna** [archzfs/archzfs#483]
When I ran `pacman -Syu` I got this message

```
error: archzfs: signature from "ArchZFS Bot <buildbot@archzfs.com>" is unknown trust
```
 I've followed the procedure in the wiki and manually added the keys,
 
 ```
 $ sudo pacman-key -r DDF7DB817396A49B2A2723F7403BD972F75D9D76
gpg: key 403BD972F75D9D76: "ArchZFS Bot <buildbot@archzfs.com>" 3 new signatures
gpg: Total number processed: 1
gpg:         new signatures: 3
$ pacman-key --lsign-key DDF7DB817396A49B2A2723F7403BD972F75D9D76
 ```
 
 But the issue remains. I've also updated `archlinux-keyring`.

**Comment by minextu** [comment]
You probably have the old key still, which recently expired. 

Checkout https://github.com/archzfs/archzfs/issues/481 which should be the same issue you are having

**Comment by FluxusMagna** [comment]
Deleting it and reimporting it seems to have worked. Thanks for the quick response!
