### ISSUE TITLE
Update for 6.2.8 linux and linux-zen packages

### ISSUE THREAD

**Issue by rnz** [archzfs/archzfs#487]
Thanks!

**Comment by HougeLangley** [comment]
https://github.com/openzfs/zfs/issues/14658

**Comment by HougeLangley** [comment]
This bug haven't fix yet.

**Comment by isopix** [comment]
Couldn't you just simply apply those two patches temporarily and release packages in archzfs repo?

**Comment by stevleibelt** [comment]
@isopix with that approach, the archzfs-community would simple loose all benefits of the test-infrastructure the openzfs-people are giving "us" for free.
Furthermore, it would divide the archzfs-openzfs from the original openzfs. I can understand your wishes. Myself has "lost" one pc by upgrading without having a look and now waiting for a fix. But fixing a fix in an unorthodox manner harms more than it solves.

At least this are my 2 cents :-).

**Comment by isopix** [comment]
> @isopix with that approach, the archzfs-community would simple loose all benefits of the test-infrastructure the openzfs-people are giving "us" for free. Furthermore, it would divide the archzfs-openzfs from the original openzfs. I can understand your wishes. Myself has "lost" one pc by upgrading without having a look and now waiting for a fix. But fixing a fix in an unorthodox manner harms more than it solves.
> 
> At least this are my 2 cents :-).

Now, I totally disagree.
I'm not hurting anybody by providing PKGBUILD diff, so anyone can fix it locally already by building packages from PKGBUILD.  (without waiting for your actions[or openzfs] and new packages in archzfs.)

**Comment by RAMChYLD** [comment]
If you use dkms, you can just apply the two patches to the source at /usr/src and run autogen.sh, and then just ask dkms to rebuild and install the modules (—force). The ZFS team already said that a fix will ship with 2.6.10, but there’s no ETA.

**Comment by BlackIkeEagle** [comment]
There is a merged patch for this issue: https://github.com/openzfs/zfs/pull/14668

And the backport for the upcoming 2.1.10: https://github.com/openzfs/zfs/pull/14677

**Comment by leonghui** [comment]
Just reporting here that linux and linux-zen 6.2.9 has been built in the `archzfs-testing` repository and the former works perfectly on my setup. Thanks again @minextu !
```
[me@machine ~]$ uname -a
Linux machine 6.2.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux
[me@machine ~]$ zfs --version
zfs-2.1.9-1
zfs-kmod-2.1.9-1
```

**Comment by minextu** [comment]
It's now in the stable repo, packages are up to date again

**Comment by nnathan** [comment]
I know this was a very frustrating update but I appreciate the patience and diligence placed into creating this update. I was a bit frustrated that I couldn't update my system for a few weeks waiting for upstream to fix things, but I'm glad my system didn't break thanks to the care and consideration placed in this update.

**Comment by stevleibelt** [comment]
@nnathan yes, I guess we all used this case as a friendly reminder that the linux-zfs is a fragile one.
It was good to see that "things are moving" :-).
