### ISSUE TITLE
Oh my gosh Becky, look at that 2.1.10

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#489]
https://github.com/openzfs/zfs/releases/tag/zfs-2.1.10

**Comment by minextu** [comment]
2.1.10 is in stable, 2.1.11 will be in testing in a few moments

**Comment by eirnym** [comment]
@minextu Is 2.1.11 compatible with Linux 6.3 and 6.3? I'm asking here as this repo has additional patches on the top.

**Comment by minextu** [comment]
Patches have been removed since 2.1.10 is compatible with Linux 6.2 now. Linux 6.3 unfortunatly isn't supported yet (https://github.com/openzfs/zfs/issues/14622)
