### ISSUE TITLE
Updates for 6.2.13 kernel

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#491]
Thanks as always

**Comment by tolbkni** [comment]
linux kernel version has been bumped to 6.3.1.arch1-1

**Comment by stevleibelt** [comment]
```bash
Error! Bad return status for module build on kernel: 6.3.1-arch1-1 (x86_64)
```

When I try to build it with `dkms install --no-depmod zfs/2.1.11 -k 6.3.1-arch1-1`.

**Comment by meithan** [comment]
> Doesn't have zfs-dkms a linux kernel version limitation that should prevent me from updating to an unsupported kernel version?

Nope, it does not. It's up to the user to verify for ZFS official support before each kernel upgrade. Each OpenZFS release [clearly states](https://github.com/openzfs/zfs/releases/tag/zfs-2.1.11) the range of supported kernels.

This is even something we were [discussing](https://aur.archlinux.org/packages/zfs-dkms#comment-913807) over the weekend with the `zfs-dkms` AUR package maintainer, but the conclusion is that there's no way to enforce a kernel version requirement or block that would work for all cases.

**Comment by coryschwartz** [comment]
I was caught off guard by this as well. I (incorrectly) assumed the dkms method would just work and I wasn't double checking kernel compatibility.

I assume the reason for not having dependency constraints is that you don't know which kernel is installed, yeah? e.g. you don't know if users have linux or linux-hardened or linux-zen or what have you, not to mention user-compiled kernels.

Assuming this is the reason, seems like it would be great if there were a kernel group package with all kernels, then packages like this could depend on there there being one or more of the supported kernels installed.

I'm not suggesting that the archzfs repo should have this group.

or, maybe the package could require something that the kernel `provides`. e.g. I bet you could depend on WIREGUARD-MODULE<=3.2 and this would probably work regardless of what kernel the user had installed.

I'm not suggesting that the archzfs packages should actually depend on wireguard. Just trying to think of a good way to do this without simply deferring to the user to know about the dependency.

by the way I'm not a kernel packager for archlinux, so I can't do either of these things. Just thinking in public.

**Comment by meithan** [comment]
> I assume the reason for not having dependency constraints is that you don't know which kernel is installed, yeah? e.g. you don't know if users have linux or linux-hardened or linux-zen or what have you, not to mention user-compiled kernels.

Exactly.

> Assuming this is the reason, seems like it would be great if there were a kernel group package with all kernels, then packages like this could depend on there there being one or more of the supported kernels installed.

I don't think that the Arch packaging system allows packages to require *at least one* of a group of packages as dependency.

> or, maybe the package could require something that the kernel `provides`. e.g. I bet you could depend on WIREGUARD-MODULE<=6.2 and this would probably work regardless of what kernel the user had installed. Maybe the various linux packages should provide `LINUX` or `KERNEL` or something

The things is that I'm not sure that different kernels are interchangeable enough to satisfy a common `provides`, in the sense that software built for one kernel is not guaranteed to work with a different one (even if they're based on the same version of the mainline kernel).

Packages closely tied to the kernel usually have multiple alternatives, each one built for and requiring a specific kernel. For instance, there's `nvidia` for the mainline Arch kernel and `nvidia-lts` for the LTS kernel -- if you're using another kernel, such as `linux-zen`, then you need to use the DKMS version, which has no explicit kernel dependency.

But I do agree that a way for DKMS packages to specify kernel versions (when they need to) would be a very good thing.

**Comment by meithan** [comment]
The `zfs-dkms` maintainer (kstolp) was [considering the alternative idea](https://aur.archlinux.org/packages/zfs-dkms#comment-913341) of doing it the other way around: using the `conflicts` directive to list kernel versions that are known to be *incompatible*, at least for the official Arch kernels. The PKGBUILD could have something like `conflicts=('linux>=6.3' 'linux-lts>=6.3' etc)', effectively blocking the kernel upgrade if `zfs-dkms` is installed.

However, [as kstolp points out](https://aur.archlinux.org/packages/zfs-dkms#comment-913722), this could lead to its own problems in complicated situations like the one we're currently facing, so it's not a good solution.

**Comment by stevleibelt** [comment]
So, what would be the best solution? Log the dkms building and revert to a previous kernel if something bad happens?

**Comment by eirnym** [comment]
Upstream just updated META to support for Linux kernel 6.3

**Comment by meithan** [comment]
> Upstream just updated META to support for Linux kernel 6.3

Where? The META files of both the [master](https://github.com/openzfs/zfs/blob/master/META) and the [zfs-2.1.12-staging](https://github.com/openzfs/zfs/blob/zfs-2.1.12-staging/META) branches at OpenZFS still show 6.2.

**Comment by meithan** [comment]
Great news! Now the changes have to be backported and packaged into a 2.1.x (2.1.12?) release, right?

**Comment by eirnym** [comment]
I will be happy with 2.2.0 as well

**Comment by stevleibelt** [comment]
Just for the log and since it took me some time to realize. If it is urgent, `zfs-dksm-git` is working with `6.3.2-arch1`. At least I was able to [build an archiso](https://github.com/stevleibelt/arch-linux-live-cd-iso-with-zfs/releases/tag/2.10.0) with it.

**Comment by minextu** [comment]
See https://github.com/archzfs/archzfs/issues/493
