### ISSUE TITLE
Update for 6.3.1 linux and linux-zen packages

### ISSUE THREAD

**Issue by rnz** [archzfs/archzfs#493]
Thanks!

**Comment by stevleibelt** [comment]
Kernel 6.3 is currently not compatible with OpenZFS.

See [here](https://github.com/archzfs/archzfs/issues/491#issuecomment-1537218169) or [here](https://github.com/openzfs/zfs/issues/14622).

Cheers!

**Comment by NHOrus** [comment]
Now it is, in Master branch of OpenZFS

**Comment by minextu** [comment]
Only -git packages are supported for now. Need to wait for the next zfs release

**Comment by jonas-w** [comment]
@AkechiShiro https://github.com/openzfs/zfs/pull/14896 probably this pull request

**Comment by czAdamV** [comment]
They expect the next 2.1 version (with 6.3 support) to be tagged in a week or two: https://github.com/openzfs/zfs/issues/14927#issuecomment-1577681083

**Comment by minextu** [comment]
2.1.12 is building and will be pushed soon
