### ISSUE TITLE
Update for linux-lts 6.1.35

### ISSUE THREAD

**Issue by TerryGeng** [archzfs/archzfs#497]
Many thanks. The CI is still running but packages were not pushed to AUR.

**Comment by atticus-sullivan** [comment]
Yes, and according to the [CI output](https://ci.archzfs.com/#/builders/4/builds/2463) it's no problem with the code. There is simply not enough space on the device left (iirc this is not the first time we have this problem)

**Comment by minextu** [comment]
Updated
