### ISSUE TITLE
Builds failing in CI

### ISSUE THREAD

**Issue by hrast01** [archzfs/archzfs#498]
Looks like builds failing again due to disk space, most recent [2489](https://ci.archzfs.com/#/builders/4/builds/2489).

**Comment by travishegner** [comment]
Hi, to work around this issue while CI is failing, I wrote a container based build process that could be useful so that you aren't blocked doing upgrades: https://github.com/travishegner/buildzfs

**Comment by minextu** [comment]
Builds are working again, will move everything to a new server soon to stop these issues in the future

**Comment by prikhi** [comment]
Hiya we're outta disk space again :sob:

**Comment by minextu** [comment]
Thx fixed :)
