### ISSUE TITLE
Updates for linux and linux-zen pkg

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#499]
Production seems to be for 6.4.5 now. Thanks!

**Comment by ilyxa** [comment]
https://ci.archzfs.com/#/builders/6/builds/2189

rsync: write failed on "/var/www/html/archive_archzfs-testing/zfs-dkms-git-2023.07.13.r8673.g6db781d52c-1-x86_64.pkg.tar.zst": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(374) [receiver=3.1.3]

Build seems OK, but no space left.

**Comment by jrudess** [comment]
Is there anything we can do to assist in these releases?  Would having someone else assisting in the infrastructure or helping fund upgrades be useful?

**Comment by jbrodriguez** [comment]
at the moment, @minextu hasn't been active in github for the past 2 months, not sure if he's the only archzfs maintainer ?

**Comment by minextu** [comment]
Sorry had a rough time recently, packages are up to date again

**Comment by stevleibelt** [comment]
> Sorry had a rough time recently, packages are up to date again

Ping me if you thing support would be welcome and is doable. I don't like it when things I rely on are shouldered by a one-man-army :-).
