### ISSUE TITLE
zfs-dkms can not be build against kernels >= 6.5.2

### ISSUE THREAD

**Issue by stevleibelt** [archzfs/archzfs#503]
I hope this ticket is not creating to much noise.

I just want to put it in here since the aur package maintainer has created a [pinned message](https://aur.archlinux.org/packages/zfs-dkms#comment-932924) for this issue.

If I update my linux kernel to >= 6.5.2, I get the following error when I want to build the dkms-

> Error! Bad return status for module build on kernel: 6.5.2-arch1-1 (x86_64)

Maybe [this](https://github.com/openzfs/zfs/pull/15265) is the pull request on the openzfs-side we all are waiting for.

Until then, I recommend all to not upgrade your linux kernel on your arch machines.

Best regards and thanks for your work so far,
Stev

**Comment by ipha** [comment]
2.1.13 is being worked on with 6.5 compat: https://github.com/openzfs/zfs/pull/15268
