### ISSUE TITLE
Wow zfs 2.2.0 has some great new features!

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#509]
Like reflinks, scrub logs, targeted scrub, corrective receive and zstd early abort!

https://github.com/openzfs/zfs/releases/tag/zfs-2.2.0

**Comment by fryfrog** [comment]
Is it weird this merged ~3 hours ago, but still hasn't made it out? I feel like previous bumps trickled through faster.

**Comment by minextu** [comment]
It was in the testing repo for a bit, now deployed to the regular repo
