### ISSUE TITLE
The boot.loader.grub.zfsSupport property is ignored.

### ISSUE THREAD

**Issue by msteen** [archzfs/archzfs#51]
When I updated my nixpkgs repo to the latest version of the 15.09 channel, I saw that zfs-user was being build even though I do not use ZFS. I checked all-packages.nix and grub.nix and found the defaults no longer match the assumptions made in grub.nix.

Currently all-packages.nix contains the following:

    grub2 = grub2_full;

    grub2_full = callPackage ../tools/misc/grub/2.0x.nix { };

    grub2_efi = grub2_full.override {
      efiSupport = true;
    };

    grub2_light = grub2_full.override {
      zfsSupport = false;
    };

While grub.nix still has the following:

    realGrub = if cfg.version == 1 then pkgs.grub
      else if cfg.zfsSupport then pkgs.grub2.override { zfsSupport = true; }
      else if cfg.enableTrustedBoot then pkgs.trustedGrub
             else pkgs.grub2;

Since `pkgs.grub2` is defined as `grub2_full`, which has `zfsSupport ? true`, there currently is no difference between `pkgs.grub2.override { zfsSupport = true; }` and `pkgs.grub2`. I do not see the need for `grub_full`, `grub_efi` and `grub_light`. Would it not be better to keep things configurable the way they are using options such as `boot.loader.grub.zfsSupport`?

**Comment by bjin** [comment]
This repo is for Arch Linux, not NixOS I believe.

**Comment by msteen** [comment]
Whoops, my bad, I must have ended up here by doing a global github.com search instead of a local NixOS search and then pressing new issue. Apologies.
