### ISSUE TITLE
Golly gee, zfs 2.2.1 is out!

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#516]
What a twist, [2.2.1](https://github.com/openzfs/zfs/releases/tag/zfs-2.2.1) is out w/ 6.6 support and a number of other fixes.

**Comment by fryfrog** [comment]
Already being worked on in https://github.com/archzfs/archzfs/pull/515, yay!

**Comment by OrdinaryMagician** [comment]
That data corruption bug worries me, hope a 2.2.1 package is out soon.

**Comment by minextu** [comment]
Updated!
