### ISSUE TITLE
Module zfs not found for linux-vfio

### ISSUE THREAD

**Issue by tirrorex** [archzfs/archzfs#52]
Hello, i have a strange behaviour here, i installed the package with pacman -Sy zfs after adding the repo, installing packages 1-3.
I use linux-vfio kernel from AUR.
Couldn't load zfs so i tried to /sbin/modprobe/zfs but it tells me it cannot find the module in /lib/modules/4.4.5-1-vfio
Also i can reinstall the pacman (still with pacman -S zfs) but i cannot remove it ? Tells me package zfs was not found.
Pretty sure i did something wrong during the install but i don't know what, this is my first arch install so...

Anyway, any lead on solving this would be welcome, all my datas are on my former fedora zfs raid so i don't have any datas atm, have a good day

**Comment by tirrorex** [comment]
Figured the removal, was -R zfs-git, was a bit tired sorry...
Just need to figure out how to build the package for me

**Comment by demizer** [comment]
The ZFS packages have the path to the kernel module hardcoded (set by upstream). I have supported the default kernel packages but not anything else. This will be changing in the next few weeks.

Relate to #28

**Comment by tirrorex** [comment]
I noticed that in the pkgbuild after a while.
The thing is, even if you do support other kernels i assume i will have to rebuild every time i switch?
If so i will stick with zfs-dkms. have a good day.

**Comment by demizer** [comment]
We will be adding dkms to archzfs project soon hopefully. Thanks!

**Comment by tirrorex** [comment]
That is indeed a great news ! Thanks for the headsup :)
