### ISSUE TITLE
zfs-dkms patch needed for kernel 6.7 series

### ISSUE THREAD

**Issue by reaperx7** [archzfs/archzfs#523]
ZFS 2.2.2 needs patch for kernel 6.7 as detailed here:

https://github.com/openzfs/zfs/pull/15681

**Comment by WonderMr** [comment]
duplicate issue https://github.com/openzfs/zfs/issues/15759

**Comment by RAMChYLD** [comment]
Is the patch integrated yet? This is holding my system back from receiving kernel 6.7...

**Comment by reaperx7** [comment]
Not that I'm aware of. Change kernel to lts for the time being until 2.2.3 is released to be safe.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by minextu** [comment]
6.7 patch added and pushed to stable
