### ISSUE TITLE
touch set's atime to 1970

### ISSUE THREAD

**Issue by 1-2-3-Man** [archzfs/archzfs#524]
At least `touch` set's atime of files to 1970-01-01 00:00 with zfs-dkms-2.2.2-2. With cat, less, vim, more atime is set correctly. This might be related to upstream [#15773](https://github.com/openzfs/zfs/pull/15773).

To reproduce `touch` any file, existent or non-existent, and look at atime.

This seems to happen regardless of atime and relatime setting of the dataset.

**Comment by minextu** [comment]
Thx for reporting, must have missed this commit when adding the patch for linux 6.7. Added the patch for this with https://github.com/archzfs/archzfs/commit/7a8622786f5081c9edc0d718b8736ad079561d88 and pushed to stable.
