### ISSUE TITLE
Support bootfs child datasets (Patch)

### ISSUE THREAD

**Issue by rwanyoike** [archzfs/archzfs#53]
Currently only the dataset defined by the `zfs` kernel parameter will get mounted during boot. For example (`zfs=bootfs`):

``` 
$ zfs list -o name,mountpoint
NAME               MOUNTPOINT
zroot              /            # (bootfs)
zroot/home         /home
zroot/usr          legacy
zroot/var          legacy
```

The other datasets will wait until the `zfs.target` systemd service is called (IF it is enabled). A dataset like `zroot/usr` will cause the kernel to complain that it can't find `/sbin/init` (`/sbin -> /usr/bin`).

Similar issue: #22

---

These changes try to mount any *children*, with the dataset defined by the `zfs` kernel parameter. For example (`zfs=bootfs`):

```
$ zfs list -o name,mountpoint
NAME               MOUNTPOINT   
zroot/root         /            # (bootfs)
zroot/root/usr     legacy       # will get mounted (child)
zroot/root/var     legacy       # will get mounted (child)
zroot/scratch      none         # will not get mounted
zroot/home         /home        # will not get mounted
```

Legacy mountpoints get mounted if they are listed in /etc/fstab. :+1:

**Comment by rwanyoike** [comment]
As per the submitting changes (https://github.com/archzfs/archzfs/tree/495964c#submitting-changes):

[child_datasets_1-3.txt](https://github.com/archzfs/archzfs/files/209316/child_datasets_1-3.txt) - [PATCH] Mount the root, and any non legacy child datasets
[child_datasets_2-3.txt](https://github.com/archzfs/archzfs/files/209317/child_datasets_2-3.txt) - [PATCH] Mount the root, and any child datasets
[child_datasets_3-3.txt](https://github.com/archzfs/archzfs/files/209318/child_datasets_3-3.txt) - [PATCH] Avoid absolute paths in hook

**Comment by demizer** [comment]
Awesome. Thank you!

**Comment by ajs124** [comment]
Why has this not been merged yet? My system does not boot without this patchset.

**Comment by demizer** [comment]
@ajs124 because time

But tonight's the night.
