### ISSUE TITLE
Release of zfs-2.2.4, yay!

### ISSUE THREAD

**Issue by fryfrog** [archzfs/archzfs#532]
Looks like they finally got us some 2.2.4! :)

https://github.com/openzfs/zfs/releases/tag/zfs-2.2.4

**Comment by gentoosys** [comment]
Please make a new zfs-dkms package asap, I am waiting for it to upgrade my kernel to 6.8

**Comment by fryfrog** [comment]
You don't need to hold off for that, they've pulled in the patches to work on 6.8 already. This may even be a noop because of that.

```
fryfrog@apollo ~  ❯ uname -a
Linux apollo 6.8.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 02 May 2024 17:49:46 +0000 x86_64 GNU/Linux
fryfrog@apollo ~  ❯ zfs --version
zfs-2.2.3-1
zfs-kmod-2.2.3-1
```

**Comment by gentoosys** [comment]
Hi @fryfrog 
I have a question. I am building kernel myself using linux-tkg scripts. I am using only versions, compatible with zfs release (right now 6.8) and update kernel version only after new zfs release. Is it right? or I can build newer kernel versions and zfs-master? Please advice

**Comment by stevleibelt** [comment]
The question of @gentoosys should be moved into a dedicated issue ticket labeled as question or something. There is no direct connection to the zfs-2.2.4 release.
