### ISSUE TITLE
What is `enforce-kernel-max-version.patch` for?

### ISSUE THREAD

**Issue by robn** [archzfs/archzfs#534]
I notice that you have `enforce-kernel-max-version.patch`, apparently chasing openzfs/zfs#15986, of which I am the author.

Leaving aside the fact that that PR is still being discussed, I was wondering why you even needed that patch? You don't appear to be using the configure option that it adds, so it literally does nothing for you. But maybe there's a use case that I'm not seeing.

I was prompted to ask after seeing #533, which takes the "latest" patch from openzfs/zfs#15986. That one actually is subtly different, and is active by default, so I wanted to make sure you know what you're doing, and that there's not some subtle impact that I'm not aware of.

**Comment by SoongNoonien** [comment]
I took it from https://patch-diff.githubusercontent.com/raw/openzfs/zfs/pull/15986.patch. Did I make a mistake there? Where is the subtle difference? I don't actually know what we are doing here... I'm not a friend of downstream patching anyways... I simply updated the patch while bumping the version in #533 as you mentioned. So you mean we can safely drop it? Maybe @minextu knows what it originally was supposed to do he added it in 18e617c824ad4b3c40eb89b087b0d46f1fdf0647?

**Comment by minextu** [comment]
@robn Thank you for the heads up! You are right, I added this patch without the configure option, which makes it inactive. I shouldn't have added it like that

@SoongNoonien Thank you for the PR, you didn't do anything wrong, updating it was a good idea. Let's remove it for now though, until that patch is actually getting merged

**Comment by SoongNoonien** [comment]
Ok, I've updated the PR accordingly.
