### ISSUE TITLE
CI build failed with google dns server error

### ISSUE THREAD

**Issue by geekifan** [archzfs/archzfs#536]
Hello guys!

I find that the archzfs repo hasn't been updated for nearly 10 days. The packages in the repo have failed to keep up-to-date with the archlinux official kernel (skipped 6.9.1.arch1-2 and 6.9.2.arch1-1). The error message on `ci.archzfs.com` shows that the ci server cannot reach the google dns server.

Here is the error message:

<img width="2100" alt="image" src="https://github.com/archzfs/archzfs/assets/74950140/9fcbaec7-b81f-4117-92b7-81f0756dc978">

**Comment by minextu** [comment]
Yeah this started happening recently, it is not related to google DNS or anything. The issue seems to be that docker runs out of allocations for new processes or something similar to that. 
I didn't investigate it that much, just started restarting the container and it works again for a few days.

**Comment by geekifan** [comment]
Thanks for your reply and nice work! The repo is up-to-date again. If I catch any other errors like this again, I will report them here.

**Comment by geekifan** [comment]
Another problem happened. The repo is not up-to-date again.

<img width="2056" alt="image" src="https://github.com/archzfs/archzfs/assets/74950140/35d89164-8303-40b9-bd75-962bb7ef0eac">

**Comment by pswiatki** [comment]
This current issue is different from the one reported originally, Correct?
Why did you not create a separate issue for this?  By the way: as far as I can see, the db file is corrupted (only 12 bytes long). Perhaps related to #537?
