### ISSUE TITLE
Invalid or corrupted archzfs-testing.db (Lzma library error:  No progress is possible)

### ISSUE THREAD

**Issue by leonghui** [archzfs/archzfs#537]
pacman and paru are reporting the error above
```
:: Synchronizing package databases...
 archzfs-testing is up to date
 core is up to date
 extra is up to date
 multilib is up to date
:: Starting full system upgrade...
error: could not open file /var/lib/pacman/sync/archzfs-testing.db: Lzma library error:  No progress is possible
error: failed to prepare transaction (invalid or corrupted database)
```

Might be related to these errors in this build step: https://ci.archzfs.com/#/builders/6/builds/2396 
```
==> Creating updated database file '/repo/archzfs-testing/x86_64/archzfs-testing.db.tar.xz'
xz: (stdin): Cannot allocate memory
bsdtar: Write error
==> Signing database 'archzfs-testing.db.tar.xz'...
  -> Created signature file 'archzfs-testing.db.tar.xz.sig'
xz: (stdin): Cannot allocate memory
bsdtar: Write error
==> Signing database 'archzfs-testing.files.tar.xz'...
  -> Created signature file 'archzfs-testing.files.tar.xz.sig'
```

**Comment by jbrodriguez** [comment]
is this issue solvable ? 

i can't upgrade my archlinux server because of this

is there any source of zfs for archlinux that is tied to the linux kernel ?

**Comment by leonghui** [comment]
In the meantime, I switched back to the `archzfs` repository in `pacman.conf` to unblock upgrades for other packages. On my servers with linux-lts, the latest zfs-linux-lts package in the `archzfs` repo is in sync (6.6.32-1).

**Comment by jbrodriguez** [comment]
thank you ! i think i will have to switch to lts 😔

**Comment by jbrodriguez** [comment]
mmm, actually this is the repo i have on my pacman.conf

```ini
[archzfs]
Server = https://archzfs.com/$repo/$arch
```

so to make it work, i actually need to switch to linux-lts instead of linux right ?

do you know if this is a seamless process? linux -> linux-lts (i'd guess not 😔) ?

**Comment by leonghui** [comment]
I think we are going off topic but discussions are not enabled for this project in GitHub. Anyway:

As you can see from [here](https://archzfs.com/archzfs/x86_64/), the latest `linux` kernel found in the repo is 6.9.2 but core repo right now has 6.9.3.

Depending on your config, `linux` and `linux-lts` can be installed concurrently but switching between them might not be seamless (e.g. other drivers that target specific kernel/version like `nvidia`, bootloader needs to be updated, remaining space in the EFI partition, etc.).

You might not need to switch to `linux-lts` if you are confortable doing a partial upgrade (i.e. download the package for linux 6.9.2 from Arch Linux Archive and upgrade it separately from the rest of your packages) but you might already know that this is an [unsupported config](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported).

**Comment by jbrodriguez** [comment]
thank you @leonghui, i'll investigate a bit more 🙏

**Comment by jbrodriguez** [comment]
looks like the ci/cd pipeline is somewhat brittle with the ci.archzfs.com buildbot (resources from what i've  seen in the past), not sure if these errors are related to that, but maybe this build process could be migrated to github ? i don't think it would exceed the free tier limits 🤷‍♂️

**Comment by pswiatki** [comment]
It definitely looks like the db file is corrupted. Check this:
```
/archlinux/archzfs/archzfs/x86_64/archzfs.db                     28-May-2024 20:57          8588
                                                                                           ^^^^^
```
but
```
/archlinux/archzfs/archzfs-testing/x86_64/archzfs-testing.db     30-May-2024 03:15              12
                                                                      12 bytes?? ------------^^^^^
```

**Comment by jbrodriguez** [comment]
i went with a partial upgrade (sudo pacman -Syu --ignore ...), as a stop gap solution 🤷‍♂️

**Comment by pswiatki** [comment]
Does it mean ZFS became dysfunctional on your machine?

**Comment by jbrodriguez** [comment]
no, zfs is still working, only i chose to ignore upgrades to linux kernel and zfs

this partial upgrade scenario is not supported, because archlinux is designed to be an all or nothing upgrade, so if enough time passes, some packages that have been upgraded might break, because they've only been tested with a newer kernel

this is stop gap measure for me, i hadn't updated my system in a month and a half, so had a lot of upgrades pending

i'm considering switching out of archlinux, a rolling release is very enticing, but sometimes these kind of things happen, i used ubuntu in the past, but the upgrade to major versions was always painful

```bash
❯ sudo checkupdates
[sudo] password for <redacted>:
linux 6.8.8.arch1-1 -> 6.9.4.arch1-1
linux-api-headers 6.7-1 -> 6.8-1
zfs-linux 2.2.3_6.8.8.arch1.1-1 -> 2.2.4_6.9.2.arch1.1-1
zfs-utils 2.2.3-1 -> 2.2.4-1
```

**Comment by pswiatki** [comment]
Got it. Thank you very much for your response. 
ZFS is a bit behind the kernel updates, but this time something happened and ZFS got stuck, I think.
I wonder is such Partial Update can fail here or there in unpredictable ways. But keep my fingers crossed. 
Since I don't use ZFS extensively (yet!) I decided to remove `zfs-linux` and proceed with the normal update.
We'll see how long we have to wait before ZFS catches up.

**Comment by jbrodriguez** [comment]
about an hour ago, the buildbot successfully pushed a fresh release !!!

i'm still wondering though, maybe i should switch to linux-lts, not sure if that would diminish the probability of something like this happening 🤷‍♂️

**Comment by pswiatki** [comment]
> ZFS is naturally a bit behind the kernel updates,

It is an unusual delay this time. Quite unfortunate, for me, too.

**Comment by minextu** [comment]
Sorry about the delay, I don't have much time to spend on this, so when something goes wrong it can sometimes take me a while to get to the bottom of it

**Comment by pswiatki** [comment]
It is all OK, @minextu. If I may ask: I now have:

```
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing linux (6.9.6.arch1-1) breaks dependency 'linux=6.9.5.arch1-1' required by zfs-linux
```
and I can see `6.9.6.arch1-1` is in [archzfs-testing](https://archzfs.com/archzfs-testing/x86_64/) as of today, June the 24-th.
What is the usual turnaround before it ends up in [archzfs](https://archzfs.com/archzfs/x86_64/)?

**Comment by leonghui** [comment]
@pswiatki based on the timestamps `6.9.6.arch1-1` is in `archzfs` after 10 hours.

I am inclined to close this issue since it appears to be a transient condition with the CI workers (`Cannot allocate memory`) and has resolved itself otherwise.

There is a [workaround](https://github.com/archzfs/archzfs/issues/537#issuecomment-2170595275) in case it happens again.

**Comment by pswiatki** [comment]
Yes, of course. I just was curious how long is a wait between testing branch and official. That's all.

Now that I know, I am spent 😁.

**Comment by pswiatki** [comment]
> i'm considering switching out of archlinux, a rolling release is very enticing, but sometimes these kind of things happen, i used ubuntu in the past, but the upgrade to major versions was always painful

I have been using Arch for 10+ years and never had an issue (apart from things like this, or self-induced no-boot situations). However, I was able to recover relatively easily. So, I am pleased with Arch.
