### ISSUE TITLE
ci.archzfs.com down

### ISSUE THREAD

**Issue by jbrodriguez** [archzfs/archzfs#540]
![Screenshot 2024-07-20 at 09 47 49](https://github.com/user-attachments/assets/81eb733b-f007-4e6d-bd48-d629a4a14517)

**Comment by jbrodriguez** [comment]
so, i was facing a very dreadful situation
- reinstalled archlinux
- switched to linux-lts
- tried to install zfs-linux-lts only to encounter it flagged out of date ~ week ago
![Screenshot 2024-07-20 at 10 08 08](https://github.com/user-attachments/assets/2eb56e09-36af-4f90-9e8d-6d03704cfdd2)
- ci.archzfs.com is down (not sure if it would have made a difference)

my solution:
- build my own zfs 🤷‍♂️

THANK YOU to this guy
https://aur.archlinux.org/packages/zfs-linux-lts#comment-948394

i installed base-devel, then followed the (few) steps and voila

```bash
❯ sudo pacman -Q | grep 6.6.40
linux-lts 6.6.40-1
zfs-linux-lts 2.2.4_6.6.40.1-1
zfs-linux-lts-headers 2.2.4_6.6.40.1-1

❯ uname -r
6.6.40-1-lts
```

at this point, i wonder how to navigate the next kernel upgrade (assuming archzfs is still out of date), i'm thinking i will:
- sudo pacman -Syu --ignore zfs-linux-lts zfs-linux-lts-headers zfs-utils
- pull latest zfs-linux-lts
- makepkg again

hope that works

**Comment by n0xena** [comment]
here's my way:
using YAY as AUR-helper
when a new kernel is released it fails due to unresolvable dependencies
building archzfs myself (although a bit differently - using the way explained in the wiki of this repo)
install the new zfs with yay -Qd and then do the regular system update with yay -Syu
reboot

**Comment by kotauskas** [comment]
Note that you can also use the Arch Linux Archive to get the most recent Linux kernel compatible with the version of ZFS that ArchZFS is currently shipping:
```sh
# Assuming you have the ArchZFS repo in pacman.conf:
pacman -Ss '^zfs-linux-lts$'
# Take note of the Linux kernel version – it follows the underscore in the ZFS module's version number
# Now browse the Arch Linux Archive (it's easy enough thanks to directory listings) and find the desired
# kernel package version; `/packages/l/linux-lts` is the starting point for LTS, but the process is analogous
# for other kernels in Arch core
curl --tlsv1.3 -o linux-lts.pkg.tar.zst \
  'https://archive.archlinux.org/packages/l/linux-lts/linux-lts-6.6.36-1-x86_64.pkg.tar.zst'
sudo pacman -U linux-lts.pkg.tar.zst
sudo pacman -S zfs-linux-lts
```
No recompilation needed.

**Comment by endreszabo** [comment]
.. or you could be using my kernel repositories that point to the 'most recent Linux kernel compatible with the version of ZFS that ArchZFS is currently shipping'

"If you happen miss to upgrade a more recent OpenZFS supported version, and the latest stable is ahead of the OpenZFS supported one, there's a solution to upgrade to the latest OpenZFS supported kernel without digging up the matching kernel packages from Arch Linux Archive."

https://end.re/blog/ebp036_archzfs-repo-for-kernels/#update-on-2020-12-17

This way you don't have to deal with ALA or archive.org or any package mumbo-jumbo manually. :)

**Comment by jbrodriguez** [comment]
@kotauskas 

> ```shell
> pacman -Ss '^zfs-linux-lts$'
> ```

ty, but this still returns an older version of zfs vs the current linux kernel 
```
╰─❯ sudo pacman -Ss '^zfs-linux-lts$'
[sudo] password for root:
archzfs/zfs-linux-lts 2.2.4_6.6.36.1-1 (archzfs-linux-lts) [installed: 2.2.4_6.6.40.1-1]
    Kernel modules for the Zettabyte File System.
```

**Comment by kotauskas** [comment]
`pacman -Ss '^zfs-linux-lts$'` is a search command. You don't need `sudo` to run it, it's simply there to tell you what version of `linux-lts` ArchZFS's `zfs-linux-lts` has most recently been built for. This allows you to then match the kernel version to that of the ZFS module, as opposed to matching the version of the ZFS module to that of the most recent available kernel, which is what you've achieved by recompiling it.

I do agree that the kernels.archzfs.com repo is a hell of a lot neater than browsing ALA manually, though. Thanks @endreszabo!

**Comment by jbrodriguez** [comment]
ty for the explanation @kotauskas, i will read more about this in the post by endreszabo

**Comment by jbrodriguez** [comment]
@endreszabo i had the opportunity to read the blog post 

if i understand correctly, in my scenario
- linux kernel 4.6.6.40
- zfs 4.6.6.36

by following your process, it would allow me to do a `pacman -Syu`, pinning the kernel version to what zfs depends on (by hinting the version on the command line)

if that's the case, wouldn't that leave me in a partial upgrade scenario ? kernel in a lower version than the rest of the packages expect/archlinux supports ?

**Comment by kotauskas** [comment]
The kernel is a somewhat special exception to the general "partial upgrades are bad" rule, since it guarantees ABI stability, and also because it's virtually impossible that the software Arch Linux packages adopts new Linux features faster than OpenZFS gets updated to compile with the new kernel.

Think of it this way: if being in a partial upgrade where the kernel is the only stale package was a problem, the `linux-lts` package wouldn't exist to start with.

**Comment by jbrodriguez** [comment]
i see

> Think of it this way: if being in a partial upgrade where the kernel is the only stale package was a problem, the `linux-lts` package wouldn't exist to start with.

i see, that makes sense

so, endreszabo approach is to basically pin zfs at the current version and look for the matching kernel in kernel.archzfs.com

why not --ignore linux-lts,etc ? 

the only reason (i can think of) not to, is that both the kernel and zfs have newer versions than what's installed on the system

i don't have enough experience to visualize a scenario where openzfs/archzfs is ahead of the kernel ?

also, once openzfs releases a new version, it automatically supports all kernel versions (for which it has declared support) or not really ? based on this picture, i understand it should
![Screenshot 2024-07-23 at 16 29 27](https://github.com/user-attachments/assets/4cdf1d38-6c6c-45af-88af-0a56c934e075)

i see 2 levels of (unavoidable) delay
- openzfs delay on supporting a new "major" kernel
- archzfs delay on building a package for the latest openzfs

**Comment by jbrodriguez** [comment]
today i failed to upgrade to linux-lts 41, the zfs build  i depicted above doesn't work, it still needs a matching kernel
i managed to get it working though via mkarchroot, makechrootpkg
however that still requires installing base-devel and devtools, so i found my endgame
a docker to build zfs-linux-lts
i'll write a blog post and put a link here
it's been a journey :)

**Comment by prikhi** [comment]
Site is back but builds are broken w/ disk space error:

> /bin/sh: line 1: /build/zfs-linux-git/src/zfs/module/zfs/.zil.o.cmd: No space left on device

https://ci.archzfs.com/#/builders/7/builds/2660/steps/1/logs/stdio

**Comment by jbrodriguez** [comment]
finally came around to writing the post on different ways to update zfs on archlinux, [check it out](https://jbrio.net/posts/5-ways-archlinux-zfs/)

**Comment by minextu** [comment]
All packages  have been updated and pushed to the old stable repository as well as the new experimental one
