### ISSUE TITLE
Using zfs-dkms wuth archzfs

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#544]
I was using zfs-linux-lts, and since package updates stopped being provided I switched to zfs-dkms (aur). When I attempt to remove the archzfs repo into problems compiling the most recent version of zfs-utils .2.5(aur). But if I use the archzfs zfs-utils with zfs-dkms (aur) i'm able to successfully update. Is there a concern mixing these packages?

**Comment by fryfrog** [comment]
I would figure out your zfs-utils aur issue, maybe post on that package for help?
