### ISSUE TITLE
Zpool corruption with 6.10.6 and zfs-dkms

### ISSUE THREAD

**Issue by reaperx7** [archzfs/archzfs#547]
Had a major corruption issue with a kernel panic and libcap-ng which caused my zpool to completely corrupt after a forced spontaneous export.

Not sure why or how it happened, but I lost an entire test rig installation, nothing of value lost mind you, but the entire zfs root was spontaneously exported and I wasn't able to recover it even with a zfs enabled boot media.

Tried to reinitialize the zpool but it said no zpool existed named "zroot" which was the name.

If you're on 6.10.5 or later, make sure you rebuild the dkms or even the AUR dkms-git if any core libraries update to be safe.

Secondary clone system was luckily offline at the time and updated to 6.10.6 and dkms-git was rebuilt and tested for 4 hours with reboots and benchmark usage.

Be careful with this one... The kernel and core libraries are not being nice.

**Comment by soi1uhtgnei2urtonwe4u** [comment]
Ty for info, but this is kinda expected as v2.2.4 officially supports only [Linux 6.8](https://github.com/openzfs/zfs/releases/tag/zfs-2.2.4). 

I guess a dkms build doesn't limit the user which Linux version is the maximum allowed to be installed on. Seeing what problems people get using `archzfs-dkms`, which allows them to install openzfs on newer, unsupported Linux versions, I think I'm going to switch away from `archzfs-dkms` and use `archzfs-linux` as it supposedly contains a version check: The [wiki](https://github.com/archzfs/archzfs/wiki) implies that to mitigate installing openzfs on not officially supported Linux versions, one has to use `archzfs-linux`: 

> While this is the best option for most people, occasionally the OpenZFS project gets behind on stable support for the latest Linux Kernel release. This means that if Linux 4.15 is released to core, but the latest stable release of OpenZFS does not support Linux 4.15, **it is not possible to perform a system update**.

And if you don't want to wait for openzfs to catch up to arch's latest Linux version, use arch' `linux-lts` and `archzfs-linux-lts`. This is the most stable option, but yes, I get it, using LTS kernel on arch.. .

**Comment by n0xena** [comment]
as you use dkms - do you use zfs-2.2.4? if so please update both the issue title and the first post to reflect this
if you use standard kernel I provide working packages over on my fork https://github.com/n0xena/archzfs/releases

**Comment by n0xena** [comment]
does this still happen to you? otherwise request for closed as outdated
