### ISSUE TITLE
spl-utils-linux package overwrites /etc/hostid

### ISSUE THREAD

**Issue by alaricljs** [archzfs/archzfs#60]
Is there a good reason for this?  I have a hypervisor running ZFS for itself and VM root disks.  One of those VMs runs ZFS for a large storage area.  I just rebooted the whole thing and now have the large storage area double imported (once to HV, once to storage VM), this is bad.

My understanding is that the hostid should be unique as it is in Solaris where it's a hardware based identifier.  My recommendation would be to derive it from the MAC address of the first network interface.  Even a random generation routine would be better than the same hostid across all of Arch Linux.

**Comment by demizer** [comment]
It's been a few years since I last looked at hostid, but I think you're right. I will change it to use a random number instead using:

```dd if=/dev/urandom of=/etc/hostid bs=4 count=1```

From https://github.com/zfsonlinux/zfs/issues/2927#issuecomment-64131512
