### ISSUE TITLE
zpool must be manually imported after update

### ISSUE THREAD

**Issue by foafron** [archzfs/archzfs#61]
After updating to Linux kernel 4.6.1-2 and zfs-linux-git version 0.6.5_r304_gf74b821_4.6.1_2-1 I have to manually issue 'zpool import <pool>'  on each reboot in order to have access to the zpool.

**Comment by geigi** [comment]
I have the same issue. Manual import is necessary after each boot, setting the cache file again didn't fix the issue. After a downgrade to the older kernel and zfs the auto import worked again.

**Comment by johnramsden** [comment]
I'm having a similar problem, any of my datasets that are manage by zfs are not automatically imported on boot. Before the update everything was working fine.

**Comment by demizer** [comment]
Work is in progress to setup a regression test for this. Thanks.

**Comment by johnramsden** [comment]
I'm not sure if this is helpful at all but switching to zfs-linux has removed the problem of the datasets not being automatically mounted, so it seems to be a bug that is present in the git version but not the zfs-linux release.

**Comment by foafron** [comment]
Hello,
I got my zpools to mount automatically after looking on the zfsonlinux github pages.  Specifically, the commit on this page -> [https://github.com/zfsonlinux/zfs/commit/92547bc45ca9a2114662d9343ae53e5098acb627](https://github.com/zfsonlinux/zfs/commit/92547bc45ca9a2114662d9343ae53e5098acb627)

The file that caught my eye was /etc/systemd/system/50-zfs.preset.in file because currently on my system I don't have a 50-zfs.preset file.  Once I enable/disabled the various systems listed the to match the contents of that file, things started mounting automatically again.

I hope this is helpful.

Thanks for all your hard work demizer!

**Comment by storrgie** [comment]
@foafron could you elaborate a bit further? 'various systems listed' doesn't help me out much.

Also, are you using dm-crypt by chance?

**Comment by foafron** [comment]
@storrgie Sorry, that was a little bit of a typo.  I was referring to enabling or disabling the various systemd services related to zfs according to what the 50-zfs.preset file has them set to.

No, I'm not using dm-crypt.

**Comment by storrgie** [comment]
For me, all I had to do was `systemctl enable zfs.target`. I am using dm-cryypt as well.

**Comment by foafron** [comment]
I guess I do have 50-zfs.preset on my local system.  @storrgie that is what used to work for me as well until this release.  It is kind of like my system did not use the preset file to make sure that the other services were properly enabled and disabled.

**Comment by dmp1ce** [comment]
I had to set my cachefile and enable zfs-import-cache and zfs-mount in order for my pool to be mounted at boot.

Here is my post to try and help others with similar problem on the BBS. https://bbs.archlinux.org/viewtopic.php?pid=1643619#p1643619

**Comment by demizer** [comment]
0.6.5.8 may have improved handling in systemd for this. Let me know otherwise.

**Comment by z3ntu** [comment]
I had the same problem until I enabled all the services.
