### ISSUE TITLE
Created initrd is missing libgcc_s.so.1

### ISSUE THREAD

**Issue by d3zd3z** [archzfs/archzfs#64]
Upon upgrading to 0.6.5_r403_ge35c5a8_4.7.0_1-1 of zfs-linux-git, my system fails to boot, with a message:
```
libgcc_s.so.1 must be installed for pthread_cancel to work
```
and the zpool command then aborts. I get similar behavior if I try to manually import the pool from the initrd shell.

I was able to work around this by copying libgcc_s.so.1 into /usr/lib within the initrd, and now the system boots.

**Comment by sdukhovni** [comment]
I had the same issue; I couldn't boot until I modified my initrd by hand to include libgcc_s.so.1.

**Comment by d3zd3z** [comment]
I was able to add the following to `/etc/mkinitcpio.conf` to make this work:
```
FILES="/usr/lib/libgcc_s.so.1"
```
so that the file is included in image generation.
