### ISSUE TITLE
Support for newest LTS kernel (4.4.19)

### ISSUE THREAD

**Issue by hrast01** [archzfs/archzfs#66]
New LTS kernel in Core, 4.4.19-1...

**Comment by demizer** [comment]
Hi guys, just got back from Vacation on Tuesday. I've been catching up with work and other things. Hopefully I will get to this today or tomorrow.

**Comment by hrast01** [comment]
Appreciate all your work on maintaining ZFS packaging for the various Arch kernels...

**Comment by storrgie** [comment]
Agree, I'm using it on a bunch of systems and truly love that you're enabling our work.

**Comment by tihsamikah** [comment]
yep agree too @demizer - awesome work and appreciated by loads of people around the world.

if you have a beer fund I would happily donate :)

**Comment by storrgie** [comment]
I'd encourage @demizer to consider some form of donation system for those of us that don't have the time/skills, but do want to financially support his work.

**Comment by foafron** [comment]
Also agree. Thanks you very much :)

**Comment by demizer** [comment]
Awww thanks everyone!
