### ISSUE TITLE
Support for linux-zen kernel

### ISSUE THREAD

**Issue by marcelkorpel** [archzfs/archzfs#67]
As linux-zen is in [extra], it would be nice to have kernel modules for it in archzfs.

I'm willing to experiment with a PKGBUILD derived from zfs-linux-git in AUR within a few days.

**Comment by demizer** [comment]
I could write up some documentation on how to do this. Once we have it working I will put together some automated tests to make sure it works as a boot fs.

**Comment by justrobd** [comment]
Hey demizer I would love to help. I just need to know where to get started. I been meaning to build the linux-vfio with zfs myself but, I have some spare time now to help out with testing. Like I said point me in the direction to get started and I will help out. Thanks!

**Comment by hexchain** [comment]
I've managed to add a zen mode and produce these packages for linux-zen. Tree is at https://github.com/hexchain/archzfs/tree/linux-zen. Will send PR if it looks good to you.

**Comment by null-git** [comment]
There already is an experimental fix for this:
https://github.com/archzfs/archzfs/issues/75

I don't know how well it's testet though

**Comment by hexchain** [comment]
Except for the headers, the {spl,zfs}-utils can also be shared among packages for different kernels. The only requirement for these utils is that their version must `>=` the kernel modules in use.

**Comment by demizer** [comment]
This kernel is now supported in the archzfs repository.
