### ISSUE TITLE
zfs-linux-git wont mount zfs managed datasets

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#69]
I was using zfs-linux and due to kernel 4.7 supported yet, I attempted switching to zfs-linux-git. For some reason zfs-linux-git is acting differently to zfs-linux and won't automount zfs managed datasets as it does on zfs-linux. I can mount the datasets manually once my system is booted up, but even though they're not set as Legacy data sets, they are not being mounted.

This is not a problem with my pool not being mounted, the pool is mounted fine.

**Comment by demizer** [comment]
Hi. This is because the systemd unit files changed in 0.6.5.8 (contained in the git commit you checked out). I did not realize this at the time I made the package so it did not give a warning after installation/upgrade.

See Issue #72
