### ISSUE TITLE
Add support for DKMS

### ISSUE THREAD

**Issue by MilesBHuff** [archzfs/archzfs#73]
I would be forever grateful if you would provide binaries for the DKMS versions.

**Comment by demizer** [comment]
This has been on the list for a long time. One I finish the automated testing, I will get back to it.

**Comment by Aimilius** [comment]
The `zfs` package from the Antergos repositories uses DKMS, so you could use that as a workaround until archzfs will add support for DKMS.

Install the required keys with
 `# pacman -U http://mirrors.antergos.com/antergos/x86_64/antergos-keyring-20150806-1-any.pkg.tar.xz`

Then add the following to `/etc/pacman.conf`
```
[antergos]
Server = http://mirrors.antergos.com/$repo/$arch
```
And install the `zfs` package.

**Comment by demizer** [comment]
If someone can come on board and help get dkms packages into archzfs that would be great. I don't have enough bandwidth for this unfortunately.

**Comment by minextu** [comment]
working on it
