### ISSUE TITLE
Deadlock on >=4.7 with case insensitive filesystems

### ISSUE THREAD

**Issue by claunia** [archzfs/archzfs#80]
Hi,

This problem has already been solved upstream:
https://github.com/zfsonlinux/zfs/commit/d5b897a6a1da2f031a708fd267b4de2cc9b7a6e2

However it may not do for 0.6.5.9, and I hope it does for 0.7.0-release.

In the meantime you could add it as a manual patch for ArchLinux?

Regards

**Comment by demizer** [comment]
These changes should be included with the current release. Thanks.
