### ISSUE TITLE
Cannot boot from pool on usb "line 48: die: not found"

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#81]
I'm I'm not sure if this is related to #77 since the boot message looks kind of similar. I have been having trouble booting from a secondary pool on my computer with an identical set up to another pool I have running off of mirrored SSDs that boots fine. 

The boot message I'm getting is: 

```
Importing pool tim
cannot import tim no such pool available
/init: line 48: die: not found
cannot open tim/ROOT/default dataset does not exist 
```

At which point I am stuck in the boot prompt. I have tried repeatedly booting into an archiso to troubleshoot, creating a new cache,  resetting the systemd units to the presets, and everything else I can think of. 

I'm not sure if it's related, but the pool I am attempting to boot from is on a usb key. I wonder if the message should say "line 48: device: not found" 

I've given zfs the entire usb key for the pool, and my boot partition is on an ssd which I can boot my main install off no problem. I've tried setting the root bootfs dataset to legacy, and zfs managed.

I'm not sure if this is the right place to bring my problem but I saw the similar error message from issue #77 :

```
/init: line 48: mount: not found
You are now being dropped into an emergency shell:
/init: line 48: can`t open /dev/console: no such file
/init: line 68: stat: not found 
```

I'm using a single root dataset and systemd boot with this config:

```
title   Tim (Arch Linux)
linux   /installs/Tim/vmlinuz-linux
initrd  /installs/Tim/intel-ucode.img
initrd  /installs/Tim/initramfs-linux.img
options zfs=tim/ROOT/default rw
```

The config is the same as my working setup.

**Comment by minextu** [comment]
If you still have this problem: Did you move the `block` hook right after `udev` in /etc/mkinitcpio.conf?

**Comment by johnramsden** [comment]
@minextu I don't think so, i'll give that a try.
