### ISSUE TITLE
linux-lts=4.4.23 support

### ISSUE THREAD

**Issue by bobwya** [archzfs/archzfs#82]
Any chance of revbump for linux-lts=4.4.23 ?
Thanks for your hardwork... :-)

**Comment by stevleibelt** [comment]
I apologize to pollute this issue ticket with a sense of fuzziness.

```
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: spl-linux-lts: installing linux-lts (4.4.25-1) breaks dependency 'linux-lts=4.4.24'
:: zfs-linux-lts: installing linux-lts (4.4.25-1) breaks dependency 'linux-lts=4.4.24'
:: zfs-utils-linux-lts: installing linux-lts (4.4.25-1) breaks dependency 'linux-lts=4.4.24'
#...
```

Again, I don't want to put pressure to you. Hopefully you are on vacation, hopefully not you are under stress or ill.
Is there anything I (located in GMT +1) can do to support you? Do you simple "trigger a build" and release it if tests have passed? If so, feel free to contact [me](https://stev.leibelt.de) to not be the one man show you have been for such a long time.

Kind regards,
Stev
