### ISSUE TITLE
Cant mount sub-datasets at boot

### ISSUE THREAD

**Issue by johnramsden** [archzfs/archzfs#85]
I posted this same issue on the [zfs on linux github](https://github.com/zfsonlinux/zfs/issues/5351) but I was wondering if anyone here could help me as well. Feel free to close this if it doesn't fit here. 

I've been trying to set up a pool with multiple data sets and I feel like I've tried every different combination of legacy data sets and ZFS managed datasets. 

Is there a way to boot from a pool using many subdatasets? 

This is the set-up I am trying to boot from: 

```
vault/ROOT/default              /
vault/home                      /home
vault/tmp                       /tmp
vault/var                       /var
vault/run                       /run
vault/usr                       /usr
vault/usr/local                 /usr/local
vault/usr/lib                   /usr/lib
vault/usr/share                 /usr/share
vault/var/lib                   /var/lib 
```

I can get ```/usr``` and the root dataset to mount, but beyond that I haven't been able to get this setup to boot. 

I've had no problem in the past booting from a set up looking like this: 

```
vault/ROOT/default              /
vault/home                      /home
vault/tmp                       /tmp
vault/var                       /var
vault/usr                       /usr
```

But it seems like when I add the sub-data sets it causes an issue. 

The error message I have continuously gotten is 

Error: Root device mounted successfully, but /sbin/init does not exist. 

Among other errors when I try different combinations of Legacy data sets and zfs managed. 

The way I usually mount them that has worked in the past is: 

```
zfs list
NAME                 USED  AVAIL  REFER  MOUNTPOINT
vault                199G  30.0G    96K  none
vault/ROOT          8.15G  30.0G    96K  none
vault/ROOT/default  8.15G  30.0G  7.82G  /
vault/home           180G  30.0G  75.2G  legacy
vault/tmp            504K  30.0G   376K  /tmp
vault/usr           3.18G  30.0G  1.71G  legacy
vault/var           4.59G  30.0G  1.56G  legacy 
```

I have had this setup currently working on the same computer.

**Comment by jnwatts** [comment]
Might not be your problem, but I seem to recall that some distros don't (didn't?) boot properly if /usr and /usr/local are not on the same mount-point. (And some further that were unable to handle /usr not being the same mount device as root)

**Comment by johnramsden** [comment]
Yea, seems to be /usr, I destroyed vault/usr/local, vault/usr/lib and vault/usr/share and it worked.

**Comment by jnwatts** [comment]
So you're able to boot root and usr separated, just not with separated usr/local? Good to know :-)

**Comment by solenskiner** [comment]
This setup kinda works for me:

```
> sudo zfs list -o name,mountpoint,canmount
flywheel                                         none                         off
flywheel/zroot                                   none                         off
flywheel/zroot/arch                              /arch                        off
flywheel/zroot/arch/root                         /arch                         on
flywheel/zroot/arch/rules                        none                         off
flywheel/zroot/arch/rules/root                   /arch                        off
flywheel/zroot/arch/rules/root/opt               /arch/opt                     on
flywheel/zroot/arch/rules/root/srv               /arch/srv                     on
flywheel/zroot/arch/rules/root/tmp               /arch/tmp                     on
flywheel/zroot/arch/rules/root/usr               /arch/usr                     on
flywheel/zroot/arch/rules/root/usr/local         /arch/usr/local               on
flywheel/zroot/arch/rules/root/var               /arch/var                     on
flywheel/zroot/arch/rules/root/var/tmp           /arch/var/tmp                 on
flywheel/zroot/arch/rules/root_var_lib_postgres  /arch/var/lib/postgres        on

```

Reason it works is that the zfs hook importing the dataset lists all child datasets and mounts them in a loop, checking the canmount property as it goes (the aur zfs-tools doesn't yet tho). As long the datasets you want mounted are sub-datasets it should work.

What doesn't work tho is special flags like exec, devices etc.
