### ISSUE TITLE
Kernel pkgrel version updates (4.8.8-2 -> 4.8.8-3) are not handled correctly breaking bootfs

### ISSUE THREAD

**Issue by lnicola** [archzfs/archzfs#87]
The Arch kernel recently had a couple of updates. The last one will not work with the `archzfs` binary packages, but `pacman` doesn't complain since it believes that `4.8.8-1` and `4.8.8-2` are compatible.

**Comment by fryfrog** [comment]
This just got me, I rolled back to 4.8.7 from package cache. I failed to visually notice that 4.8.8-1 and 4.8.8-2 were different... and so did the package(s). :)

**Comment by lnicola** [comment]
@fryfrog Wouldn't 4.8.7 fail to work in a similar way?

**Comment by thomas-holmes** [comment]
I just got hit by this too. I had to fetch 4.8.8-1 from the arch archives.

**Comment by ejstacey** [comment]
Also hit.  If anyone wants to 4.8.8-1 and don't have it locally, you can grab it from the arch archives here:

https://archive.archlinux.org/packages/l/linux/

**Comment by fryfrog** [comment]
@lnicola, I was installing from package cache where I had all of the 4.8.7 linux and zfs packages. I missed the window where linux 4.8.8-1 and zfs 4.8.8-1 were available at the same time, so I didn't have those packages in my cache to fall back to instead.

**Comment by lnicola** [comment]
@fryfrog ah, of course :smile:

**Comment by ben-kuhn** [comment]
Kernel is up to 4.8.10-1 now.

**Comment by fafische** [comment]
same Problem with 4.8.12-3

>>> Updating ZFS module dependencies
depmod: WARNING: could not open /lib/modules/4.8.12-2-ARCH/modules.order: No such file or directory
depmod: WARNING: could not open /lib/modules/4.8.12-2-ARCH/modules.builtin: No such file or directory

**Comment by demizer** [comment]
This issue will be fixed when #92 is implemented. My scraper scripts to not alert me when the kernel receives pkgrel updates (4.8.8-1 to 4.8.8-2).

**Comment by demizer** [comment]
It's going to be a while before I can consider the "extramodules" packages (issue #92) safe. For now, I am going to make this fix and push out update.
