### ISSUE TITLE
Update for linux-lts (4.4.37-1)

### ISSUE THREAD

**Issue by jacksonatl** [archzfs/archzfs#90]

**Comment by jdn06** [comment]
The AUR package has been updated to 4.4.38 but in the repo the last package is still 4.4.36.

**Comment by KrzaQ** [comment]
Would it be possible to get an ETA?

**Comment by demizer** [comment]
I am trying to upgrade the PKGBUILD so we don't have to rebuild for every point release. There have been too many kernel point releases lately and I can barely keep up. Will be another day or two. @KrzaQ

**Comment by demizer** [comment]
Packages have been pushed, still working on adding extra modules support.

**Comment by storrgie** [comment]
yeah releases are hitting really often... If you're able to design out people pinging you here then that would be awesome! :+1:
