### ISSUE TITLE
Use extramodules to eliminate package rebuilds for minor kernel releases

### ISSUE THREAD

**Issue by demizer** [archzfs/archzfs#92]
Chris sent an email and made a comment on the AUR zfs-linux page informing me that he was able to get the packages working using extramodules; same as the nvidia kernel modules. This will eliminate the need to rebuild the packages for minor kernel releases (4.8.8 -> 4.8.9). I had attempted this four years ago and was not able to get it to work due to upstream support and forgot about it. This would be a major improvement for everyone.

**Comment by storrgie** [comment]
Can you reference this email in some way so that other people might poke into it? It seems like this might be one of the crux issues that generates a lot of tickets for the project.

**Comment by demizer** [comment]
@storrgie absolutely. Email was sent to me by @lnxsrt last October.

> I posted a comment in the zfs-linux AUR about using a dependency of linux>=4.8 instead of linux=4.8.2 so that you don't have to make packages for each kernel point release. Many packages (nvidia, etc) use this method along with the /lib/modules/extramodules-4.8 folder that will remain consistent after a point release kernel update. I have attached a .tgz with the 4 primary zfs-linux packages that have been modified to ignore point releases. It works fine for me, I will note that I made the version 0.6.5.8_4.8.999_1 just to keep yaourt from trying to grab your package from the AUR. Ideally you could start this on 4.9 and just call it 0.6.5.8_4.9_1. Let me know if it would prefer me to fork and submit a merge request on your github.

He also provided an attachment with the changes. I will make a branch and reference it here. Apologies for having this in the backlog for so long, I have been extremely busy at work, but I plan on tackling this this weekend because kernel updates are coming so quickly now and it's painful for all of us.

Thanks!

**Comment by minextu** [comment]
Doesn't work correctly (see #130)
